// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/missions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-missions"
                ],
                "summary": "Danh sách toàn bộ nhiệm vụ (admin, kể cả đã tắt)",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.MissionResponse"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-missions"
                ],
                "summary": "Tạo nhiệm vụ mới (admin)",
                "parameters": [
                    {
                        "description": "Thông tin nhiệm vụ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.MissionRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.MissionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/admin/missions/{id}": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "admin-missions"
                ],
                "summary": "Sửa nhiệm vụ (admin)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Mission ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Thông tin nhiệm vụ",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.MissionRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.MissionResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "tags": [
                    "admin-missions"
                ],
                "summary": "Tắt nhiệm vụ (admin, xoá mềm — giữ lịch sử tiến độ)",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Mission ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Email hoặc username, và mật khẩu",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Mật khẩu 8-72 ký tự. Trả về access token để đăng nhập luôn.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/challenges/rooms": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenges"
                ],
                "summary": "Tạo phòng thử thách",
                "parameters": [
                    {
                        "description": "Cấu hình phòng",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.CreateRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.CreateRoomResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/challenges/rooms/join": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenges"
                ],
                "summary": "Tham gia phòng bằng mã",
                "parameters": [
                    {
                        "description": "Mã phòng",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.JoinRoomRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ParticipantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/challenges/rooms/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenges"
                ],
                "summary": "Thông tin phòng thử thách",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.RoomDetailResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/challenges/rooms/{id}/invite": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenges"
                ],
                "summary": "Mời người chơi vào phòng theo username (chỉ host)",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Username người được mời",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.InviteRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.ParticipantResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/challenges/rooms/{id}/leaderboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "challenges"
                ],
                "summary": "Bảng xếp hạng phòng thử thách",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Room ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/domain.LeaderboardEntryResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/grammar/exercises/{id}/submit": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Chạy song song với check client-side hiện có — chỉ để ghi nhận tiến độ nhiệm vụ.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "Chấm 1 bài tập ngữ pháp",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Exercise ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Câu trả lời",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/handler.submitExerciseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.SubmitExerciseResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/grammar/lessons/{code}": {
            "get": {
                "description": "Nội dung bài học (summary, công thức, dấu hiệu) và danh sách bài tập.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "Chi tiết bài học ngữ pháp",
                "parameters": [
                    {
                        "type": "string",
                        "example": "present_simple",
                        "description": "Lesson code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.GrammarLessonDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/languages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "languages"
                ],
                "summary": "Danh sách ngôn ngữ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.LanguageResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/languages/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "languages"
                ],
                "summary": "Lấy thông tin ngôn ngữ",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Language ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.LanguageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/languages/{id}/grammar": {
            "get": {
                "description": "Mỗi chủ đề kèm danh sách bài học (không gồm nội dung chi tiết).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "Danh sách chủ đề ngữ pháp của một ngôn ngữ",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Language ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.GrammarTopicResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/leaderboard": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Sort theo level, điểm thách đấu (points), hoặc streak (mặc định).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Bảng xếp hạng người học",
                "parameters": [
                    {
                        "type": "string",
                        "example": "level",
                        "description": "level | points | streak",
                        "name": "by",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.LeaderboardEntry"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/missions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Danh sách nhiệm vụ đang active kèm tiến độ của user hiện tại trong kỳ hiện tại.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "missions"
                ],
                "summary": "Nhiệm vụ của tôi",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.MyMissionResponse"
                            }
                        }
                    }
                }
            }
        },
        "/srs/due": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Từ vựng đến hạn ôn tập",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Số lượng tối đa (mặc định 20, tối đa 100)",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Chỉ lấy đến hạn của 1 ngôn ngữ (bỏ trống = tất cả ngôn ngữ)",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.DueVocabulary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/learn": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo review row stage 0, đến hạn ôn ngay. Gọi lại với từ đã học thì giữ nguyên tiến độ.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Đánh dấu đã học từ mới",
                "parameters": [
                    {
                        "description": "Từ vựng đã học",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LearnVocabularyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.LearnVocabularyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/new": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Từ vựng mới chưa học",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Mã ngôn ngữ (mặc định en)",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng tối đa (mặc định 10, tối đa 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.NewVocabulary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/reviews": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Ghi nhận kết quả ôn tập (SM-2)",
                "parameters": [
                    {
                        "description": "Kết quả ôn tập",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.VocabularyReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.VocabularyReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Danh sách user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Thông tin user đang đăng nhập",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Chỉ cập nhật các field được gửi lên.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Cập nhật hồ sơ của user đang đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin cần cập nhật",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lấy thông tin user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vocab/favorites": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Từ vựng yêu thích",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Chỉ lấy 1 ngôn ngữ (bỏ trống = tất cả)",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.VocabularyCard"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vocab/topics": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Danh sách chủ đề của 1 ngôn ngữ kèm số từ user đã đưa vào ôn tập.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Chủ đề từ vựng",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Mã ngôn ngữ (mặc định en)",
                        "name": "language",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.VocabularyTopic"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vocab/words": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Topic truyền qua query vì tên chủ đề có dấu cách/ký tự đặc biệt.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Từ vựng theo chủ đề",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Mã ngôn ngữ (mặc định en)",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "Đồ ăn \u0026 Thức uống",
                        "description": "Tên chủ đề",
                        "name": "topic",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.VocabularyCard"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vocab/{id}/favorite": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Thêm từ vào yêu thích",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Vocabulary ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.FavoriteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Bỏ từ khỏi yêu thích",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Vocabulary ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.FavoriteResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/vocab/{id}/like": {
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Like từ vựng",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Vocabulary ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.LikeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "vocab"
                ],
                "summary": "Bỏ like từ vựng",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "Vocabulary ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.LikeResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.CreateRoomRequest": {
            "type": "object",
            "properties": {
                "difficulty": {
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 1,
                    "example": 2
                },
                "is_practice": {
                    "type": "boolean",
                    "example": false
                },
                "language_id": {
                    "type": "string",
                    "example": "en"
                },
                "question_count": {
                    "type": "integer",
                    "maximum": 50,
                    "minimum": 1,
                    "example": 10
                },
                "time_per_question_seconds": {
                    "type": "integer",
                    "maximum": 120,
                    "minimum": 5,
                    "example": 20
                }
            }
        },
        "domain.CreateRoomResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "AB3K9Z"
                },
                "difficulty": {
                    "type": "integer"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "is_practice": {
                    "type": "boolean"
                },
                "max_participants": {
                    "type": "integer"
                },
                "question_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string",
                    "example": "waiting"
                },
                "time_per_question_seconds": {
                    "type": "integer"
                }
            }
        },
        "domain.InviteRequest": {
            "type": "object",
            "properties": {
                "username": {
                    "type": "string",
                    "example": "nguyenvana"
                }
            }
        },
        "domain.JoinRoomRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "AB3K9Z"
                }
            }
        },
        "domain.LeaderboardEntryResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "rank": {
                    "type": "integer"
                },
                "score": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.LearnVocabularyRequest": {
            "type": "object",
            "properties": {
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "22222222-2222-2222-2222-222222222222"
                }
            }
        },
        "domain.LearnVocabularyResponse": {
            "type": "object",
            "properties": {
                "learned": {
                    "type": "boolean",
                    "example": true
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "domain.ParticipantResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "full_name": {
                    "type": "string"
                },
                "joined_at": {
                    "type": "string"
                },
                "room_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "score": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "domain.RoomDetailResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "difficulty": {
                    "type": "integer"
                },
                "host_user_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "is_practice": {
                    "type": "boolean"
                },
                "participants": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/domain.ParticipantResponse"
                    }
                },
                "question_count": {
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "time_per_question_seconds": {
                    "type": "integer"
                }
            }
        },
        "domain.VocabularyReviewRequest": {
            "type": "object",
            "properties": {
                "quality": {
                    "description": "0 -\u003e 5",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 0,
                    "example": 4
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "22222222-2222-2222-2222-222222222222"
                }
            }
        },
        "domain.VocabularyReviewResponse": {
            "type": "object",
            "properties": {
                "interval_days": {
                    "type": "integer",
                    "example": 1
                },
                "new_stage": {
                    "type": "integer",
                    "example": 1
                },
                "next_review_at": {
                    "type": "string"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "không tìm thấy dữ liệu"
                }
            }
        },
        "handler.submitExerciseRequest": {
            "type": "object",
            "properties": {
                "answer": {
                    "type": "string",
                    "example": "goes"
                }
            }
        },
        "service.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                },
                "user": {
                    "$ref": "#/definitions/service.UserResponse"
                }
            }
        },
        "service.DueVocabulary": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "language_id": {
                    "type": "string",
                    "example": "en"
                },
                "meaning": {
                    "type": "string"
                },
                "next_review_at": {
                    "type": "string"
                },
                "phonetic": {
                    "type": "string"
                },
                "srs_stage": {
                    "type": "integer"
                },
                "term": {
                    "type": "string",
                    "example": "apple"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.FavoriteResponse": {
            "type": "object",
            "properties": {
                "favorited": {
                    "type": "boolean"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.GrammarExerciseResponse": {
            "type": "object",
            "properties": {
                "correct_answer": {
                    "type": "string",
                    "example": "goes"
                },
                "explanation": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "question": {
                    "type": "string",
                    "example": "She _______ to school every day."
                },
                "type": {
                    "type": "string",
                    "example": "MULTIPLE_CHOICE"
                }
            }
        },
        "service.GrammarLessonDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "present_simple"
                },
                "content": {
                    "type": "object"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.GrammarExerciseResponse"
                    }
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "title": {
                    "type": "string",
                    "example": "Thì Hiện Tại Đơn (Present Simple)"
                }
            }
        },
        "service.GrammarLessonSummary": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "present_simple"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "order_index": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "Thì Hiện Tại Đơn (Present Simple)"
                }
            }
        },
        "service.GrammarTopicResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "english_12_tenses"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "lessons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.GrammarLessonSummary"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "12 Thì Trong Tiếng Anh"
                }
            }
        },
        "service.LanguageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "en-US"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "English"
                }
            }
        },
        "service.LeaderboardEntry": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "exp": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "level": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "rank": {
                    "type": "integer"
                },
                "streak_count": {
                    "type": "integer"
                },
                "user_id": {
                    "type": "string",
                    "format": "uuid"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "service.LikeResponse": {
            "type": "object",
            "properties": {
                "like_count": {
                    "type": "integer"
                },
                "liked": {
                    "type": "boolean"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.LoginRequest": {
            "type": "object",
            "properties": {
                "identifier": {
                    "type": "string",
                    "example": "user@laclingo.vn"
                },
                "password": {
                    "type": "string",
                    "example": "matkhau123"
                }
            }
        },
        "service.MissionRequest": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string",
                    "enum": [
                        "srs_review",
                        "learn_word",
                        "grammar_exercise",
                        "challenge_participate",
                        "challenge_win"
                    ],
                    "example": "srs_review"
                },
                "description": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "is_active": {
                    "type": "boolean"
                },
                "period": {
                    "type": "string",
                    "enum": [
                        "daily",
                        "weekly",
                        "monthly",
                        "event"
                    ],
                    "example": "daily"
                },
                "reward_exp": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 50
                },
                "reward_points": {
                    "type": "integer",
                    "minimum": 0,
                    "example": 10
                },
                "starts_at": {
                    "type": "string"
                },
                "target_count": {
                    "type": "integer",
                    "minimum": 1,
                    "example": 10
                },
                "title": {
                    "type": "string",
                    "example": "Ôn tập 10 từ hôm nay"
                }
            }
        },
        "service.MissionResponse": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "ends_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "is_active": {
                    "type": "boolean"
                },
                "period": {
                    "type": "string"
                },
                "reward_exp": {
                    "type": "integer"
                },
                "reward_points": {
                    "type": "integer"
                },
                "starts_at": {
                    "type": "string"
                },
                "target_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.MyMissionResponse": {
            "type": "object",
            "properties": {
                "action_type": {
                    "type": "string"
                },
                "completed": {
                    "type": "boolean"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "period": {
                    "type": "string"
                },
                "progress_count": {
                    "type": "integer"
                },
                "reward_exp": {
                    "type": "integer"
                },
                "reward_points": {
                    "type": "integer"
                },
                "target_count": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "service.NewVocabulary": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "example": {
                    "type": "string"
                },
                "language_id": {
                    "type": "string",
                    "example": "en"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "meaning": {
                    "type": "string"
                },
                "phonetic": {
                    "type": "string"
                },
                "term": {
                    "type": "string",
                    "example": "apple"
                },
                "topic": {
                    "type": "string",
                    "example": "Đồ ăn \u0026 Thức uống"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@laclingo.vn"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "Nguyễn Văn A"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8,
                    "example": "matkhau123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "nguyenvana"
                }
            }
        },
        "service.SubmitExerciseResponse": {
            "type": "object",
            "properties": {
                "correct": {
                    "type": "boolean"
                }
            }
        },
        "service.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "Nguyễn Văn A"
                }
            }
        },
        "service.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "user@laclingo.vn"
                },
                "exp": {
                    "type": "integer"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "level": {
                    "type": "integer"
                },
                "points": {
                    "type": "integer"
                },
                "role": {
                    "type": "string",
                    "example": "user"
                },
                "streak_count": {
                    "type": "integer"
                },
                "username": {
                    "type": "string",
                    "example": "nguyenvana"
                }
            }
        },
        "service.VocabularyCard": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "example": {
                    "type": "string"
                },
                "favorited": {
                    "type": "boolean"
                },
                "image_emoji": {
                    "description": "từ không có emoji riêng thì lấy icon chủ đề",
                    "type": "string",
                    "example": "🍎"
                },
                "image_url": {
                    "type": "string"
                },
                "in_review": {
                    "description": "đã có trong hàng đợi ôn tập SRS",
                    "type": "boolean"
                },
                "language_id": {
                    "type": "string",
                    "example": "en"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "like_count": {
                    "type": "integer"
                },
                "liked": {
                    "type": "boolean"
                },
                "meaning": {
                    "type": "string"
                },
                "phonetic": {
                    "type": "string"
                },
                "term": {
                    "type": "string",
                    "example": "apple"
                },
                "topic": {
                    "type": "string"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.VocabularyTopic": {
            "type": "object",
            "properties": {
                "icon": {
                    "type": "string",
                    "example": "🍜"
                },
                "learned": {
                    "description": "số từ đã vào hàng đợi SRS",
                    "type": "integer",
                    "example": 12
                },
                "name": {
                    "type": "string",
                    "example": "Đồ ăn \u0026 Thức uống"
                },
                "total": {
                    "type": "integer",
                    "example": 25
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Nhập \"Bearer \u003caccess_token\u003e\" (lấy từ /auth/login hoặc /auth/register)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LacLingo API",
	Description:      "API học ngôn ngữ với thuật toán SRS (SM-2).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
