// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng nhập",
                "parameters": [
                    {
                        "description": "Email hoặc username, và mật khẩu",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.LoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/register": {
            "post": {
                "description": "Mật khẩu 8-72 ký tự. Trả về access token để đăng nhập luôn.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Đăng ký tài khoản",
                "parameters": [
                    {
                        "description": "Thông tin đăng ký",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.RegisterRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/service.AuthResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/grammar/lessons/{code}": {
            "get": {
                "description": "Nội dung bài học (summary, công thức, dấu hiệu) và danh sách bài tập.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "Chi tiết bài học ngữ pháp",
                "parameters": [
                    {
                        "type": "string",
                        "example": "present_simple",
                        "description": "Lesson code",
                        "name": "code",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.GrammarLessonDetail"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/languages": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "languages"
                ],
                "summary": "Danh sách ngôn ngữ",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.LanguageResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/languages/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "languages"
                ],
                "summary": "Lấy thông tin ngôn ngữ",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Language ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.LanguageResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/languages/{id}/grammar": {
            "get": {
                "description": "Mỗi chủ đề kèm danh sách bài học (không gồm nội dung chi tiết).",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "grammar"
                ],
                "summary": "Danh sách chủ đề ngữ pháp của một ngôn ngữ",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Language ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.GrammarTopicResponse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/due": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Từ vựng đến hạn ôn tập",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Số lượng tối đa (mặc định 20, tối đa 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.DueVocabulary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/learn": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Tạo review row stage 0, đến hạn ôn ngay. Gọi lại với từ đã học thì giữ nguyên tiến độ.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Đánh dấu đã học từ mới",
                "parameters": [
                    {
                        "description": "Từ vựng đã học",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.LearnVocabularyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.LearnVocabularyResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/new": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Từ vựng mới chưa học",
                "parameters": [
                    {
                        "type": "string",
                        "example": "en",
                        "description": "Mã ngôn ngữ (mặc định en)",
                        "name": "language",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Số lượng tối đa (mặc định 10, tối đa 100)",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.NewVocabulary"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/srs/reviews": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "srs"
                ],
                "summary": "Ghi nhận kết quả ôn tập (SM-2)",
                "parameters": [
                    {
                        "description": "Kết quả ôn tập",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/domain.VocabularyReviewRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/domain.VocabularyReviewResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Danh sách user",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/service.UserResponse"
                            }
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/me": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Thông tin user đang đăng nhập",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            },
            "patch": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Chỉ cập nhật các field được gửi lên.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Cập nhật hồ sơ của user đang đăng nhập",
                "parameters": [
                    {
                        "description": "Thông tin cần cập nhật",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/service.UpdateProfileRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "users"
                ],
                "summary": "Lấy thông tin user",
                "parameters": [
                    {
                        "type": "string",
                        "format": "uuid",
                        "description": "User ID (UUID)",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/service.UserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "domain.LearnVocabularyRequest": {
            "type": "object",
            "properties": {
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "22222222-2222-2222-2222-222222222222"
                }
            }
        },
        "domain.LearnVocabularyResponse": {
            "type": "object",
            "properties": {
                "learned": {
                    "type": "boolean",
                    "example": true
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "domain.VocabularyReviewRequest": {
            "type": "object",
            "properties": {
                "quality": {
                    "description": "0 -\u003e 5",
                    "type": "integer",
                    "maximum": 5,
                    "minimum": 0,
                    "example": 4
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid",
                    "example": "22222222-2222-2222-2222-222222222222"
                }
            }
        },
        "domain.VocabularyReviewResponse": {
            "type": "object",
            "properties": {
                "interval_days": {
                    "type": "integer",
                    "example": 1
                },
                "new_stage": {
                    "type": "integer",
                    "example": 1
                },
                "next_review_at": {
                    "type": "string"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "không tìm thấy dữ liệu"
                }
            }
        },
        "service.AuthResponse": {
            "type": "object",
            "properties": {
                "access_token": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "token_type": {
                    "type": "string",
                    "example": "Bearer"
                },
                "user": {
                    "$ref": "#/definitions/service.UserResponse"
                }
            }
        },
        "service.DueVocabulary": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "meaning": {
                    "type": "string"
                },
                "next_review_at": {
                    "type": "string"
                },
                "phonetic": {
                    "type": "string"
                },
                "srs_stage": {
                    "type": "integer"
                },
                "term": {
                    "type": "string",
                    "example": "apple"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.GrammarExerciseResponse": {
            "type": "object",
            "properties": {
                "correct_answer": {
                    "type": "string",
                    "example": "goes"
                },
                "explanation": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "options": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "question": {
                    "type": "string",
                    "example": "She _______ to school every day."
                },
                "type": {
                    "type": "string",
                    "example": "MULTIPLE_CHOICE"
                }
            }
        },
        "service.GrammarLessonDetail": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "present_simple"
                },
                "content": {
                    "type": "object"
                },
                "exercises": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.GrammarExerciseResponse"
                    }
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "title": {
                    "type": "string",
                    "example": "Thì Hiện Tại Đơn (Present Simple)"
                }
            }
        },
        "service.GrammarLessonSummary": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "present_simple"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "order_index": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "Thì Hiện Tại Đơn (Present Simple)"
                }
            }
        },
        "service.GrammarTopicResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "english_12_tenses"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "lessons": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/service.GrammarLessonSummary"
                    }
                },
                "order_index": {
                    "type": "integer"
                },
                "title": {
                    "type": "string",
                    "example": "12 Thì Trong Tiếng Anh"
                }
            }
        },
        "service.LanguageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string",
                    "example": "en-US"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "example": "en"
                },
                "name": {
                    "type": "string",
                    "example": "English"
                }
            }
        },
        "service.LoginRequest": {
            "type": "object",
            "properties": {
                "identifier": {
                    "type": "string",
                    "example": "user@laclingo.vn"
                },
                "password": {
                    "type": "string",
                    "example": "matkhau123"
                }
            }
        },
        "service.NewVocabulary": {
            "type": "object",
            "properties": {
                "audio_url": {
                    "type": "string"
                },
                "example": {
                    "type": "string"
                },
                "level": {
                    "type": "string",
                    "example": "A1"
                },
                "meaning": {
                    "type": "string"
                },
                "phonetic": {
                    "type": "string"
                },
                "term": {
                    "type": "string",
                    "example": "apple"
                },
                "topic": {
                    "type": "string",
                    "example": "Đồ ăn \u0026 Thức uống"
                },
                "vocabulary_id": {
                    "type": "string",
                    "format": "uuid"
                }
            }
        },
        "service.RegisterRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string",
                    "example": "user@laclingo.vn"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "Nguyễn Văn A"
                },
                "password": {
                    "type": "string",
                    "maxLength": 72,
                    "minLength": 8,
                    "example": "matkhau123"
                },
                "username": {
                    "type": "string",
                    "maxLength": 50,
                    "minLength": 3,
                    "example": "nguyenvana"
                }
            }
        },
        "service.UpdateProfileRequest": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string",
                    "example": "https://example.com/avatar.png"
                },
                "full_name": {
                    "type": "string",
                    "maxLength": 100,
                    "example": "Nguyễn Văn A"
                }
            }
        },
        "service.UserResponse": {
            "type": "object",
            "properties": {
                "avatar_url": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "email": {
                    "type": "string",
                    "example": "user@laclingo.vn"
                },
                "full_name": {
                    "type": "string"
                },
                "id": {
                    "type": "string",
                    "format": "uuid"
                },
                "streak_count": {
                    "type": "integer"
                },
                "username": {
                    "type": "string",
                    "example": "nguyenvana"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Nhập \"Bearer \u003caccess_token\u003e\" (lấy từ /auth/login hoặc /auth/register)",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "LacLingo API",
	Description:      "API học ngôn ngữ với thuật toán SRS (SM-2).",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
