-- =============================================================================
-- Seed từ vựng tiếng Anh A1-A2 — 12 chủ đề x 25 từ = 300 từ
-- Idempotent: ON CONFLICT (language_id, term) DO NOTHING
-- Chạy: docker exec -i laclingo_postgres psql -U laclingo_user -d laclingo_db < packages/database/seeds_vocabulary.sql
-- =============================================================================

-- 1. Gia đình & Con người
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'family', 'ˈfæməli', 'gia đình', 'My family has four people.', 'Gia đình & Con người', 'A1'),
('en', 'father', 'ˈfɑːðər', 'bố, cha', 'My father works in a bank.', 'Gia đình & Con người', 'A1'),
('en', 'mother', 'ˈmʌðər', 'mẹ', 'My mother cooks very well.', 'Gia đình & Con người', 'A1'),
('en', 'brother', 'ˈbrʌðər', 'anh/em trai', 'My brother is ten years old.', 'Gia đình & Con người', 'A1'),
('en', 'sister', 'ˈsɪstər', 'chị/em gái', 'My sister likes music.', 'Gia đình & Con người', 'A1'),
('en', 'parents', 'ˈpeərənts', 'bố mẹ', 'My parents live in Hanoi.', 'Gia đình & Con người', 'A1'),
('en', 'grandfather', 'ˈɡrænfɑːðər', 'ông', 'My grandfather tells great stories.', 'Gia đình & Con người', 'A1'),
('en', 'grandmother', 'ˈɡrænmʌðər', 'bà', 'My grandmother makes cakes.', 'Gia đình & Con người', 'A1'),
('en', 'son', 'sʌn', 'con trai', 'Their son plays football.', 'Gia đình & Con người', 'A1'),
('en', 'daughter', 'ˈdɔːtər', 'con gái', 'Her daughter is a student.', 'Gia đình & Con người', 'A1'),
('en', 'husband', 'ˈhʌzbənd', 'chồng', 'Her husband is a teacher.', 'Gia đình & Con người', 'A1'),
('en', 'wife', 'waɪf', 'vợ', 'His wife works at a hospital.', 'Gia đình & Con người', 'A1'),
('en', 'baby', 'ˈbeɪbi', 'em bé', 'The baby is sleeping now.', 'Gia đình & Con người', 'A1'),
('en', 'child', 'tʃaɪld', 'đứa trẻ', 'Every child needs love.', 'Gia đình & Con người', 'A1'),
('en', 'friend', 'frend', 'bạn bè', 'She is my best friend.', 'Gia đình & Con người', 'A1'),
('en', 'neighbor', 'ˈneɪbər', 'hàng xóm', 'Our neighbor is very friendly.', 'Gia đình & Con người', 'A2'),
('en', 'uncle', 'ˈʌŋkl', 'chú, bác, cậu', 'My uncle lives in Da Nang.', 'Gia đình & Con người', 'A1'),
('en', 'aunt', 'ɑːnt', 'cô, dì, bác gái', 'My aunt has two children.', 'Gia đình & Con người', 'A1'),
('en', 'cousin', 'ˈkʌzn', 'anh chị em họ', 'My cousin studies abroad.', 'Gia đình & Con người', 'A2'),
('en', 'twin', 'twɪn', 'sinh đôi', 'They are twin brothers.', 'Gia đình & Con người', 'A2'),
('en', 'person', 'ˈpɜːrsn', 'người', 'He is a kind person.', 'Gia đình & Con người', 'A1'),
('en', 'people', 'ˈpiːpl', 'mọi người', 'Many people like coffee.', 'Gia đình & Con người', 'A1'),
('en', 'man', 'mæn', 'đàn ông', 'That man is my teacher.', 'Gia đình & Con người', 'A1'),
('en', 'woman', 'ˈwʊmən', 'phụ nữ', 'The woman wears a red dress.', 'Gia đình & Con người', 'A1'),
('en', 'teenager', 'ˈtiːneɪdʒər', 'thanh thiếu niên', 'Teenagers love social media.', 'Gia đình & Con người', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 2. Đồ ăn & Thức uống
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'rice', 'raɪs', 'cơm, gạo', 'We eat rice every day.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'bread', 'bred', 'bánh mì', 'I have bread for breakfast.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'egg', 'eɡ', 'trứng', 'She eats two eggs a day.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'milk', 'mɪlk', 'sữa', 'Children drink milk at night.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'water', 'ˈwɔːtər', 'nước', 'Drink more water every day.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'coffee', 'ˈkɒfi', 'cà phê', 'He drinks coffee in the morning.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'tea', 'tiː', 'trà', 'My grandmother loves green tea.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'juice', 'dʒuːs', 'nước ép', 'Orange juice is my favorite.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'meat', 'miːt', 'thịt', 'I do not eat much meat.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'chicken', 'ˈtʃɪkɪn', 'thịt gà', 'We had chicken for dinner.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'beef', 'biːf', 'thịt bò', 'This beef noodle soup is tasty.', 'Đồ ăn & Thức uống', 'A2'),
('en', 'fish', 'fɪʃ', 'cá', 'Fish is good for your brain.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'vegetable', 'ˈvedʒtəbl', 'rau củ', 'Eat more vegetables to stay healthy.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'fruit', 'fruːt', 'trái cây', 'Fruit is sweet and healthy.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'apple', 'ˈæpl', 'quả táo', 'An apple a day keeps the doctor away.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'banana', 'bəˈnɑːnə', 'quả chuối', 'Monkeys love bananas.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'orange', 'ˈɒrɪndʒ', 'quả cam', 'This orange is very sweet.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'noodle', 'ˈnuːdl', 'mì, phở', 'Vietnamese noodles are famous.', 'Đồ ăn & Thức uống', 'A2'),
('en', 'soup', 'suːp', 'súp, canh', 'Hot soup is great in winter.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'salad', 'ˈsæləd', 'rau trộn', 'I ordered a chicken salad.', 'Đồ ăn & Thức uống', 'A2'),
('en', 'cake', 'keɪk', 'bánh ngọt', 'She made a birthday cake.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'sugar', 'ˈʃʊɡər', 'đường', 'Too much sugar is bad for you.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'salt', 'sɔːlt', 'muối', 'Add a little salt to the soup.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'breakfast', 'ˈbrekfəst', 'bữa sáng', 'Breakfast is the most important meal.', 'Đồ ăn & Thức uống', 'A1'),
('en', 'dinner', 'ˈdɪnər', 'bữa tối', 'We have dinner at seven.', 'Đồ ăn & Thức uống', 'A1')
ON CONFLICT (language_id, term) DO NOTHING;

-- 3. Nhà cửa & Đồ vật
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'house', 'haʊs', 'ngôi nhà', 'They live in a big house.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'room', 'ruːm', 'căn phòng', 'My room is small but clean.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'kitchen', 'ˈkɪtʃɪn', 'nhà bếp', 'Mom is cooking in the kitchen.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'bedroom', 'ˈbedruːm', 'phòng ngủ', 'The bedroom has two windows.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'bathroom', 'ˈbɑːθruːm', 'phòng tắm', 'The bathroom is upstairs.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'door', 'dɔːr', 'cửa ra vào', 'Please close the door.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'window', 'ˈwɪndoʊ', 'cửa sổ', 'Open the window for fresh air.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'table', 'ˈteɪbl', 'cái bàn', 'The book is on the table.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'chair', 'tʃeər', 'cái ghế', 'This chair is very comfortable.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'bed', 'bed', 'cái giường', 'I go to bed at ten.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'lamp', 'læmp', 'cái đèn', 'Turn on the lamp, please.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'fridge', 'frɪdʒ', 'tủ lạnh', 'The milk is in the fridge.', 'Nhà cửa & Đồ vật', 'A2'),
('en', 'television', 'ˈtelɪvɪʒn', 'ti vi', 'We watch television after dinner.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'phone', 'foʊn', 'điện thoại', 'My phone is out of battery.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'computer', 'kəmˈpjuːtər', 'máy tính', 'He plays games on his computer.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'clock', 'klɒk', 'đồng hồ treo', 'The clock on the wall is old.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'key', 'kiː', 'chìa khóa', 'I lost my house key.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'mirror', 'ˈmɪrər', 'cái gương', 'She looks in the mirror.', 'Nhà cửa & Đồ vật', 'A2'),
('en', 'cupboard', 'ˈkʌbərd', 'tủ chén, tủ đồ', 'The cups are in the cupboard.', 'Nhà cửa & Đồ vật', 'A2'),
('en', 'sofa', 'ˈsoʊfə', 'ghế sô pha', 'The cat sleeps on the sofa.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'floor', 'flɔːr', 'sàn nhà, tầng', 'My office is on the third floor.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'wall', 'wɔːl', 'bức tường', 'There is a picture on the wall.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'garden', 'ˈɡɑːrdn', 'khu vườn', 'She grows flowers in the garden.', 'Nhà cửa & Đồ vật', 'A1'),
('en', 'stairs', 'steərz', 'cầu thang', 'Take the stairs to the second floor.', 'Nhà cửa & Đồ vật', 'A2'),
('en', 'roof', 'ruːf', 'mái nhà', 'The roof is red.', 'Nhà cửa & Đồ vật', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 4. Trường học & Học tập
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'school', 'skuːl', 'trường học', 'Our school has a big library.', 'Trường học & Học tập', 'A1'),
('en', 'teacher', 'ˈtiːtʃər', 'giáo viên', 'The teacher explains the lesson.', 'Trường học & Học tập', 'A1'),
('en', 'student', 'ˈstjuːdnt', 'học sinh, sinh viên', 'Every student has a notebook.', 'Trường học & Học tập', 'A1'),
('en', 'classroom', 'ˈklɑːsruːm', 'lớp học', 'The classroom is on the first floor.', 'Trường học & Học tập', 'A1'),
('en', 'lesson', 'ˈlesn', 'bài học', 'Today''s lesson is about verbs.', 'Trường học & Học tập', 'A1'),
('en', 'homework', 'ˈhoʊmwɜːrk', 'bài tập về nhà', 'I finish my homework before dinner.', 'Trường học & Học tập', 'A1'),
('en', 'book', 'bʊk', 'quyển sách', 'This book is very interesting.', 'Trường học & Học tập', 'A1'),
('en', 'notebook', 'ˈnoʊtbʊk', 'quyển vở', 'Write the new words in your notebook.', 'Trường học & Học tập', 'A1'),
('en', 'pen', 'pen', 'cái bút', 'Can I borrow your pen?', 'Trường học & Học tập', 'A1'),
('en', 'pencil', 'ˈpensl', 'bút chì', 'Draw with a pencil first.', 'Trường học & Học tập', 'A1'),
('en', 'exam', 'ɪɡˈzæm', 'kỳ thi', 'The exam starts at eight.', 'Trường học & Học tập', 'A2'),
('en', 'test', 'test', 'bài kiểm tra', 'We have an English test today.', 'Trường học & Học tập', 'A1'),
('en', 'question', 'ˈkwestʃən', 'câu hỏi', 'May I ask a question?', 'Trường học & Học tập', 'A1'),
('en', 'answer', 'ˈɑːnsər', 'câu trả lời', 'Your answer is correct.', 'Trường học & Học tập', 'A1'),
('en', 'library', 'ˈlaɪbrəri', 'thư viện', 'I study in the library.', 'Trường học & Học tập', 'A1'),
('en', 'dictionary', 'ˈdɪkʃənri', 'từ điển', 'Look up new words in a dictionary.', 'Trường học & Học tập', 'A2'),
('en', 'language', 'ˈlæŋɡwɪdʒ', 'ngôn ngữ', 'English is a global language.', 'Trường học & Học tập', 'A1'),
('en', 'word', 'wɜːrd', 'từ, chữ', 'Learn five new words a day.', 'Trường học & Học tập', 'A1'),
('en', 'sentence', 'ˈsentəns', 'câu văn', 'Make a sentence with this word.', 'Trường học & Học tập', 'A2'),
('en', 'grammar', 'ˈɡræmər', 'ngữ pháp', 'Grammar helps you speak correctly.', 'Trường học & Học tập', 'A2'),
('en', 'subject', 'ˈsʌbdʒɪkt', 'môn học', 'Math is my favorite subject.', 'Trường học & Học tập', 'A2'),
('en', 'university', 'ˌjuːnɪˈvɜːrsəti', 'trường đại học', 'She studies at a university in Hue.', 'Trường học & Học tập', 'A2'),
('en', 'learn', 'lɜːrn', 'học, học hỏi', 'We learn English together.', 'Trường học & Học tập', 'A1'),
('en', 'teach', 'tiːtʃ', 'dạy học', 'He teaches math at high school.', 'Trường học & Học tập', 'A1'),
('en', 'practice', 'ˈpræktɪs', 'luyện tập', 'Practice speaking every day.', 'Trường học & Học tập', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 5. Công việc & Nghề nghiệp
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'job', 'dʒɒb', 'công việc', 'She found a new job last month.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'work', 'wɜːrk', 'làm việc', 'I work from nine to five.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'office', 'ˈɒfɪs', 'văn phòng', 'Our office is in the city center.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'doctor', 'ˈdɒktər', 'bác sĩ', 'The doctor checks my health.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'nurse', 'nɜːrs', 'y tá', 'The nurse is very gentle.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'engineer', 'ˌendʒɪˈnɪər', 'kỹ sư', 'My brother is a software engineer.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'farmer', 'ˈfɑːrmər', 'nông dân', 'The farmer grows rice.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'driver', 'ˈdraɪvər', 'tài xế', 'The taxi driver knows the way.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'police officer', 'pəˈliːs ˌɒfɪsər', 'cảnh sát', 'The police officer helped the old man.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'chef', 'ʃef', 'đầu bếp', 'The chef cooks delicious food.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'singer', 'ˈsɪŋər', 'ca sĩ', 'That singer has a beautiful voice.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'worker', 'ˈwɜːrkər', 'công nhân', 'The workers build a new bridge.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'manager', 'ˈmænɪdʒər', 'quản lý', 'The manager leads our team.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'salary', 'ˈsæləri', 'lương', 'He gets his salary every month.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'meeting', 'ˈmiːtɪŋ', 'cuộc họp', 'We have a meeting at ten.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'company', 'ˈkʌmpəni', 'công ty', 'She works for a big company.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'boss', 'bɒs', 'sếp', 'My boss is friendly and fair.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'customer', 'ˈkʌstəmər', 'khách hàng', 'The customer is always right.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'email', 'ˈiːmeɪl', 'thư điện tử', 'Send me an email tomorrow.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'report', 'rɪˈpɔːrt', 'báo cáo', 'Finish the report by Friday.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'busy', 'ˈbɪzi', 'bận rộn', 'I am busy this week.', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'free', 'friː', 'rảnh rỗi, miễn phí', 'Are you free this afternoon?', 'Công việc & Nghề nghiệp', 'A1'),
('en', 'interview', 'ˈɪntərvjuː', 'phỏng vấn', 'She has a job interview on Monday.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'skill', 'skɪl', 'kỹ năng', 'Speaking is an important skill.', 'Công việc & Nghề nghiệp', 'A2'),
('en', 'team', 'tiːm', 'đội, nhóm', 'Our team works well together.', 'Công việc & Nghề nghiệp', 'A1')
ON CONFLICT (language_id, term) DO NOTHING;

-- 6. Du lịch & Phương tiện
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'travel', 'ˈtrævl', 'du lịch, di chuyển', 'I love to travel in summer.', 'Du lịch & Phương tiện', 'A1'),
('en', 'trip', 'trɪp', 'chuyến đi', 'Our trip to Sapa was amazing.', 'Du lịch & Phương tiện', 'A1'),
('en', 'airport', 'ˈeərpɔːrt', 'sân bay', 'The airport is far from here.', 'Du lịch & Phương tiện', 'A1'),
('en', 'airplane', 'ˈeərpleɪn', 'máy bay', 'The airplane lands at noon.', 'Du lịch & Phương tiện', 'A1'),
('en', 'train', 'treɪn', 'tàu hỏa', 'We took a train to Hue.', 'Du lịch & Phương tiện', 'A1'),
('en', 'bus', 'bʌs', 'xe buýt', 'The bus comes every ten minutes.', 'Du lịch & Phương tiện', 'A1'),
('en', 'car', 'kɑːr', 'ô tô', 'His car is black and new.', 'Du lịch & Phương tiện', 'A1'),
('en', 'bicycle', 'ˈbaɪsɪkl', 'xe đạp', 'I ride my bicycle to school.', 'Du lịch & Phương tiện', 'A1'),
('en', 'motorbike', 'ˈmoʊtərbaɪk', 'xe máy', 'Motorbikes are popular in Vietnam.', 'Du lịch & Phương tiện', 'A2'),
('en', 'taxi', 'ˈtæksi', 'xe taxi', 'Let''s take a taxi to the hotel.', 'Du lịch & Phương tiện', 'A1'),
('en', 'ticket', 'ˈtɪkɪt', 'vé', 'I bought two tickets for the show.', 'Du lịch & Phương tiện', 'A1'),
('en', 'passport', 'ˈpæspɔːrt', 'hộ chiếu', 'Do not forget your passport.', 'Du lịch & Phương tiện', 'A2'),
('en', 'hotel', 'hoʊˈtel', 'khách sạn', 'The hotel is near the beach.', 'Du lịch & Phương tiện', 'A1'),
('en', 'map', 'mæp', 'bản đồ', 'Check the map before you go.', 'Du lịch & Phương tiện', 'A1'),
('en', 'beach', 'biːtʃ', 'bãi biển', 'Children play on the beach.', 'Du lịch & Phương tiện', 'A1'),
('en', 'mountain', 'ˈmaʊntən', 'ngọn núi', 'We climbed the mountain at dawn.', 'Du lịch & Phương tiện', 'A1'),
('en', 'city', 'ˈsɪti', 'thành phố', 'Hanoi is a busy city.', 'Du lịch & Phương tiện', 'A1'),
('en', 'village', 'ˈvɪlɪdʒ', 'làng quê', 'My grandparents live in a village.', 'Du lịch & Phương tiện', 'A2'),
('en', 'street', 'striːt', 'con đường, phố', 'The street is full of shops.', 'Du lịch & Phương tiện', 'A1'),
('en', 'bridge', 'brɪdʒ', 'cây cầu', 'The bridge crosses the river.', 'Du lịch & Phương tiện', 'A2'),
('en', 'station', 'ˈsteɪʃn', 'nhà ga, trạm', 'Meet me at the train station.', 'Du lịch & Phương tiện', 'A1'),
('en', 'luggage', 'ˈlʌɡɪdʒ', 'hành lý', 'My luggage is too heavy.', 'Du lịch & Phương tiện', 'A2'),
('en', 'tourist', 'ˈtʊərɪst', 'khách du lịch', 'Many tourists visit Ha Long Bay.', 'Du lịch & Phương tiện', 'A2'),
('en', 'direction', 'dəˈrekʃn', 'phương hướng', 'Ask for directions if you are lost.', 'Du lịch & Phương tiện', 'A2'),
('en', 'journey', 'ˈdʒɜːrni', 'hành trình', 'The journey takes three hours.', 'Du lịch & Phương tiện', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 7. Thiên nhiên & Thời tiết
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'weather', 'ˈweðər', 'thời tiết', 'The weather is nice today.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'sun', 'sʌn', 'mặt trời', 'The sun rises in the east.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'moon', 'muːn', 'mặt trăng', 'The moon is bright tonight.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'star', 'stɑːr', 'ngôi sao', 'We counted stars in the sky.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'sky', 'skaɪ', 'bầu trời', 'The sky is blue and clear.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'rain', 'reɪn', 'mưa', 'It often rains in July.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'wind', 'wɪnd', 'gió', 'The wind blows from the sea.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'cloud', 'klaʊd', 'đám mây', 'Dark clouds mean rain is coming.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'storm', 'stɔːrm', 'cơn bão', 'The storm broke many trees.', 'Thiên nhiên & Thời tiết', 'A2'),
('en', 'snow', 'snoʊ', 'tuyết', 'It never snows in Saigon.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'hot', 'hɒt', 'nóng', 'Summer in Vietnam is very hot.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'cold', 'koʊld', 'lạnh', 'Wear a coat, it is cold outside.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'warm', 'wɔːrm', 'ấm áp', 'Spring days are warm and sunny.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'cool', 'kuːl', 'mát mẻ', 'Autumn weather is cool.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'tree', 'triː', 'cái cây', 'Birds sing on the tree.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'flower', 'ˈflaʊər', 'bông hoa', 'She picked a yellow flower.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'grass', 'ɡrɑːs', 'cỏ', 'The grass is green after rain.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'river', 'ˈrɪvər', 'dòng sông', 'The river flows to the sea.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'sea', 'siː', 'biển', 'We swim in the sea every summer.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'lake', 'leɪk', 'hồ nước', 'Hoan Kiem Lake is in Hanoi.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'forest', 'ˈfɒrɪst', 'rừng', 'Many animals live in the forest.', 'Thiên nhiên & Thời tiết', 'A2'),
('en', 'animal', 'ˈænɪml', 'động vật', 'My favorite animal is the cat.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'bird', 'bɜːrd', 'con chim', 'A small bird sits on the roof.', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'season', 'ˈsiːzn', 'mùa', 'Which season do you like best?', 'Thiên nhiên & Thời tiết', 'A1'),
('en', 'temperature', 'ˈtemprətʃər', 'nhiệt độ', 'The temperature is 35 degrees today.', 'Thiên nhiên & Thời tiết', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 8. Cơ thể & Sức khỏe
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'head', 'hed', 'cái đầu', 'My head hurts a little.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'hair', 'heər', 'tóc', 'She has long black hair.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'face', 'feɪs', 'khuôn mặt', 'Wash your face every morning.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'eye', 'aɪ', 'con mắt', 'Her eyes are brown.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'ear', 'ɪər', 'cái tai', 'Rabbits have long ears.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'nose', 'noʊz', 'cái mũi', 'My nose is blocked today.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'mouth', 'maʊθ', 'cái miệng', 'Open your mouth and say ah.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'tooth', 'tuːθ', 'cái răng', 'Brush your teeth twice a day.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'hand', 'hænd', 'bàn tay', 'Wash your hands before eating.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'arm', 'ɑːrm', 'cánh tay', 'He broke his arm playing football.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'leg', 'leɡ', 'cái chân', 'My legs are tired after running.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'foot', 'fʊt', 'bàn chân', 'I go to school on foot.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'heart', 'hɑːrt', 'trái tim', 'Running is good for your heart.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'stomach', 'ˈstʌmək', 'bụng, dạ dày', 'My stomach hurts after lunch.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'healthy', 'ˈhelθi', 'khỏe mạnh', 'Eat well to stay healthy.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'sick', 'sɪk', 'ốm, bệnh', 'He is sick and stays home.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'tired', 'ˈtaɪərd', 'mệt mỏi', 'I feel tired after work.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'headache', 'ˈhedeɪk', 'đau đầu', 'She has a bad headache.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'fever', 'ˈfiːvər', 'sốt', 'The baby has a high fever.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'medicine', 'ˈmedsn', 'thuốc', 'Take this medicine after meals.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'hospital', 'ˈhɒspɪtl', 'bệnh viện', 'The hospital is open all night.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'exercise', 'ˈeksərsaɪz', 'tập thể dục', 'Exercise for thirty minutes a day.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'sleep', 'sliːp', 'ngủ', 'Children need ten hours of sleep.', 'Cơ thể & Sức khỏe', 'A1'),
('en', 'rest', 'rest', 'nghỉ ngơi', 'Take a rest after lunch.', 'Cơ thể & Sức khỏe', 'A2'),
('en', 'strong', 'strɒŋ', 'khỏe, mạnh mẽ', 'Elephants are very strong.', 'Cơ thể & Sức khỏe', 'A1')
ON CONFLICT (language_id, term) DO NOTHING;

-- 9. Quần áo & Mua sắm
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'clothes', 'kloʊðz', 'quần áo', 'She buys new clothes every month.', 'Quần áo & Mua sắm', 'A1'),
('en', 'shirt', 'ʃɜːrt', 'áo sơ mi', 'He wears a white shirt to work.', 'Quần áo & Mua sắm', 'A1'),
('en', 't-shirt', 'ˈtiː ʃɜːrt', 'áo phông', 'This t-shirt is too small.', 'Quần áo & Mua sắm', 'A1'),
('en', 'dress', 'dres', 'váy liền', 'Her red dress is beautiful.', 'Quần áo & Mua sắm', 'A1'),
('en', 'trousers', 'ˈtraʊzərz', 'quần dài', 'These trousers are too long.', 'Quần áo & Mua sắm', 'A1'),
('en', 'jeans', 'dʒiːnz', 'quần bò', 'Jeans are comfortable to wear.', 'Quần áo & Mua sắm', 'A1'),
('en', 'skirt', 'skɜːrt', 'chân váy', 'The skirt matches her shoes.', 'Quần áo & Mua sắm', 'A1'),
('en', 'jacket', 'ˈdʒækɪt', 'áo khoác', 'Take a jacket, it is windy.', 'Quần áo & Mua sắm', 'A1'),
('en', 'coat', 'koʊt', 'áo khoác dày', 'Wear a warm coat in winter.', 'Quần áo & Mua sắm', 'A1'),
('en', 'shoes', 'ʃuːz', 'giày', 'My new shoes are white.', 'Quần áo & Mua sắm', 'A1'),
('en', 'sandals', 'ˈsændlz', 'dép xăng đan', 'Sandals are great for summer.', 'Quần áo & Mua sắm', 'A2'),
('en', 'hat', 'hæt', 'cái mũ', 'Wear a hat in the sun.', 'Quần áo & Mua sắm', 'A1'),
('en', 'socks', 'sɒks', 'tất, vớ', 'I need new socks for winter.', 'Quần áo & Mua sắm', 'A1'),
('en', 'bag', 'bæɡ', 'cái túi', 'Her bag is full of books.', 'Quần áo & Mua sắm', 'A1'),
('en', 'wallet', 'ˈwɒlɪt', 'ví tiền', 'I left my wallet at home.', 'Quần áo & Mua sắm', 'A2'),
('en', 'glasses', 'ˈɡlɑːsɪz', 'kính mắt', 'He wears glasses for reading.', 'Quần áo & Mua sắm', 'A2'),
('en', 'watch', 'wɒtʃ', 'đồng hồ đeo tay', 'This watch was a birthday gift.', 'Quần áo & Mua sắm', 'A1'),
('en', 'shop', 'ʃɒp', 'cửa hàng', 'The shop opens at nine.', 'Quần áo & Mua sắm', 'A1'),
('en', 'market', 'ˈmɑːrkɪt', 'chợ', 'Mom goes to the market early.', 'Quần áo & Mua sắm', 'A1'),
('en', 'supermarket', 'ˈsuːpərmɑːrkɪt', 'siêu thị', 'We buy food at the supermarket.', 'Quần áo & Mua sắm', 'A1'),
('en', 'price', 'praɪs', 'giá cả', 'What is the price of this shirt?', 'Quần áo & Mua sắm', 'A1'),
('en', 'money', 'ˈmʌni', 'tiền', 'Save money for your trip.', 'Quần áo & Mua sắm', 'A1'),
('en', 'cheap', 'tʃiːp', 'rẻ', 'Street food is cheap and tasty.', 'Quần áo & Mua sắm', 'A1'),
('en', 'expensive', 'ɪkˈspensɪv', 'đắt', 'That phone is too expensive.', 'Quần áo & Mua sắm', 'A1'),
('en', 'sale', 'seɪl', 'giảm giá', 'The shop has a big sale today.', 'Quần áo & Mua sắm', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 10. Thể thao & Giải trí
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'football', 'ˈfʊtbɔːl', 'bóng đá', 'Vietnamese people love football.', 'Thể thao & Giải trí', 'A1'),
('en', 'badminton', 'ˈbædmɪntən', 'cầu lông', 'We play badminton after school.', 'Thể thao & Giải trí', 'A2'),
('en', 'swimming', 'ˈswɪmɪŋ', 'bơi lội', 'Swimming is fun in summer.', 'Thể thao & Giải trí', 'A1'),
('en', 'running', 'ˈrʌnɪŋ', 'chạy bộ', 'Running keeps me fit.', 'Thể thao & Giải trí', 'A1'),
('en', 'game', 'ɡeɪm', 'trò chơi', 'Let''s play a fun game.', 'Thể thao & Giải trí', 'A1'),
('en', 'music', 'ˈmjuːzɪk', 'âm nhạc', 'I listen to music every night.', 'Thể thao & Giải trí', 'A1'),
('en', 'song', 'sɒŋ', 'bài hát', 'This song is very popular.', 'Thể thao & Giải trí', 'A1'),
('en', 'movie', 'ˈmuːvi', 'bộ phim', 'We watched a funny movie.', 'Thể thao & Giải trí', 'A1'),
('en', 'dance', 'dɑːns', 'nhảy múa', 'She dances very well.', 'Thể thao & Giải trí', 'A1'),
('en', 'hobby', 'ˈhɒbi', 'sở thích', 'Reading is my favorite hobby.', 'Thể thao & Giải trí', 'A2'),
('en', 'party', 'ˈpɑːrti', 'bữa tiệc', 'The party starts at eight.', 'Thể thao & Giải trí', 'A1'),
('en', 'picnic', 'ˈpɪknɪk', 'dã ngoại', 'We had a picnic by the lake.', 'Thể thao & Giải trí', 'A2'),
('en', 'camera', 'ˈkæmərə', 'máy ảnh', 'She takes photos with her camera.', 'Thể thao & Giải trí', 'A1'),
('en', 'photo', 'ˈfoʊtoʊ', 'bức ảnh', 'This photo was taken in Dalat.', 'Thể thao & Giải trí', 'A1'),
('en', 'book club', 'bʊk klʌb', 'câu lạc bộ sách', 'She joined a book club last year.', 'Thể thao & Giải trí', 'A2'),
('en', 'guitar', 'ɡɪˈtɑːr', 'đàn ghi ta', 'He plays the guitar at parties.', 'Thể thao & Giải trí', 'A1'),
('en', 'piano', 'piˈænoʊ', 'đàn piano', 'My daughter learns the piano.', 'Thể thao & Giải trí', 'A1'),
('en', 'team sport', 'tiːm spɔːrt', 'môn thể thao đồng đội', 'Football is a team sport.', 'Thể thao & Giải trí', 'A2'),
('en', 'winner', 'ˈwɪnər', 'người chiến thắng', 'The winner gets a gold medal.', 'Thể thao & Giải trí', 'A2'),
('en', 'ball', 'bɔːl', 'quả bóng', 'Throw the ball to me.', 'Thể thao & Giải trí', 'A1'),
('en', 'swimming pool', 'ˈswɪmɪŋ puːl', 'bể bơi', 'The hotel has a swimming pool.', 'Thể thao & Giải trí', 'A1'),
('en', 'gym', 'dʒɪm', 'phòng tập', 'He goes to the gym twice a week.', 'Thể thao & Giải trí', 'A2'),
('en', 'ticket office', 'ˈtɪkɪt ˌɒfɪs', 'quầy vé', 'Buy tickets at the ticket office.', 'Thể thao & Giải trí', 'A2'),
('en', 'television show', 'ˈtelɪvɪʒn ʃoʊ', 'chương trình ti vi', 'This television show is funny.', 'Thể thao & Giải trí', 'A2'),
('en', 'holiday', 'ˈhɒlədeɪ', 'kỳ nghỉ, ngày lễ', 'We go to the beach on holiday.', 'Thể thao & Giải trí', 'A1')
ON CONFLICT (language_id, term) DO NOTHING;

-- 11. Động từ thường gặp
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'go', 'ɡoʊ', 'đi', 'I go to work by bus.', 'Động từ thường gặp', 'A1'),
('en', 'come', 'kʌm', 'đến', 'Come here, please.', 'Động từ thường gặp', 'A1'),
('en', 'eat', 'iːt', 'ăn', 'We eat lunch at noon.', 'Động từ thường gặp', 'A1'),
('en', 'drink', 'drɪŋk', 'uống', 'Drink some water first.', 'Động từ thường gặp', 'A1'),
('en', 'see', 'siː', 'nhìn thấy', 'I see a bird on the tree.', 'Động từ thường gặp', 'A1'),
('en', 'hear', 'hɪər', 'nghe thấy', 'Can you hear the music?', 'Động từ thường gặp', 'A1'),
('en', 'speak', 'spiːk', 'nói', 'She speaks three languages.', 'Động từ thường gặp', 'A1'),
('en', 'read', 'riːd', 'đọc', 'He reads books before bed.', 'Động từ thường gặp', 'A1'),
('en', 'write', 'raɪt', 'viết', 'Write your name here.', 'Động từ thường gặp', 'A1'),
('en', 'run', 'rʌn', 'chạy', 'They run in the park.', 'Động từ thường gặp', 'A1'),
('en', 'walk', 'wɔːk', 'đi bộ', 'We walk to school together.', 'Động từ thường gặp', 'A1'),
('en', 'open', 'ˈoʊpən', 'mở', 'Open your books to page ten.', 'Động từ thường gặp', 'A1'),
('en', 'close', 'kloʊz', 'đóng', 'Close the window, please.', 'Động từ thường gặp', 'A1'),
('en', 'buy', 'baɪ', 'mua', 'I want to buy a new phone.', 'Động từ thường gặp', 'A1'),
('en', 'sell', 'sel', 'bán', 'They sell fruit at the market.', 'Động từ thường gặp', 'A1'),
('en', 'give', 'ɡɪv', 'đưa, tặng', 'Give me the pen, please.', 'Động từ thường gặp', 'A1'),
('en', 'take', 'teɪk', 'lấy, cầm', 'Take an umbrella with you.', 'Động từ thường gặp', 'A1'),
('en', 'make', 'meɪk', 'làm, tạo ra', 'Mom makes breakfast every day.', 'Động từ thường gặp', 'A1'),
('en', 'help', 'help', 'giúp đỡ', 'Can you help me with this?', 'Động từ thường gặp', 'A1'),
('en', 'play', 'pleɪ', 'chơi', 'The kids play in the garden.', 'Động từ thường gặp', 'A1'),
('en', 'cook', 'kʊk', 'nấu ăn', 'My father cooks on weekends.', 'Động từ thường gặp', 'A1'),
('en', 'listen', 'ˈlɪsn', 'lắng nghe', 'Listen to the teacher carefully.', 'Động từ thường gặp', 'A1'),
('en', 'wait', 'weɪt', 'chờ đợi', 'Wait for me at the gate.', 'Động từ thường gặp', 'A1'),
('en', 'remember', 'rɪˈmembər', 'nhớ', 'Remember to lock the door.', 'Động từ thường gặp', 'A2'),
('en', 'forget', 'fərˈɡet', 'quên', 'Do not forget your homework.', 'Động từ thường gặp', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;

-- 12. Tính từ thường gặp
INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level) VALUES
('en', 'big', 'bɪɡ', 'to, lớn', 'They live in a big city.', 'Tính từ thường gặp', 'A1'),
('en', 'small', 'smɔːl', 'nhỏ', 'The kitten is very small.', 'Tính từ thường gặp', 'A1'),
('en', 'good', 'ɡʊd', 'tốt', 'She is a good student.', 'Tính từ thường gặp', 'A1'),
('en', 'bad', 'bæd', 'xấu, tệ', 'Smoking is bad for health.', 'Tính từ thường gặp', 'A1'),
('en', 'new', 'njuː', 'mới', 'I like your new haircut.', 'Tính từ thường gặp', 'A1'),
('en', 'old', 'oʊld', 'cũ, già', 'This is an old temple.', 'Tính từ thường gặp', 'A1'),
('en', 'happy', 'ˈhæpi', 'vui vẻ', 'The children look very happy.', 'Tính từ thường gặp', 'A1'),
('en', 'sad', 'sæd', 'buồn', 'He feels sad about the news.', 'Tính từ thường gặp', 'A1'),
('en', 'beautiful', 'ˈbjuːtɪfl', 'đẹp', 'Ha Long Bay is beautiful.', 'Tính từ thường gặp', 'A1'),
('en', 'ugly', 'ˈʌɡli', 'xấu xí', 'The witch in the story is ugly.', 'Tính từ thường gặp', 'A2'),
('en', 'fast', 'fɑːst', 'nhanh', 'The train is very fast.', 'Tính từ thường gặp', 'A1'),
('en', 'slow', 'sloʊ', 'chậm', 'Turtles are slow animals.', 'Tính từ thường gặp', 'A1'),
('en', 'easy', 'ˈiːzi', 'dễ', 'This exercise is easy.', 'Tính từ thường gặp', 'A1'),
('en', 'difficult', 'ˈdɪfɪkəlt', 'khó', 'The last question is difficult.', 'Tính từ thường gặp', 'A1'),
('en', 'long', 'lɒŋ', 'dài', 'The Mekong is a long river.', 'Tính từ thường gặp', 'A1'),
('en', 'short', 'ʃɔːrt', 'ngắn, thấp', 'He wrote a short letter.', 'Tính từ thường gặp', 'A1'),
('en', 'tall', 'tɔːl', 'cao', 'My brother is tall and thin.', 'Tính từ thường gặp', 'A1'),
('en', 'young', 'jʌŋ', 'trẻ', 'She is too young to drive.', 'Tính từ thường gặp', 'A1'),
('en', 'clean', 'kliːn', 'sạch sẽ', 'Keep your room clean.', 'Tính từ thường gặp', 'A1'),
('en', 'dirty', 'ˈdɜːrti', 'bẩn', 'Wash the dirty dishes.', 'Tính từ thường gặp', 'A1'),
('en', 'funny', 'ˈfʌni', 'hài hước', 'He tells funny stories.', 'Tính từ thường gặp', 'A1'),
('en', 'kind', 'kaɪnd', 'tử tế', 'Be kind to animals.', 'Tính từ thường gặp', 'A2'),
('en', 'quiet', 'ˈkwaɪət', 'yên tĩnh', 'The library is a quiet place.', 'Tính từ thường gặp', 'A2'),
('en', 'noisy', 'ˈnɔɪzi', 'ồn ào', 'The street market is noisy.', 'Tính từ thường gặp', 'A2'),
('en', 'important', 'ɪmˈpɔːrtnt', 'quan trọng', 'Sleep is important for your health.', 'Tính từ thường gặp', 'A2')
ON CONFLICT (language_id, term) DO NOTHING;
