// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: blog.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const adoptBlogImages = `-- name: AdoptBlogImages :exec
UPDATE blog_post_images SET post_id = $1
WHERE id = ANY($2::uuid[]) AND author_id = $3 AND post_id IS NULL
`

type AdoptBlogImagesParams struct {
	PostID   pgtype.UUID   `json:"post_id"`
	Ids      []pgtype.UUID `json:"ids"`
	AuthorID pgtype.UUID   `json:"author_id"`
}

// Gắn các ảnh (do đúng author upload, CHƯA gắn bài nào) vào bài vừa lưu —
// ảnh KHÔNG thuộc danh sách này (đã bị xoá khỏi content khi sửa bài) vẫn
// giữ nguyên post_id cũ, chấp nhận trở thành rác mồ côi trên R2 (không có
// cơ chế dọn tự động ở bản này).
func (q *Queries) AdoptBlogImages(ctx context.Context, arg AdoptBlogImagesParams) error {
	_, err := q.db.Exec(ctx, adoptBlogImages, arg.PostID, arg.Ids, arg.AuthorID)
	return err
}

const countBlogCommentDislikes = `-- name: CountBlogCommentDislikes :one
SELECT COUNT(*)::int FROM blog_comment_dislikes WHERE comment_id = $1
`

func (q *Queries) CountBlogCommentDislikes(ctx context.Context, commentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlogCommentDislikes, commentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBlogCommentLikes = `-- name: CountBlogCommentLikes :one
SELECT COUNT(*)::int FROM blog_comment_likes WHERE comment_id = $1
`

func (q *Queries) CountBlogCommentLikes(ctx context.Context, commentID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlogCommentLikes, commentID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBlogPostDislikes = `-- name: CountBlogPostDislikes :one
SELECT COUNT(*)::int FROM blog_post_dislikes WHERE post_id = $1
`

func (q *Queries) CountBlogPostDislikes(ctx context.Context, postID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlogPostDislikes, postID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBlogPostLikes = `-- name: CountBlogPostLikes :one
SELECT COUNT(*)::int FROM blog_post_likes WHERE post_id = $1
`

func (q *Queries) CountBlogPostLikes(ctx context.Context, postID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlogPostLikes, postID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBlogPostMarkers = `-- name: CountBlogPostMarkers :one
SELECT COUNT(*)::int FROM blog_post_markers WHERE post_id = $1
`

func (q *Queries) CountBlogPostMarkers(ctx context.Context, postID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlogPostMarkers, postID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countBlogPostStars = `-- name: CountBlogPostStars :one
SELECT COUNT(*)::int FROM blog_post_stars WHERE post_id = $1
`

func (q *Queries) CountBlogPostStars(ctx context.Context, postID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countBlogPostStars, postID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const createBlogComment = `-- name: CreateBlogComment :one

INSERT INTO blog_comments (post_id, author_id, parent_comment_id, content)
VALUES ($1, $2, $3, $4)
RETURNING id, post_id, author_id, parent_comment_id, content, is_hidden, created_at, updated_at
`

type CreateBlogCommentParams struct {
	PostID          pgtype.UUID `json:"post_id"`
	AuthorID        pgtype.UUID `json:"author_id"`
	ParentCommentID pgtype.UUID `json:"parent_comment_id"`
	Content         string      `json:"content"`
}

// ===== Comment (lồng nhau) =====
func (q *Queries) CreateBlogComment(ctx context.Context, arg CreateBlogCommentParams) (BlogComment, error) {
	row := q.db.QueryRow(ctx, createBlogComment,
		arg.PostID,
		arg.AuthorID,
		arg.ParentCommentID,
		arg.Content,
	)
	var i BlogComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBlogImage = `-- name: CreateBlogImage :one

INSERT INTO blog_post_images (author_id, image_key)
VALUES ($1, $2)
RETURNING id, post_id, author_id, image_key
`

type CreateBlogImageParams struct {
	AuthorID pgtype.UUID `json:"author_id"`
	ImageKey string      `json:"image_key"`
}

// ===== Ảnh chèn trong content (upload qua R2, phục vụ qua /blog/images/:id) =====
// post_id NULL lúc upload (có thể đang soạn bài MỚI, chưa có id) — Create/Update
// bài sẽ "nhận" (AdoptBlogImages) các ảnh được tham chiếu trong content.
func (q *Queries) CreateBlogImage(ctx context.Context, arg CreateBlogImageParams) (BlogPostImage, error) {
	row := q.db.QueryRow(ctx, createBlogImage, arg.AuthorID, arg.ImageKey)
	var i BlogPostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ImageKey,
	)
	return i, err
}

const createBlogPost = `-- name: CreateBlogPost :one

INSERT INTO blog_posts (author_id, language_id, title, content, tags)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, author_id, language_id, title, content, tags, view_count, is_hidden, created_at, updated_at
`

type CreateBlogPostParams struct {
	AuthorID   pgtype.UUID `json:"author_id"`
	LanguageID pgtype.Text `json:"language_id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	Tags       []string    `json:"tags"`
}

// ===== Posts =====
func (q *Queries) CreateBlogPost(ctx context.Context, arg CreateBlogPostParams) (BlogPost, error) {
	row := q.db.QueryRow(ctx, createBlogPost,
		arg.AuthorID,
		arg.LanguageID,
		arg.Title,
		arg.Content,
		arg.Tags,
	)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.LanguageID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.ViewCount,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteBlogComment = `-- name: DeleteBlogComment :exec
DELETE FROM blog_comments WHERE id = $1
`

func (q *Queries) DeleteBlogComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlogComment, id)
	return err
}

const deleteBlogPost = `-- name: DeleteBlogPost :exec
DELETE FROM blog_posts WHERE id = $1
`

func (q *Queries) DeleteBlogPost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlogPost, id)
	return err
}

const dislikeBlogComment = `-- name: DislikeBlogComment :exec
INSERT INTO blog_comment_dislikes (user_id, comment_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type DislikeBlogCommentParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	CommentID pgtype.UUID `json:"comment_id"`
}

func (q *Queries) DislikeBlogComment(ctx context.Context, arg DislikeBlogCommentParams) error {
	_, err := q.db.Exec(ctx, dislikeBlogComment, arg.UserID, arg.CommentID)
	return err
}

const dislikeBlogPost = `-- name: DislikeBlogPost :exec
INSERT INTO blog_post_dislikes (user_id, post_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type DislikeBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) DislikeBlogPost(ctx context.Context, arg DislikeBlogPostParams) error {
	_, err := q.db.Exec(ctx, dislikeBlogPost, arg.UserID, arg.PostID)
	return err
}

const getBlogCommentByID = `-- name: GetBlogCommentByID :one
SELECT id, post_id, author_id, parent_comment_id, content, is_hidden, created_at, updated_at FROM blog_comments WHERE id = $1
`

func (q *Queries) GetBlogCommentByID(ctx context.Context, id pgtype.UUID) (BlogComment, error) {
	row := q.db.QueryRow(ctx, getBlogCommentByID, id)
	var i BlogComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogImageByID = `-- name: GetBlogImageByID :one
SELECT id, post_id, author_id, image_key FROM blog_post_images WHERE id = $1
`

// Dùng để phục vụ ảnh qua /blog/images/:id (resolve sang presigned URL) — public, không cần biết ai hỏi.
func (q *Queries) GetBlogImageByID(ctx context.Context, id pgtype.UUID) (BlogPostImage, error) {
	row := q.db.QueryRow(ctx, getBlogImageByID, id)
	var i BlogPostImage
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ImageKey,
	)
	return i, err
}

const getBlogPostByID = `-- name: GetBlogPostByID :one
SELECT id, author_id, language_id, title, content, tags, view_count, is_hidden, created_at, updated_at FROM blog_posts WHERE id = $1
`

// Bản gọn, dùng cho ownership check trước khi Update/Delete — không join gì thêm.
func (q *Queries) GetBlogPostByID(ctx context.Context, id pgtype.UUID) (BlogPost, error) {
	row := q.db.QueryRow(ctx, getBlogPostByID, id)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.LanguageID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.ViewCount,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBlogPostDetailByID = `-- name: GetBlogPostDetailByID :one
SELECT
    p.id, p.author_id, p.language_id, p.title, p.content, p.tags, p.view_count, p.is_hidden, p.created_at, p.updated_at,
    u.username,
    u.full_name,
    u.avatar_url,
    (SELECT COUNT(*) FROM blog_comments c WHERE c.post_id = p.id AND c.is_hidden = false)::int AS comment_count,
    (SELECT COUNT(*) FROM blog_post_stars s WHERE s.post_id = p.id)::int AS star_count,
    (SELECT COUNT(*) FROM blog_post_markers m WHERE m.post_id = p.id)::int AS marker_count,
    (SELECT COUNT(*) FROM blog_post_likes l WHERE l.post_id = p.id)::int AS like_count,
    (SELECT COUNT(*) FROM blog_post_dislikes d WHERE d.post_id = p.id)::int AS dislike_count,
    EXISTS (SELECT 1 FROM blog_post_stars s WHERE s.post_id = p.id AND s.user_id = $1) AS starred,
    EXISTS (SELECT 1 FROM blog_post_markers m WHERE m.post_id = p.id AND m.user_id = $1) AS marked,
    EXISTS (SELECT 1 FROM blog_post_likes l WHERE l.post_id = p.id AND l.user_id = $1) AS liked,
    EXISTS (SELECT 1 FROM blog_post_dislikes d WHERE d.post_id = p.id AND d.user_id = $1) AS disliked
FROM blog_posts p
JOIN users u ON u.id = p.author_id
WHERE p.id = $2
`

type GetBlogPostDetailByIDParams struct {
	UserID pgtype.UUID `json:"user_id"`
	ID     pgtype.UUID `json:"id"`
}

type GetBlogPostDetailByIDRow struct {
	ID           pgtype.UUID        `json:"id"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	LanguageID   pgtype.Text        `json:"language_id"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Tags         []string           `json:"tags"`
	ViewCount    int32              `json:"view_count"`
	IsHidden     bool               `json:"is_hidden"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CommentCount int32              `json:"comment_count"`
	StarCount    int32              `json:"star_count"`
	MarkerCount  int32              `json:"marker_count"`
	LikeCount    int32              `json:"like_count"`
	DislikeCount int32              `json:"dislike_count"`
	Starred      bool               `json:"starred"`
	Marked       bool               `json:"marked"`
	Liked        bool               `json:"liked"`
	Disliked     bool               `json:"disliked"`
}

// Bản đầy đủ cho trang chi tiết: thông tin tác giả + count/flag theo user hiện tại.
func (q *Queries) GetBlogPostDetailByID(ctx context.Context, arg GetBlogPostDetailByIDParams) (GetBlogPostDetailByIDRow, error) {
	row := q.db.QueryRow(ctx, getBlogPostDetailByID, arg.UserID, arg.ID)
	var i GetBlogPostDetailByIDRow
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.LanguageID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.ViewCount,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Username,
		&i.FullName,
		&i.AvatarUrl,
		&i.CommentCount,
		&i.StarCount,
		&i.MarkerCount,
		&i.LikeCount,
		&i.DislikeCount,
		&i.Starred,
		&i.Marked,
		&i.Liked,
		&i.Disliked,
	)
	return i, err
}

const hideBlogComment = `-- name: HideBlogComment :exec
UPDATE blog_comments SET is_hidden = true WHERE id = $1
`

func (q *Queries) HideBlogComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hideBlogComment, id)
	return err
}

const hideBlogPost = `-- name: HideBlogPost :exec
UPDATE blog_posts SET is_hidden = true WHERE id = $1
`

func (q *Queries) HideBlogPost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hideBlogPost, id)
	return err
}

const incrementBlogPostViewCount = `-- name: IncrementBlogPostViewCount :exec
UPDATE blog_posts SET view_count = view_count + 1 WHERE id = $1
`

func (q *Queries) IncrementBlogPostViewCount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, incrementBlogPostViewCount, id)
	return err
}

const likeBlogComment = `-- name: LikeBlogComment :exec

INSERT INTO blog_comment_likes (user_id, comment_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LikeBlogCommentParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	CommentID pgtype.UUID `json:"comment_id"`
}

// ===== Like/dislike cho comment (độc lập với like/dislike bài viết) =====
func (q *Queries) LikeBlogComment(ctx context.Context, arg LikeBlogCommentParams) error {
	_, err := q.db.Exec(ctx, likeBlogComment, arg.UserID, arg.CommentID)
	return err
}

const likeBlogPost = `-- name: LikeBlogPost :exec
INSERT INTO blog_post_likes (user_id, post_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LikeBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) LikeBlogPost(ctx context.Context, arg LikeBlogPostParams) error {
	_, err := q.db.Exec(ctx, likeBlogPost, arg.UserID, arg.PostID)
	return err
}

const listBlogCommentsByPost = `-- name: ListBlogCommentsByPost :many
SELECT
    c.id, c.post_id, c.author_id, c.parent_comment_id, c.content, c.is_hidden, c.created_at, c.updated_at,
    u.username,
    u.full_name,
    u.avatar_url,
    (SELECT COUNT(*) FROM blog_comment_likes l WHERE l.comment_id = c.id)::int AS like_count,
    (SELECT COUNT(*) FROM blog_comment_dislikes d WHERE d.comment_id = c.id)::int AS dislike_count,
    EXISTS (SELECT 1 FROM blog_comment_likes l WHERE l.comment_id = c.id AND l.user_id = $1) AS liked,
    EXISTS (SELECT 1 FROM blog_comment_dislikes d WHERE d.comment_id = c.id AND d.user_id = $1) AS disliked
FROM blog_comments c
JOIN users u ON u.id = c.author_id
WHERE c.post_id = $2
ORDER BY c.created_at
`

type ListBlogCommentsByPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

type ListBlogCommentsByPostRow struct {
	ID              pgtype.UUID        `json:"id"`
	PostID          pgtype.UUID        `json:"post_id"`
	AuthorID        pgtype.UUID        `json:"author_id"`
	ParentCommentID pgtype.UUID        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	IsHidden        bool               `json:"is_hidden"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Username        string             `json:"username"`
	FullName        pgtype.Text        `json:"full_name"`
	AvatarUrl       pgtype.Text        `json:"avatar_url"`
	LikeCount       int32              `json:"like_count"`
	DislikeCount    int32              `json:"dislike_count"`
	Liked           bool               `json:"liked"`
	Disliked        bool               `json:"disliked"`
}

// Flat, sắp theo thời gian — service dựng cây parent/child ở Go từ parent_comment_id.
// Kèm like/dislike count + flag theo user hiện tại (giống cách post làm).
func (q *Queries) ListBlogCommentsByPost(ctx context.Context, arg ListBlogCommentsByPostParams) ([]ListBlogCommentsByPostRow, error) {
	rows, err := q.db.Query(ctx, listBlogCommentsByPost, arg.UserID, arg.PostID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogCommentsByPostRow
	for rows.Next() {
		var i ListBlogCommentsByPostRow
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ParentCommentID,
			&i.Content,
			&i.IsHidden,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Liked,
			&i.Disliked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostImages = `-- name: ListBlogPostImages :many
SELECT id, post_id, author_id, image_key FROM blog_post_images WHERE post_id = $1
`

// Dùng khi xoá bài (lấy key để xoá object trên R2 trước khi xoá hàng DB).
func (q *Queries) ListBlogPostImages(ctx context.Context, postID pgtype.UUID) ([]BlogPostImage, error) {
	rows, err := q.db.Query(ctx, listBlogPostImages, postID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BlogPostImage
	for rows.Next() {
		var i BlogPostImage
		if err := rows.Scan(
			&i.ID,
			&i.PostID,
			&i.AuthorID,
			&i.ImageKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostsAdminPaged = `-- name: ListBlogPostsAdminPaged :many
SELECT
    p.id, p.author_id, p.language_id, p.title, p.content, p.tags, p.view_count, p.is_hidden, p.created_at, p.updated_at,
    u.username,
    u.full_name,
    u.avatar_url,
    (SELECT COUNT(*) FROM blog_comments c WHERE c.post_id = p.id)::int AS comment_count,
    COUNT(*) OVER() AS total_count
FROM blog_posts p
JOIN users u ON u.id = p.author_id
WHERE ($1::bool = false OR p.is_hidden = true)
ORDER BY p.created_at DESC
LIMIT $3 OFFSET $2
`

type ListBlogPostsAdminPagedParams struct {
	HiddenOnly bool  `json:"hidden_only"`
	Offset     int32 `json:"offset"`
	Limit      int32 `json:"limit"`
}

type ListBlogPostsAdminPagedRow struct {
	ID           pgtype.UUID        `json:"id"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	LanguageID   pgtype.Text        `json:"language_id"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Tags         []string           `json:"tags"`
	ViewCount    int32              `json:"view_count"`
	IsHidden     bool               `json:"is_hidden"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CommentCount int32              `json:"comment_count"`
	TotalCount   int64              `json:"total_count"`
}

// Trang quản trị: thấy mọi bài (ẩn hoặc không), filter "chỉ bài đã ẩn" qua hidden_only.
func (q *Queries) ListBlogPostsAdminPaged(ctx context.Context, arg ListBlogPostsAdminPagedParams) ([]ListBlogPostsAdminPagedRow, error) {
	rows, err := q.db.Query(ctx, listBlogPostsAdminPaged, arg.HiddenOnly, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogPostsAdminPagedRow
	for rows.Next() {
		var i ListBlogPostsAdminPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.LanguageID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.ViewCount,
			&i.IsHidden,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.CommentCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBlogPostsPaged = `-- name: ListBlogPostsPaged :many
SELECT
    p.id, p.author_id, p.language_id, p.title, p.content, p.tags, p.view_count, p.is_hidden, p.created_at, p.updated_at,
    u.username,
    u.full_name,
    u.avatar_url,
    (SELECT COUNT(*) FROM blog_comments c WHERE c.post_id = p.id AND c.is_hidden = false)::int AS comment_count,
    (SELECT COUNT(*) FROM blog_post_stars s WHERE s.post_id = p.id)::int AS star_count,
    (SELECT COUNT(*) FROM blog_post_markers m WHERE m.post_id = p.id)::int AS marker_count,
    (SELECT COUNT(*) FROM blog_post_likes l WHERE l.post_id = p.id)::int AS like_count,
    (SELECT COUNT(*) FROM blog_post_dislikes d WHERE d.post_id = p.id)::int AS dislike_count,
    EXISTS (SELECT 1 FROM blog_post_stars s WHERE s.post_id = p.id AND s.user_id = $1) AS starred,
    EXISTS (SELECT 1 FROM blog_post_markers m WHERE m.post_id = p.id AND m.user_id = $1) AS marked,
    EXISTS (SELECT 1 FROM blog_post_likes l WHERE l.post_id = p.id AND l.user_id = $1) AS liked,
    EXISTS (SELECT 1 FROM blog_post_dislikes d WHERE d.post_id = p.id AND d.user_id = $1) AS disliked,
    COUNT(*) OVER() AS total_count
FROM blog_posts p
JOIN users u ON u.id = p.author_id
WHERE (p.is_hidden = false OR p.author_id = $1)
  AND ($2::varchar IS NULL OR p.language_id = $2)
  AND ($3::text IS NULL OR $3::text = ANY(p.tags))
  AND ($4::uuid IS NULL OR p.author_id = $4)
ORDER BY p.created_at DESC
LIMIT $6 OFFSET $5
`

type ListBlogPostsPagedParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID pgtype.Text `json:"language_id"`
	Tag        pgtype.Text `json:"tag"`
	AuthorID   pgtype.UUID `json:"author_id"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type ListBlogPostsPagedRow struct {
	ID           pgtype.UUID        `json:"id"`
	AuthorID     pgtype.UUID        `json:"author_id"`
	LanguageID   pgtype.Text        `json:"language_id"`
	Title        string             `json:"title"`
	Content      string             `json:"content"`
	Tags         []string           `json:"tags"`
	ViewCount    int32              `json:"view_count"`
	IsHidden     bool               `json:"is_hidden"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	Username     string             `json:"username"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	CommentCount int32              `json:"comment_count"`
	StarCount    int32              `json:"star_count"`
	MarkerCount  int32              `json:"marker_count"`
	LikeCount    int32              `json:"like_count"`
	DislikeCount int32              `json:"dislike_count"`
	Starred      bool               `json:"starred"`
	Marked       bool               `json:"marked"`
	Liked        bool               `json:"liked"`
	Disliked     bool               `json:"disliked"`
	TotalCount   int64              `json:"total_count"`
}

// Learner-facing: ẩn bài is_hidden của người khác, nhưng tác giả vẫn thấy bài
// (đã bị ẩn) của chính mình kèm badge. Lọc theo ngôn ngữ/tag/tác giả (mine).
func (q *Queries) ListBlogPostsPaged(ctx context.Context, arg ListBlogPostsPagedParams) ([]ListBlogPostsPagedRow, error) {
	rows, err := q.db.Query(ctx, listBlogPostsPaged,
		arg.UserID,
		arg.LanguageID,
		arg.Tag,
		arg.AuthorID,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogPostsPagedRow
	for rows.Next() {
		var i ListBlogPostsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.AuthorID,
			&i.LanguageID,
			&i.Title,
			&i.Content,
			&i.Tags,
			&i.ViewCount,
			&i.IsHidden,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.CommentCount,
			&i.StarCount,
			&i.MarkerCount,
			&i.LikeCount,
			&i.DislikeCount,
			&i.Starred,
			&i.Marked,
			&i.Liked,
			&i.Disliked,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markBlogPost = `-- name: MarkBlogPost :exec
INSERT INTO blog_post_markers (user_id, post_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type MarkBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) MarkBlogPost(ctx context.Context, arg MarkBlogPostParams) error {
	_, err := q.db.Exec(ctx, markBlogPost, arg.UserID, arg.PostID)
	return err
}

const starBlogPost = `-- name: StarBlogPost :exec

INSERT INTO blog_post_stars (user_id, post_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type StarBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

// ===== 4 counter độc lập (bài viết) =====
func (q *Queries) StarBlogPost(ctx context.Context, arg StarBlogPostParams) error {
	_, err := q.db.Exec(ctx, starBlogPost, arg.UserID, arg.PostID)
	return err
}

const undislikeBlogComment = `-- name: UndislikeBlogComment :exec
DELETE FROM blog_comment_dislikes WHERE user_id = $1 AND comment_id = $2
`

type UndislikeBlogCommentParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	CommentID pgtype.UUID `json:"comment_id"`
}

func (q *Queries) UndislikeBlogComment(ctx context.Context, arg UndislikeBlogCommentParams) error {
	_, err := q.db.Exec(ctx, undislikeBlogComment, arg.UserID, arg.CommentID)
	return err
}

const undislikeBlogPost = `-- name: UndislikeBlogPost :exec
DELETE FROM blog_post_dislikes WHERE user_id = $1 AND post_id = $2
`

type UndislikeBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) UndislikeBlogPost(ctx context.Context, arg UndislikeBlogPostParams) error {
	_, err := q.db.Exec(ctx, undislikeBlogPost, arg.UserID, arg.PostID)
	return err
}

const unhideBlogComment = `-- name: UnhideBlogComment :exec
UPDATE blog_comments SET is_hidden = false WHERE id = $1
`

func (q *Queries) UnhideBlogComment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unhideBlogComment, id)
	return err
}

const unhideBlogPost = `-- name: UnhideBlogPost :exec
UPDATE blog_posts SET is_hidden = false WHERE id = $1
`

func (q *Queries) UnhideBlogPost(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, unhideBlogPost, id)
	return err
}

const unlikeBlogComment = `-- name: UnlikeBlogComment :exec
DELETE FROM blog_comment_likes WHERE user_id = $1 AND comment_id = $2
`

type UnlikeBlogCommentParams struct {
	UserID    pgtype.UUID `json:"user_id"`
	CommentID pgtype.UUID `json:"comment_id"`
}

func (q *Queries) UnlikeBlogComment(ctx context.Context, arg UnlikeBlogCommentParams) error {
	_, err := q.db.Exec(ctx, unlikeBlogComment, arg.UserID, arg.CommentID)
	return err
}

const unlikeBlogPost = `-- name: UnlikeBlogPost :exec
DELETE FROM blog_post_likes WHERE user_id = $1 AND post_id = $2
`

type UnlikeBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) UnlikeBlogPost(ctx context.Context, arg UnlikeBlogPostParams) error {
	_, err := q.db.Exec(ctx, unlikeBlogPost, arg.UserID, arg.PostID)
	return err
}

const unmarkBlogPost = `-- name: UnmarkBlogPost :exec
DELETE FROM blog_post_markers WHERE user_id = $1 AND post_id = $2
`

type UnmarkBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) UnmarkBlogPost(ctx context.Context, arg UnmarkBlogPostParams) error {
	_, err := q.db.Exec(ctx, unmarkBlogPost, arg.UserID, arg.PostID)
	return err
}

const unstarBlogPost = `-- name: UnstarBlogPost :exec
DELETE FROM blog_post_stars WHERE user_id = $1 AND post_id = $2
`

type UnstarBlogPostParams struct {
	UserID pgtype.UUID `json:"user_id"`
	PostID pgtype.UUID `json:"post_id"`
}

func (q *Queries) UnstarBlogPost(ctx context.Context, arg UnstarBlogPostParams) error {
	_, err := q.db.Exec(ctx, unstarBlogPost, arg.UserID, arg.PostID)
	return err
}

const updateBlogComment = `-- name: UpdateBlogComment :one
UPDATE blog_comments SET content = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, post_id, author_id, parent_comment_id, content, is_hidden, created_at, updated_at
`

type UpdateBlogCommentParams struct {
	ID      pgtype.UUID `json:"id"`
	Content string      `json:"content"`
}

func (q *Queries) UpdateBlogComment(ctx context.Context, arg UpdateBlogCommentParams) (BlogComment, error) {
	row := q.db.QueryRow(ctx, updateBlogComment, arg.ID, arg.Content)
	var i BlogComment
	err := row.Scan(
		&i.ID,
		&i.PostID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateBlogPost = `-- name: UpdateBlogPost :one
UPDATE blog_posts
SET title = $2, content = $3, tags = $4, language_id = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, author_id, language_id, title, content, tags, view_count, is_hidden, created_at, updated_at
`

type UpdateBlogPostParams struct {
	ID         pgtype.UUID `json:"id"`
	Title      string      `json:"title"`
	Content    string      `json:"content"`
	Tags       []string    `json:"tags"`
	LanguageID pgtype.Text `json:"language_id"`
}

func (q *Queries) UpdateBlogPost(ctx context.Context, arg UpdateBlogPostParams) (BlogPost, error) {
	row := q.db.QueryRow(ctx, updateBlogPost,
		arg.ID,
		arg.Title,
		arg.Content,
		arg.Tags,
		arg.LanguageID,
	)
	var i BlogPost
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.LanguageID,
		&i.Title,
		&i.Content,
		&i.Tags,
		&i.ViewCount,
		&i.IsHidden,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
