// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: challenge_game.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createGameRoom = `-- name: CreateGameRoom :one
INSERT INTO game_rooms (code, host_user_id, question_count, time_per_question_seconds, max_participants)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, code, host_user_id, status, question_count, time_per_question_seconds, max_participants, created_at, started_at, finished_at
`

type CreateGameRoomParams struct {
	Code                   string      `json:"code"`
	HostUserID             pgtype.UUID `json:"host_user_id"`
	QuestionCount          int32       `json:"question_count"`
	TimePerQuestionSeconds int32       `json:"time_per_question_seconds"`
	MaxParticipants        int32       `json:"max_participants"`
}

func (q *Queries) CreateGameRoom(ctx context.Context, arg CreateGameRoomParams) (GameRoom, error) {
	row := q.db.QueryRow(ctx, createGameRoom,
		arg.Code,
		arg.HostUserID,
		arg.QuestionCount,
		arg.TimePerQuestionSeconds,
		arg.MaxParticipants,
	)
	var i GameRoom
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.Status,
		&i.QuestionCount,
		&i.TimePerQuestionSeconds,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishGameRoom = `-- name: FinishGameRoom :one
UPDATE game_rooms
SET status = 'finished', finished_at = NOW()
WHERE id = $1 AND status = 'in_progress'
RETURNING id, code, host_user_id, status, question_count, time_per_question_seconds, max_participants, created_at, started_at, finished_at
`

func (q *Queries) FinishGameRoom(ctx context.Context, id pgtype.UUID) (GameRoom, error) {
	row := q.db.QueryRow(ctx, finishGameRoom, id)
	var i GameRoom
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.Status,
		&i.QuestionCount,
		&i.TimePerQuestionSeconds,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGameParticipantByUser = `-- name: GetGameParticipantByUser :one
SELECT id, room_id, user_id, score, joined_at FROM game_participants WHERE room_id = $1 AND user_id = $2
`

type GetGameParticipantByUserParams struct {
	RoomID pgtype.UUID `json:"room_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetGameParticipantByUser(ctx context.Context, arg GetGameParticipantByUserParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, getGameParticipantByUser, arg.RoomID, arg.UserID)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const getGameRoomByCode = `-- name: GetGameRoomByCode :one
SELECT id, code, host_user_id, status, question_count, time_per_question_seconds, max_participants, created_at, started_at, finished_at FROM game_rooms WHERE code = $1
`

func (q *Queries) GetGameRoomByCode(ctx context.Context, code string) (GameRoom, error) {
	row := q.db.QueryRow(ctx, getGameRoomByCode, code)
	var i GameRoom
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.Status,
		&i.QuestionCount,
		&i.TimePerQuestionSeconds,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getGameRoomByID = `-- name: GetGameRoomByID :one
SELECT id, code, host_user_id, status, question_count, time_per_question_seconds, max_participants, created_at, started_at, finished_at FROM game_rooms WHERE id = $1
`

func (q *Queries) GetGameRoomByID(ctx context.Context, id pgtype.UUID) (GameRoom, error) {
	row := q.db.QueryRow(ctx, getGameRoomByID, id)
	var i GameRoom
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.Status,
		&i.QuestionCount,
		&i.TimePerQuestionSeconds,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLeaderboard = `-- name: GetLeaderboard :many
SELECT p.id AS participant_id, p.user_id, u.username, u.full_name, u.avatar_url, p.score,
       RANK() OVER (ORDER BY p.score DESC, p.joined_at ASC) AS rank
FROM game_participants p
JOIN users u ON u.id = p.user_id
WHERE p.room_id = $1
ORDER BY p.score DESC, p.joined_at ASC
`

type GetLeaderboardRow struct {
	ParticipantID pgtype.UUID `json:"participant_id"`
	UserID        pgtype.UUID `json:"user_id"`
	Username      string      `json:"username"`
	FullName      pgtype.Text `json:"full_name"`
	AvatarUrl     pgtype.Text `json:"avatar_url"`
	Score         int32       `json:"score"`
	Rank          int64       `json:"rank"`
}

func (q *Queries) GetLeaderboard(ctx context.Context, roomID pgtype.UUID) ([]GetLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getLeaderboard, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLeaderboardRow
	for rows.Next() {
		var i GetLeaderboardRow
		if err := rows.Scan(
			&i.ParticipantID,
			&i.UserID,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
			&i.Score,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGameRoomQuestion = `-- name: InsertGameRoomQuestion :exec
INSERT INTO game_room_questions (room_id, question_id, order_index)
VALUES ($1, $2, $3)
`

type InsertGameRoomQuestionParams struct {
	RoomID     pgtype.UUID `json:"room_id"`
	QuestionID pgtype.UUID `json:"question_id"`
	OrderIndex int32       `json:"order_index"`
}

func (q *Queries) InsertGameRoomQuestion(ctx context.Context, arg InsertGameRoomQuestionParams) error {
	_, err := q.db.Exec(ctx, insertGameRoomQuestion, arg.RoomID, arg.QuestionID, arg.OrderIndex)
	return err
}

const joinGameRoom = `-- name: JoinGameRoom :one
INSERT INTO game_participants (room_id, user_id)
SELECT gr.id, $1
FROM game_rooms gr
WHERE gr.id = $2
  AND gr.status = 'waiting'
  AND (SELECT COUNT(*) FROM game_participants p WHERE p.room_id = gr.id) < gr.max_participants
ON CONFLICT (room_id, user_id) DO UPDATE SET room_id = EXCLUDED.room_id
RETURNING id, room_id, user_id, score, joined_at
`

type JoinGameRoomParams struct {
	UserID pgtype.UUID `json:"user_id"`
	RoomID pgtype.UUID `json:"room_id"`
}

// Atomic: kiểm tra phòng còn "waiting" + chưa đủ người trong CÙNG 1 statement với
// insert, để tránh race khi 2 người join đúng slot cuối cùng cùng lúc.
func (q *Queries) JoinGameRoom(ctx context.Context, arg JoinGameRoomParams) (GameParticipant, error) {
	row := q.db.QueryRow(ctx, joinGameRoom, arg.UserID, arg.RoomID)
	var i GameParticipant
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.UserID,
		&i.Score,
		&i.JoinedAt,
	)
	return i, err
}

const listGameParticipants = `-- name: ListGameParticipants :many
SELECT p.id, p.room_id, p.user_id, p.score, p.joined_at,
       u.username, u.full_name, u.avatar_url
FROM game_participants p
JOIN users u ON u.id = p.user_id
WHERE p.room_id = $1
ORDER BY p.joined_at
`

type ListGameParticipantsRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoomID    pgtype.UUID        `json:"room_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Score     int32              `json:"score"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
	Username  string             `json:"username"`
	FullName  pgtype.Text        `json:"full_name"`
	AvatarUrl pgtype.Text        `json:"avatar_url"`
}

func (q *Queries) ListGameParticipants(ctx context.Context, roomID pgtype.UUID) ([]ListGameParticipantsRow, error) {
	rows, err := q.db.Query(ctx, listGameParticipants, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameParticipantsRow
	for rows.Next() {
		var i ListGameParticipantsRow
		if err := rows.Scan(
			&i.ID,
			&i.RoomID,
			&i.UserID,
			&i.Score,
			&i.JoinedAt,
			&i.Username,
			&i.FullName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGameRoomQuestions = `-- name: ListGameRoomQuestions :many
SELECT grq.order_index, cq.id, cq.language_id, cq.question, cq.options, cq.correct_index,
       cq.explanation, cq.difficulty, cq.created_at
FROM game_room_questions grq
JOIN challenge_questions cq ON cq.id = grq.question_id
WHERE grq.room_id = $1
ORDER BY grq.order_index
`

type ListGameRoomQuestionsRow struct {
	OrderIndex   int32              `json:"order_index"`
	ID           pgtype.UUID        `json:"id"`
	LanguageID   pgtype.Text        `json:"language_id"`
	Question     string             `json:"question"`
	Options      []byte             `json:"options"`
	CorrectIndex int32              `json:"correct_index"`
	Explanation  pgtype.Text        `json:"explanation"`
	Difficulty   int32              `json:"difficulty"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListGameRoomQuestions(ctx context.Context, roomID pgtype.UUID) ([]ListGameRoomQuestionsRow, error) {
	rows, err := q.db.Query(ctx, listGameRoomQuestions, roomID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGameRoomQuestionsRow
	for rows.Next() {
		var i ListGameRoomQuestionsRow
		if err := rows.Scan(
			&i.OrderIndex,
			&i.ID,
			&i.LanguageID,
			&i.Question,
			&i.Options,
			&i.CorrectIndex,
			&i.Explanation,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pickRandomQuestions = `-- name: PickRandomQuestions :many
SELECT id, language_id, question, options, correct_index, explanation, difficulty, created_at FROM challenge_questions
WHERE ($1::varchar IS NULL OR language_id = $1)
  AND ($2::int IS NULL OR difficulty = $2)
ORDER BY random()
LIMIT $3
`

type PickRandomQuestionsParams struct {
	LanguageID pgtype.Text `json:"language_id"`
	Difficulty pgtype.Int4 `json:"difficulty"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) PickRandomQuestions(ctx context.Context, arg PickRandomQuestionsParams) ([]ChallengeQuestion, error) {
	rows, err := q.db.Query(ctx, pickRandomQuestions, arg.LanguageID, arg.Difficulty, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ChallengeQuestion
	for rows.Next() {
		var i ChallengeQuestion
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Question,
			&i.Options,
			&i.CorrectIndex,
			&i.Explanation,
			&i.Difficulty,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const startGameRoom = `-- name: StartGameRoom :one
UPDATE game_rooms
SET status = 'in_progress', started_at = NOW()
WHERE id = $1 AND status = 'waiting'
RETURNING id, code, host_user_id, status, question_count, time_per_question_seconds, max_participants, created_at, started_at, finished_at
`

func (q *Queries) StartGameRoom(ctx context.Context, id pgtype.UUID) (GameRoom, error) {
	row := q.db.QueryRow(ctx, startGameRoom, id)
	var i GameRoom
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.HostUserID,
		&i.Status,
		&i.QuestionCount,
		&i.TimePerQuestionSeconds,
		&i.MaxParticipants,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const submitGameAnswer = `-- name: SubmitGameAnswer :one
WITH ins AS (
    INSERT INTO game_answers (room_id, participant_id, question_id, selected_index, is_correct, points_earned, time_taken_ms)
    VALUES ($1, $2, $3, $4, $5, $6, $7)
    ON CONFLICT (participant_id, question_id) DO NOTHING
    RETURNING id, room_id, participant_id, question_id, selected_index, is_correct, points_earned, time_taken_ms, answered_at
), upd AS (
    UPDATE game_participants gp
    SET score = gp.score + ins.points_earned
    FROM ins
    WHERE gp.id = ins.participant_id
    RETURNING gp.score
)
SELECT ins.id, ins.room_id, ins.participant_id, ins.question_id, ins.selected_index,
       ins.is_correct, ins.points_earned, ins.time_taken_ms, ins.answered_at,
       upd.score AS new_total_score
FROM ins JOIN upd ON true
`

type SubmitGameAnswerParams struct {
	RoomID        pgtype.UUID `json:"room_id"`
	ParticipantID pgtype.UUID `json:"participant_id"`
	QuestionID    pgtype.UUID `json:"question_id"`
	SelectedIndex pgtype.Int4 `json:"selected_index"`
	IsCorrect     bool        `json:"is_correct"`
	PointsEarned  int32       `json:"points_earned"`
	TimeTakenMs   int32       `json:"time_taken_ms"`
}

type SubmitGameAnswerRow struct {
	ID            pgtype.UUID        `json:"id"`
	RoomID        pgtype.UUID        `json:"room_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	SelectedIndex pgtype.Int4        `json:"selected_index"`
	IsCorrect     bool               `json:"is_correct"`
	PointsEarned  int32              `json:"points_earned"`
	TimeTakenMs   int32              `json:"time_taken_ms"`
	AnsweredAt    pgtype.Timestamptz `json:"answered_at"`
	NewTotalScore int32              `json:"new_total_score"`
}

// Atomic: insert câu trả lời + cộng điểm participant trong 1 statement (CTE),
// tránh cần transaction Go riêng. Nếu đã trả lời câu này rồi (ON CONFLICT DO
// NOTHING) thì không có row nào -> pgx.ErrNoRows ở phía Go.
func (q *Queries) SubmitGameAnswer(ctx context.Context, arg SubmitGameAnswerParams) (SubmitGameAnswerRow, error) {
	row := q.db.QueryRow(ctx, submitGameAnswer,
		arg.RoomID,
		arg.ParticipantID,
		arg.QuestionID,
		arg.SelectedIndex,
		arg.IsCorrect,
		arg.PointsEarned,
		arg.TimeTakenMs,
	)
	var i SubmitGameAnswerRow
	err := row.Scan(
		&i.ID,
		&i.RoomID,
		&i.ParticipantID,
		&i.QuestionID,
		&i.SelectedIndex,
		&i.IsCorrect,
		&i.PointsEarned,
		&i.TimeTakenMs,
		&i.AnsweredAt,
		&i.NewTotalScore,
	)
	return i, err
}
