// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: classes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addClassLesson = `-- name: AddClassLesson :exec
INSERT INTO class_lessons (class_id, lesson_id, order_index)
VALUES ($1, $2, $3)
`

type AddClassLessonParams struct {
	ClassID    pgtype.UUID `json:"class_id"`
	LessonID   pgtype.UUID `json:"lesson_id"`
	OrderIndex int32       `json:"order_index"`
}

func (q *Queries) AddClassLesson(ctx context.Context, arg AddClassLessonParams) error {
	_, err := q.db.Exec(ctx, addClassLesson, arg.ClassID, arg.LessonID, arg.OrderIndex)
	return err
}

const createClass = `-- name: CreateClass :one

INSERT INTO classes (language_id, title, description, level, order_index)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, language_id, title, description, level, order_index, created_at, updated_at
`

type CreateClassParams struct {
	LanguageID  string      `json:"language_id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Level       string      `json:"level"`
	OrderIndex  int32       `json:"order_index"`
}

// ===== Admin CRUD =====
func (q *Queries) CreateClass(ctx context.Context, arg CreateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, createClass,
		arg.LanguageID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.OrderIndex,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteClass = `-- name: DeleteClass :exec
DELETE FROM classes WHERE id = $1
`

func (q *Queries) DeleteClass(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClass, id)
	return err
}

const deleteClassLessons = `-- name: DeleteClassLessons :exec
DELETE FROM class_lessons WHERE class_id = $1
`

// Dùng trong ReplaceClassLessons (xoá hết rồi insert lại theo thứ tự mảng mới).
func (q *Queries) DeleteClassLessons(ctx context.Context, classID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteClassLessons, classID)
	return err
}

const enrollInClass = `-- name: EnrollInClass :exec
INSERT INTO user_class_enrollments (user_id, class_id)
VALUES ($1, $2)
ON CONFLICT (user_id, class_id) DO NOTHING
`

type EnrollInClassParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	ClassID pgtype.UUID `json:"class_id"`
}

func (q *Queries) EnrollInClass(ctx context.Context, arg EnrollInClassParams) error {
	_, err := q.db.Exec(ctx, enrollInClass, arg.UserID, arg.ClassID)
	return err
}

const getClassByID = `-- name: GetClassByID :one
SELECT id, language_id, title, description, level, order_index, created_at, updated_at FROM classes WHERE id = $1
`

func (q *Queries) GetClassByID(ctx context.Context, id pgtype.UUID) (Class, error) {
	row := q.db.QueryRow(ctx, getClassByID, id)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listClassLessonsByClass = `-- name: ListClassLessonsByClass :many
SELECT
    cl.id AS class_lesson_id,
    cl.order_index,
    l.id AS lesson_id,
    l.code,
    l.title,
    l.level
FROM class_lessons cl
JOIN grammar_lessons l ON l.id = cl.lesson_id
WHERE cl.class_id = $1
ORDER BY cl.order_index
`

type ListClassLessonsByClassRow struct {
	ClassLessonID pgtype.UUID `json:"class_lesson_id"`
	OrderIndex    int32       `json:"order_index"`
	LessonID      pgtype.UUID `json:"lesson_id"`
	Code          string      `json:"code"`
	Title         string      `json:"title"`
	Level         pgtype.Text `json:"level"`
}

// Giáo án đầy đủ của 1 lớp, kèm thông tin bài học — dùng cho cả admin (sửa
// giáo án) và learner detail (learner query riêng có thêm completion, xem dưới).
func (q *Queries) ListClassLessonsByClass(ctx context.Context, classID pgtype.UUID) ([]ListClassLessonsByClassRow, error) {
	rows, err := q.db.Query(ctx, listClassLessonsByClass, classID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassLessonsByClassRow
	for rows.Next() {
		var i ListClassLessonsByClassRow
		if err := rows.Scan(
			&i.ClassLessonID,
			&i.OrderIndex,
			&i.LessonID,
			&i.Code,
			&i.Title,
			&i.Level,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassLessonsWithProgress = `-- name: ListClassLessonsWithProgress :many
SELECT
    cl.id AS class_lesson_id,
    cl.order_index,
    l.id AS lesson_id,
    l.code,
    l.title,
    l.level,
    COUNT(e.id) AS total_exercises,
    COUNT(uec.exercise_id) AS completed_exercises
FROM class_lessons cl
JOIN grammar_lessons l ON l.id = cl.lesson_id
LEFT JOIN grammar_exercises e ON e.lesson_id = l.id
LEFT JOIN user_exercise_completions uec ON uec.exercise_id = e.id AND uec.user_id = $1
WHERE cl.class_id = $2
GROUP BY cl.id, cl.order_index, l.id, l.code, l.title, l.level
ORDER BY cl.order_index
`

type ListClassLessonsWithProgressParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	ClassID pgtype.UUID `json:"class_id"`
}

type ListClassLessonsWithProgressRow struct {
	ClassLessonID      pgtype.UUID `json:"class_lesson_id"`
	OrderIndex         int32       `json:"order_index"`
	LessonID           pgtype.UUID `json:"lesson_id"`
	Code               string      `json:"code"`
	Title              string      `json:"title"`
	Level              pgtype.Text `json:"level"`
	TotalExercises     int64       `json:"total_exercises"`
	CompletedExercises int64       `json:"completed_exercises"`
}

// Giống ListClassLessonsByClass nhưng kèm completed_exercises/total_exercises
// của 1 user cụ thể — dùng cho trang chi tiết lớp (learner).
func (q *Queries) ListClassLessonsWithProgress(ctx context.Context, arg ListClassLessonsWithProgressParams) ([]ListClassLessonsWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listClassLessonsWithProgress, arg.UserID, arg.ClassID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassLessonsWithProgressRow
	for rows.Next() {
		var i ListClassLessonsWithProgressRow
		if err := rows.Scan(
			&i.ClassLessonID,
			&i.OrderIndex,
			&i.LessonID,
			&i.Code,
			&i.Title,
			&i.Level,
			&i.TotalExercises,
			&i.CompletedExercises,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassProgressByLanguage = `-- name: ListClassProgressByLanguage :many
SELECT
    cl.class_id,
    cl.lesson_id,
    COUNT(e.id) AS total_exercises,
    COUNT(uec.exercise_id) AS completed_exercises
FROM class_lessons cl
JOIN classes c ON c.id = cl.class_id
LEFT JOIN grammar_exercises e ON e.lesson_id = cl.lesson_id
LEFT JOIN user_exercise_completions uec ON uec.exercise_id = e.id AND uec.user_id = $1
WHERE c.language_id = $2
GROUP BY cl.class_id, cl.lesson_id
`

type ListClassProgressByLanguageParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
}

type ListClassProgressByLanguageRow struct {
	ClassID            pgtype.UUID `json:"class_id"`
	LessonID           pgtype.UUID `json:"lesson_id"`
	TotalExercises     int64       `json:"total_exercises"`
	CompletedExercises int64       `json:"completed_exercises"`
}

// 1 query gộp cho TOÀN BỘ lớp của 1 ngôn ngữ — tránh N+1 khi liệt kê lớp. Mỗi
// dòng = 1 bài trong giáo án, nên COUNT(*) dòng theo class_id ở Go cũng chính
// là lesson_count (lớp chưa có bài nào thì không có dòng, tự hiểu count=0).
// Gộp thành % tiến độ ở Go (lesson "done" khi completed_exercises >= total_exercises và total > 0).
func (q *Queries) ListClassProgressByLanguage(ctx context.Context, arg ListClassProgressByLanguageParams) ([]ListClassProgressByLanguageRow, error) {
	rows, err := q.db.Query(ctx, listClassProgressByLanguage, arg.UserID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassProgressByLanguageRow
	for rows.Next() {
		var i ListClassProgressByLanguageRow
		if err := rows.Scan(
			&i.ClassID,
			&i.LessonID,
			&i.TotalExercises,
			&i.CompletedExercises,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesAdminPaged = `-- name: ListClassesAdminPaged :many
SELECT id, language_id, title, description, level, order_index, created_at, updated_at, COUNT(*) OVER() AS total_count FROM classes
WHERE language_id = $1
  AND ($2::text IS NULL OR title ILIKE '%' || $2::text || '%')
ORDER BY order_index, created_at
LIMIT $4 OFFSET $3
`

type ListClassesAdminPagedParams struct {
	LanguageID string      `json:"language_id"`
	Search     pgtype.Text `json:"search"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type ListClassesAdminPagedRow struct {
	ID          pgtype.UUID        `json:"id"`
	LanguageID  string             `json:"language_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Level       string             `json:"level"`
	OrderIndex  int32              `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	TotalCount  int64              `json:"total_count"`
}

func (q *Queries) ListClassesAdminPaged(ctx context.Context, arg ListClassesAdminPagedParams) ([]ListClassesAdminPagedRow, error) {
	rows, err := q.db.Query(ctx, listClassesAdminPaged,
		arg.LanguageID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListClassesAdminPagedRow
	for rows.Next() {
		var i ListClassesAdminPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listClassesByLanguage = `-- name: ListClassesByLanguage :many
SELECT id, language_id, title, description, level, order_index, created_at, updated_at FROM classes
WHERE language_id = $1
ORDER BY order_index, created_at
`

// Learner — số lớp/ngôn ngữ ít, không cần phân trang (giống Missions admin).
func (q *Queries) ListClassesByLanguage(ctx context.Context, languageID string) ([]Class, error) {
	rows, err := q.db.Query(ctx, listClassesByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Class
	for rows.Next() {
		var i Class
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Title,
			&i.Description,
			&i.Level,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMyEnrollmentsByLanguage = `-- name: ListMyEnrollmentsByLanguage :many
SELECT e.class_id
FROM user_class_enrollments e
JOIN classes c ON c.id = e.class_id
WHERE e.user_id = $1 AND c.language_id = $2
`

type ListMyEnrollmentsByLanguageParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
}

// Trả về class_id user đã ghi danh, lọc theo ngôn ngữ — dùng đánh dấu "enrolled" khi liệt kê lớp.
func (q *Queries) ListMyEnrollmentsByLanguage(ctx context.Context, arg ListMyEnrollmentsByLanguageParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listMyEnrollmentsByLanguage, arg.UserID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var class_id pgtype.UUID
		if err := rows.Scan(&class_id); err != nil {
			return nil, err
		}
		items = append(items, class_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateClass = `-- name: UpdateClass :one
UPDATE classes
SET title = $2, description = $3, level = $4, order_index = $5, updated_at = NOW()
WHERE id = $1
RETURNING id, language_id, title, description, level, order_index, created_at, updated_at
`

type UpdateClassParams struct {
	ID          pgtype.UUID `json:"id"`
	Title       string      `json:"title"`
	Description pgtype.Text `json:"description"`
	Level       string      `json:"level"`
	OrderIndex  int32       `json:"order_index"`
}

func (q *Queries) UpdateClass(ctx context.Context, arg UpdateClassParams) (Class, error) {
	row := q.db.QueryRow(ctx, updateClass,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Level,
		arg.OrderIndex,
	)
	var i Class
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.Title,
		&i.Description,
		&i.Level,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
