// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: decks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addVocabularyToDeck = `-- name: AddVocabularyToDeck :execrows
INSERT INTO deck_vocabularies (deck_id, vocabulary_id) VALUES ($1, $2)
ON CONFLICT DO NOTHING
`

type AddVocabularyToDeckParams struct {
	DeckID       pgtype.UUID `json:"deck_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) AddVocabularyToDeck(ctx context.Context, arg AddVocabularyToDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, addVocabularyToDeck, arg.DeckID, arg.VocabularyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createDeck = `-- name: CreateDeck :one
INSERT INTO user_decks (user_id, name, description, color, icon)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, user_id, name, description, color, icon, is_public, is_system, created_at, updated_at
`

type CreateDeckParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       pgtype.Text `json:"color"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) CreateDeck(ctx context.Context, arg CreateDeckParams) (UserDeck, error) {
	row := q.db.QueryRow(ctx, createDeck,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Icon,
	)
	var i UserDeck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsPublic,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteDeck = `-- name: DeleteDeck :execrows
DELETE FROM user_decks WHERE id = $1 AND user_id = $2
`

type DeleteDeckParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) DeleteDeck(ctx context.Context, arg DeleteDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeck, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDeck = `-- name: GetDeck :one
SELECT id, user_id, name, description, color, icon, is_public, is_system, created_at, updated_at FROM user_decks WHERE id = $1 AND user_id = $2
`

type GetDeckParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetDeck(ctx context.Context, arg GetDeckParams) (UserDeck, error) {
	row := q.db.QueryRow(ctx, getDeck, arg.ID, arg.UserID)
	var i UserDeck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsPublic,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeckVocabularies = `-- name: GetDeckVocabularies :many
SELECT v.id, v.language_id, v.term, v.phonetic, v.meaning, v.example, v.topic, v.level, v.audio_url, v.image_url, v.created_at FROM vocabularies v
JOIN deck_vocabularies dv ON v.id = dv.vocabulary_id
WHERE dv.deck_id = $1
ORDER BY dv.added_at DESC
`

func (q *Queries) GetDeckVocabularies(ctx context.Context, deckID pgtype.UUID) ([]Vocabulary, error) {
	rows, err := q.db.Query(ctx, getDeckVocabularies, deckID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vocabulary
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserDecks = `-- name: ListUserDecks :many
SELECT id, user_id, name, description, color, icon, is_public, is_system, created_at, updated_at
FROM user_decks
WHERE user_id = $1
ORDER BY is_system DESC, created_at DESC
`

func (q *Queries) ListUserDecks(ctx context.Context, userID pgtype.UUID) ([]UserDeck, error) {
	rows, err := q.db.Query(ctx, listUserDecks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserDeck
	for rows.Next() {
		var i UserDeck
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Description,
			&i.Color,
			&i.Icon,
			&i.IsPublic,
			&i.IsSystem,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeVocabularyFromDeck = `-- name: RemoveVocabularyFromDeck :execrows
DELETE FROM deck_vocabularies WHERE deck_id = $1 AND vocabulary_id = $2
`

type RemoveVocabularyFromDeckParams struct {
	DeckID       pgtype.UUID `json:"deck_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) RemoveVocabularyFromDeck(ctx context.Context, arg RemoveVocabularyFromDeckParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeVocabularyFromDeck, arg.DeckID, arg.VocabularyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateDeck = `-- name: UpdateDeck :one
UPDATE user_decks
SET name = $3, description = $4, color = $5, icon = $6, updated_at = NOW()
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, description, color, icon, is_public, is_system, created_at, updated_at
`

type UpdateDeckParams struct {
	ID          pgtype.UUID `json:"id"`
	UserID      pgtype.UUID `json:"user_id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Color       pgtype.Text `json:"color"`
	Icon        pgtype.Text `json:"icon"`
}

func (q *Queries) UpdateDeck(ctx context.Context, arg UpdateDeckParams) (UserDeck, error) {
	row := q.db.QueryRow(ctx, updateDeck,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Description,
		arg.Color,
		arg.Icon,
	)
	var i UserDeck
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Description,
		&i.Color,
		&i.Icon,
		&i.IsPublic,
		&i.IsSystem,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
