// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: dialogues.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDialogueById = `-- name: GetDialogueById :one
SELECT d.id, d.lesson_id, d.title, d.description, d.difficulty, d.order_index, d.created_at, json_agg(dl ORDER BY dl.order_index) as lines
FROM dialogues d
LEFT JOIN dialogue_lines dl ON dl.dialogue_id = d.id
WHERE d.id = $1
GROUP BY d.id
`

type GetDialogueByIdRow struct {
	ID          pgtype.UUID        `json:"id"`
	LessonID    pgtype.UUID        `json:"lesson_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Difficulty  pgtype.Text        `json:"difficulty"`
	OrderIndex  pgtype.Int4        `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Lines       []byte             `json:"lines"`
}

func (q *Queries) GetDialogueById(ctx context.Context, id pgtype.UUID) (GetDialogueByIdRow, error) {
	row := q.db.QueryRow(ctx, getDialogueById, id)
	var i GetDialogueByIdRow
	err := row.Scan(
		&i.ID,
		&i.LessonID,
		&i.Title,
		&i.Description,
		&i.Difficulty,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.Lines,
	)
	return i, err
}

const getDialoguesByLesson = `-- name: GetDialoguesByLesson :many
SELECT d.id, d.lesson_id, d.title, d.description, d.difficulty, d.order_index, d.created_at, json_agg(dl ORDER BY dl.order_index) as lines
FROM dialogues d
LEFT JOIN dialogue_lines dl ON dl.dialogue_id = d.id
WHERE d.lesson_id = $1
GROUP BY d.id
ORDER BY d.order_index
`

type GetDialoguesByLessonRow struct {
	ID          pgtype.UUID        `json:"id"`
	LessonID    pgtype.UUID        `json:"lesson_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Difficulty  pgtype.Text        `json:"difficulty"`
	OrderIndex  pgtype.Int4        `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Lines       []byte             `json:"lines"`
}

func (q *Queries) GetDialoguesByLesson(ctx context.Context, lessonID pgtype.UUID) ([]GetDialoguesByLessonRow, error) {
	rows, err := q.db.Query(ctx, getDialoguesByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDialoguesByLessonRow
	for rows.Next() {
		var i GetDialoguesByLessonRow
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Title,
			&i.Description,
			&i.Difficulty,
			&i.OrderIndex,
			&i.CreatedAt,
			&i.Lines,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
