// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeExerciseSession = `-- name: CompleteExerciseSession :one
UPDATE exercise_sessions
SET correct_answers = $2,
    xp_earned = $3,
    duration_seconds = $4,
    details = $5,
    completed_at = NOW()
WHERE id = $1
RETURNING id, user_id, deck_id, exercise_type, total_questions, correct_answers, xp_earned, duration_seconds, details, started_at, completed_at
`

type CompleteExerciseSessionParams struct {
	ID              pgtype.UUID `json:"id"`
	CorrectAnswers  pgtype.Int4 `json:"correct_answers"`
	XpEarned        pgtype.Int8 `json:"xp_earned"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
	Details         []byte      `json:"details"`
}

func (q *Queries) CompleteExerciseSession(ctx context.Context, arg CompleteExerciseSessionParams) (ExerciseSession, error) {
	row := q.db.QueryRow(ctx, completeExerciseSession,
		arg.ID,
		arg.CorrectAnswers,
		arg.XpEarned,
		arg.DurationSeconds,
		arg.Details,
	)
	var i ExerciseSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.ExerciseType,
		&i.TotalQuestions,
		&i.CorrectAnswers,
		&i.XpEarned,
		&i.DurationSeconds,
		&i.Details,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createExerciseSession = `-- name: CreateExerciseSession :one
INSERT INTO exercise_sessions (user_id, deck_id, exercise_type, total_questions, correct_answers, xp_earned, duration_seconds, details)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, user_id, deck_id, exercise_type, total_questions, correct_answers, xp_earned, duration_seconds, details, started_at, completed_at
`

type CreateExerciseSessionParams struct {
	UserID          pgtype.UUID `json:"user_id"`
	DeckID          pgtype.UUID `json:"deck_id"`
	ExerciseType    string      `json:"exercise_type"`
	TotalQuestions  pgtype.Int4 `json:"total_questions"`
	CorrectAnswers  pgtype.Int4 `json:"correct_answers"`
	XpEarned        pgtype.Int8 `json:"xp_earned"`
	DurationSeconds pgtype.Int4 `json:"duration_seconds"`
	Details         []byte      `json:"details"`
}

func (q *Queries) CreateExerciseSession(ctx context.Context, arg CreateExerciseSessionParams) (ExerciseSession, error) {
	row := q.db.QueryRow(ctx, createExerciseSession,
		arg.UserID,
		arg.DeckID,
		arg.ExerciseType,
		arg.TotalQuestions,
		arg.CorrectAnswers,
		arg.XpEarned,
		arg.DurationSeconds,
		arg.Details,
	)
	var i ExerciseSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.ExerciseType,
		&i.TotalQuestions,
		&i.CorrectAnswers,
		&i.XpEarned,
		&i.DurationSeconds,
		&i.Details,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDeckSessionStats = `-- name: GetDeckSessionStats :one
SELECT
    COUNT(*) as total_sessions,
    COALESCE(SUM(total_questions), 0) as total_questions,
    COALESCE(SUM(correct_answers), 0) as total_correct,
    COALESCE(SUM(xp_earned), 0) as total_xp,
    COALESCE(AVG(duration_seconds), 0) as avg_duration
FROM exercise_sessions
WHERE deck_id = $1 AND completed_at IS NOT NULL
`

type GetDeckSessionStatsRow struct {
	TotalSessions  int64       `json:"total_sessions"`
	TotalQuestions interface{} `json:"total_questions"`
	TotalCorrect   interface{} `json:"total_correct"`
	TotalXp        interface{} `json:"total_xp"`
	AvgDuration    interface{} `json:"avg_duration"`
}

func (q *Queries) GetDeckSessionStats(ctx context.Context, deckID pgtype.UUID) (GetDeckSessionStatsRow, error) {
	row := q.db.QueryRow(ctx, getDeckSessionStats, deckID)
	var i GetDeckSessionStatsRow
	err := row.Scan(
		&i.TotalSessions,
		&i.TotalQuestions,
		&i.TotalCorrect,
		&i.TotalXp,
		&i.AvgDuration,
	)
	return i, err
}

const getExerciseSession = `-- name: GetExerciseSession :one
SELECT id, user_id, deck_id, exercise_type, total_questions, correct_answers, xp_earned, duration_seconds, details, started_at, completed_at FROM exercise_sessions WHERE id = $1
`

func (q *Queries) GetExerciseSession(ctx context.Context, id pgtype.UUID) (ExerciseSession, error) {
	row := q.db.QueryRow(ctx, getExerciseSession, id)
	var i ExerciseSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DeckID,
		&i.ExerciseType,
		&i.TotalQuestions,
		&i.CorrectAnswers,
		&i.XpEarned,
		&i.DurationSeconds,
		&i.Details,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getUserExerciseSessions = `-- name: GetUserExerciseSessions :many
SELECT id, user_id, deck_id, exercise_type, total_questions, correct_answers, xp_earned, duration_seconds, details, started_at, completed_at FROM exercise_sessions
WHERE user_id = $1
ORDER BY started_at DESC
LIMIT $2
`

type GetUserExerciseSessionsParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

func (q *Queries) GetUserExerciseSessions(ctx context.Context, arg GetUserExerciseSessionsParams) ([]ExerciseSession, error) {
	rows, err := q.db.Query(ctx, getUserExerciseSessions, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseSession
	for rows.Next() {
		var i ExerciseSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DeckID,
			&i.ExerciseType,
			&i.TotalQuestions,
			&i.CorrectAnswers,
			&i.XpEarned,
			&i.DurationSeconds,
			&i.Details,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
