// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: exercise_types.sql

package db

import (
	"context"
)

const getActiveExerciseTypes = `-- name: GetActiveExerciseTypes :many
SELECT id, name, description, icon, config, is_active, order_index
FROM exercise_types
WHERE is_active = TRUE
ORDER BY order_index
`

func (q *Queries) GetActiveExerciseTypes(ctx context.Context) ([]ExerciseType, error) {
	rows, err := q.db.Query(ctx, getActiveExerciseTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExerciseType
	for rows.Next() {
		var i ExerciseType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Config,
			&i.IsActive,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExerciseType = `-- name: GetExerciseType :one
SELECT id, name, description, icon, config, is_active, order_index
FROM exercise_types
WHERE id = $1
`

func (q *Queries) GetExerciseType(ctx context.Context, id string) (ExerciseType, error) {
	row := q.db.QueryRow(ctx, getExerciseType, id)
	var i ExerciseType
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Icon,
		&i.Config,
		&i.IsActive,
		&i.OrderIndex,
	)
	return i, err
}
