// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grammar.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGrammarLessonByCode = `-- name: GetGrammarLessonByCode :one
SELECT id, topic_id, code, title, level, order_index, content, created_at, updated_at FROM grammar_lessons
WHERE code = $1
`

func (q *Queries) GetGrammarLessonByCode(ctx context.Context, code string) (GrammarLesson, error) {
	row := q.db.QueryRow(ctx, getGrammarLessonByCode, code)
	var i GrammarLesson
	err := row.Scan(
		&i.ID,
		&i.TopicID,
		&i.Code,
		&i.Title,
		&i.Level,
		&i.OrderIndex,
		&i.Content,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGrammarExercisesByLesson = `-- name: ListGrammarExercisesByLesson :many
SELECT id, lesson_id, type, question, options, correct_answer, explanation, order_index, level, hint, xp_reward FROM grammar_exercises
WHERE lesson_id = $1
ORDER BY order_index
`

func (q *Queries) ListGrammarExercisesByLesson(ctx context.Context, lessonID pgtype.UUID) ([]GrammarExercise, error) {
	rows, err := q.db.Query(ctx, listGrammarExercisesByLesson, lessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrammarExercise
	for rows.Next() {
		var i GrammarExercise
		if err := rows.Scan(
			&i.ID,
			&i.LessonID,
			&i.Type,
			&i.Question,
			&i.Options,
			&i.CorrectAnswer,
			&i.Explanation,
			&i.OrderIndex,
			&i.Level,
			&i.Hint,
			&i.XpReward,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrammarLessonsByLanguage = `-- name: ListGrammarLessonsByLanguage :many
SELECT l.id, l.topic_id, l.code, l.title, l.level, l.order_index
FROM grammar_lessons l
JOIN grammar_topics t ON t.id = l.topic_id
WHERE t.language_id = $1
ORDER BY l.order_index, l.created_at
`

type ListGrammarLessonsByLanguageRow struct {
	ID         pgtype.UUID `json:"id"`
	TopicID    pgtype.UUID `json:"topic_id"`
	Code       string      `json:"code"`
	Title      string      `json:"title"`
	Level      pgtype.Text `json:"level"`
	OrderIndex pgtype.Int4 `json:"order_index"`
}

func (q *Queries) ListGrammarLessonsByLanguage(ctx context.Context, languageID string) ([]ListGrammarLessonsByLanguageRow, error) {
	rows, err := q.db.Query(ctx, listGrammarLessonsByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGrammarLessonsByLanguageRow
	for rows.Next() {
		var i ListGrammarLessonsByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.TopicID,
			&i.Code,
			&i.Title,
			&i.Level,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGrammarTopicsByLanguage = `-- name: ListGrammarTopicsByLanguage :many
SELECT id, language_id, code, title, description, order_index, created_at FROM grammar_topics
WHERE language_id = $1
ORDER BY order_index, created_at
`

func (q *Queries) ListGrammarTopicsByLanguage(ctx context.Context, languageID string) ([]GrammarTopic, error) {
	rows, err := q.db.Query(ctx, listGrammarTopicsByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GrammarTopic
	for rows.Next() {
		var i GrammarTopic
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Code,
			&i.Title,
			&i.Description,
			&i.OrderIndex,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
