// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package db

import (
	"context"
)

const getLanguageByID = `-- name: GetLanguageByID :one
SELECT id, name, code, created_at FROM languages
WHERE id = $1
`

func (q *Queries) GetLanguageByID(ctx context.Context, id string) (Language, error) {
	row := q.db.QueryRow(ctx, getLanguageByID, id)
	var i Language
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const listLanguages = `-- name: ListLanguages :many
SELECT id, name, code, created_at FROM languages
ORDER BY name
`

func (q *Queries) ListLanguages(ctx context.Context) ([]Language, error) {
	rows, err := q.db.Query(ctx, listLanguages)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Language
	for rows.Next() {
		var i Language
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
