// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: listening.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getListeningPassageByID = `-- name: GetListeningPassageByID :one
SELECT id, language_id, title, script, topic, level, order_index, created_at, updated_at FROM listening_passages
WHERE id = $1
`

func (q *Queries) GetListeningPassageByID(ctx context.Context, id pgtype.UUID) (ListeningPassage, error) {
	row := q.db.QueryRow(ctx, getListeningPassageByID, id)
	var i ListeningPassage
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.Title,
		&i.Script,
		&i.Topic,
		&i.Level,
		&i.OrderIndex,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getListeningQuestionByID = `-- name: GetListeningQuestionByID :one
SELECT id, passage_id, question, options, correct_answer, explanation, order_index FROM listening_questions
WHERE id = $1
`

func (q *Queries) GetListeningQuestionByID(ctx context.Context, id pgtype.UUID) (ListeningQuestion, error) {
	row := q.db.QueryRow(ctx, getListeningQuestionByID, id)
	var i ListeningQuestion
	err := row.Scan(
		&i.ID,
		&i.PassageID,
		&i.Question,
		&i.Options,
		&i.CorrectAnswer,
		&i.Explanation,
		&i.OrderIndex,
	)
	return i, err
}

const listListeningPassagesByLanguage = `-- name: ListListeningPassagesByLanguage :many
SELECT id, language_id, title, topic, level, order_index
FROM listening_passages
WHERE language_id = $1
ORDER BY order_index, created_at
`

type ListListeningPassagesByLanguageRow struct {
	ID         pgtype.UUID `json:"id"`
	LanguageID string      `json:"language_id"`
	Title      string      `json:"title"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	OrderIndex pgtype.Int4 `json:"order_index"`
}

func (q *Queries) ListListeningPassagesByLanguage(ctx context.Context, languageID string) ([]ListListeningPassagesByLanguageRow, error) {
	rows, err := q.db.Query(ctx, listListeningPassagesByLanguage, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListeningPassagesByLanguageRow
	for rows.Next() {
		var i ListListeningPassagesByLanguageRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Title,
			&i.Topic,
			&i.Level,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listListeningQuestionsByPassage = `-- name: ListListeningQuestionsByPassage :many
SELECT id, passage_id, question, options, order_index
FROM listening_questions
WHERE passage_id = $1
ORDER BY order_index
`

type ListListeningQuestionsByPassageRow struct {
	ID         pgtype.UUID `json:"id"`
	PassageID  pgtype.UUID `json:"passage_id"`
	Question   string      `json:"question"`
	Options    []byte      `json:"options"`
	OrderIndex pgtype.Int4 `json:"order_index"`
}

// KHÔNG select correct_answer — câu hỏi hiển thị cho learner trước khi nộp
// bài không được lộ đáp án (khác với grammar_exercises cũ, vốn đã lộ sẵn ở FE).
func (q *Queries) ListListeningQuestionsByPassage(ctx context.Context, passageID pgtype.UUID) ([]ListListeningQuestionsByPassageRow, error) {
	rows, err := q.db.Query(ctx, listListeningQuestionsByPassage, passageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListListeningQuestionsByPassageRow
	for rows.Next() {
		var i ListListeningQuestionsByPassageRow
		if err := rows.Scan(
			&i.ID,
			&i.PassageID,
			&i.Question,
			&i.Options,
			&i.OrderIndex,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
