// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: missions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMission = `-- name: CreateMission :one
INSERT INTO missions (title, description, period, action_type, target_count, reward_exp, reward_points, starts_at, ends_at, created_by)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, title, description, period, action_type, target_count, reward_exp, reward_points, starts_at, ends_at, is_active, created_by, created_at, updated_at
`

type CreateMissionParams struct {
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Period       string             `json:"period"`
	ActionType   string             `json:"action_type"`
	TargetCount  int32              `json:"target_count"`
	RewardExp    int32              `json:"reward_exp"`
	RewardPoints int32              `json:"reward_points"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
}

func (q *Queries) CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, createMission,
		arg.Title,
		arg.Description,
		arg.Period,
		arg.ActionType,
		arg.TargetCount,
		arg.RewardExp,
		arg.RewardPoints,
		arg.StartsAt,
		arg.EndsAt,
		arg.CreatedBy,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Period,
		&i.ActionType,
		&i.TargetCount,
		&i.RewardExp,
		&i.RewardPoints,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateMission = `-- name: DeactivateMission :exec
UPDATE missions SET is_active = FALSE, updated_at = NOW() WHERE id = $1
`

// Xoá mềm — giữ lại user_mission_progress đã có (không mất lịch sử/FK).
func (q *Queries) DeactivateMission(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deactivateMission, id)
	return err
}

const getMissionByID = `-- name: GetMissionByID :one
SELECT id, title, description, period, action_type, target_count, reward_exp, reward_points, starts_at, ends_at, is_active, created_by, created_at, updated_at FROM missions WHERE id = $1
`

func (q *Queries) GetMissionByID(ctx context.Context, id pgtype.UUID) (Mission, error) {
	row := q.db.QueryRow(ctx, getMissionByID, id)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Period,
		&i.ActionType,
		&i.TargetCount,
		&i.RewardExp,
		&i.RewardPoints,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveMissionsByAction = `-- name: ListActiveMissionsByAction :many
SELECT id, title, description, period, action_type, target_count, reward_exp, reward_points, starts_at, ends_at, is_active, created_by, created_at, updated_at FROM missions
WHERE action_type = $1
  AND is_active = TRUE
  AND (period != 'event' OR (starts_at IS NOT NULL AND ends_at IS NOT NULL AND NOW() BETWEEN starts_at AND ends_at))
ORDER BY created_at
`

// Nhiệm vụ event chỉ tính khi NOW() đang trong khoảng starts_at..ends_at.
func (q *Queries) ListActiveMissionsByAction(ctx context.Context, actionType string) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listActiveMissionsByAction, actionType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Period,
			&i.ActionType,
			&i.TargetCount,
			&i.RewardExp,
			&i.RewardPoints,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllMissions = `-- name: ListAllMissions :many
SELECT id, title, description, period, action_type, target_count, reward_exp, reward_points, starts_at, ends_at, is_active, created_by, created_at, updated_at FROM missions
ORDER BY is_active DESC, created_at DESC
`

// Dành cho admin — thấy cả nhiệm vụ đã tắt (is_active=false) để còn bật lại.
func (q *Queries) ListAllMissions(ctx context.Context) ([]Mission, error) {
	rows, err := q.db.Query(ctx, listAllMissions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Mission
	for rows.Next() {
		var i Mission
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Period,
			&i.ActionType,
			&i.TargetCount,
			&i.RewardExp,
			&i.RewardPoints,
			&i.StartsAt,
			&i.EndsAt,
			&i.IsActive,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMissionsWithProgress = `-- name: ListMissionsWithProgress :many
SELECT
    m.id, m.title, m.description, m.period, m.action_type, m.target_count,
    m.reward_exp, m.reward_points, m.starts_at, m.ends_at,
    COALESCE(ump.progress_count, 0) AS progress_count,
    ump.completed_at
FROM missions m
LEFT JOIN user_mission_progress ump
    ON ump.mission_id = m.id
    AND ump.user_id = $1
    AND ump.period_key = CASE m.period
        WHEN 'daily' THEN to_char(NOW(), 'YYYY-MM-DD')
        WHEN 'weekly' THEN to_char(NOW(), 'IYYY-"W"IW')
        WHEN 'monthly' THEN to_char(NOW(), 'YYYY-MM')
        ELSE m.id::text
    END
WHERE m.is_active = TRUE
  AND (m.period != 'event' OR (m.starts_at IS NOT NULL AND m.ends_at IS NOT NULL AND NOW() BETWEEN m.starts_at AND m.ends_at))
ORDER BY m.period, m.created_at
`

type ListMissionsWithProgressRow struct {
	ID            pgtype.UUID        `json:"id"`
	Title         string             `json:"title"`
	Description   pgtype.Text        `json:"description"`
	Period        string             `json:"period"`
	ActionType    string             `json:"action_type"`
	TargetCount   int32              `json:"target_count"`
	RewardExp     int32              `json:"reward_exp"`
	RewardPoints  int32              `json:"reward_points"`
	StartsAt      pgtype.Timestamptz `json:"starts_at"`
	EndsAt        pgtype.Timestamptz `json:"ends_at"`
	ProgressCount int32              `json:"progress_count"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

// period_key tính theo CÙNG quy tắc với Go (mission_service.periodKey) —
// daily=YYYY-MM-DD, weekly=IYYY-"W"IW (ISO week), monthly=YYYY-MM, event=mission id.
func (q *Queries) ListMissionsWithProgress(ctx context.Context, userID pgtype.UUID) ([]ListMissionsWithProgressRow, error) {
	rows, err := q.db.Query(ctx, listMissionsWithProgress, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListMissionsWithProgressRow
	for rows.Next() {
		var i ListMissionsWithProgressRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Period,
			&i.ActionType,
			&i.TargetCount,
			&i.RewardExp,
			&i.RewardPoints,
			&i.StartsAt,
			&i.EndsAt,
			&i.ProgressCount,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMissionProgressCompleted = `-- name: MarkMissionProgressCompleted :one
UPDATE user_mission_progress
SET completed_at = NOW(), updated_at = NOW()
WHERE id = $1 AND completed_at IS NULL
RETURNING id, user_id, mission_id, period_key, progress_count, completed_at, created_at, updated_at
`

// WHERE completed_at IS NULL đảm bảo chỉ 1 lần cộng thưởng dù gọi nhiều lần
// (ví dụ race giữa 2 request) — gọi lần 2 trả 0 dòng (pgx.ErrNoRows).
func (q *Queries) MarkMissionProgressCompleted(ctx context.Context, id pgtype.UUID) (UserMissionProgress, error) {
	row := q.db.QueryRow(ctx, markMissionProgressCompleted, id)
	var i UserMissionProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.PeriodKey,
		&i.ProgressCount,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMission = `-- name: UpdateMission :one
UPDATE missions
SET title = $2,
    description = $3,
    period = $4,
    action_type = $5,
    target_count = $6,
    reward_exp = $7,
    reward_points = $8,
    starts_at = $9,
    ends_at = $10,
    is_active = $11,
    updated_at = NOW()
WHERE id = $1
RETURNING id, title, description, period, action_type, target_count, reward_exp, reward_points, starts_at, ends_at, is_active, created_by, created_at, updated_at
`

type UpdateMissionParams struct {
	ID           pgtype.UUID        `json:"id"`
	Title        string             `json:"title"`
	Description  pgtype.Text        `json:"description"`
	Period       string             `json:"period"`
	ActionType   string             `json:"action_type"`
	TargetCount  int32              `json:"target_count"`
	RewardExp    int32              `json:"reward_exp"`
	RewardPoints int32              `json:"reward_points"`
	StartsAt     pgtype.Timestamptz `json:"starts_at"`
	EndsAt       pgtype.Timestamptz `json:"ends_at"`
	IsActive     bool               `json:"is_active"`
}

func (q *Queries) UpdateMission(ctx context.Context, arg UpdateMissionParams) (Mission, error) {
	row := q.db.QueryRow(ctx, updateMission,
		arg.ID,
		arg.Title,
		arg.Description,
		arg.Period,
		arg.ActionType,
		arg.TargetCount,
		arg.RewardExp,
		arg.RewardPoints,
		arg.StartsAt,
		arg.EndsAt,
		arg.IsActive,
	)
	var i Mission
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Period,
		&i.ActionType,
		&i.TargetCount,
		&i.RewardExp,
		&i.RewardPoints,
		&i.StartsAt,
		&i.EndsAt,
		&i.IsActive,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMissionProgress = `-- name: UpsertMissionProgress :one
INSERT INTO user_mission_progress (user_id, mission_id, period_key, progress_count)
VALUES ($1, $2, $3, $4)
ON CONFLICT (user_id, mission_id, period_key)
DO UPDATE SET progress_count = user_mission_progress.progress_count + EXCLUDED.progress_count, updated_at = NOW()
RETURNING id, user_id, mission_id, period_key, progress_count, completed_at, created_at, updated_at
`

type UpsertMissionProgressParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	MissionID     pgtype.UUID `json:"mission_id"`
	PeriodKey     string      `json:"period_key"`
	ProgressCount int32       `json:"progress_count"`
}

// Atomic: cộng thêm progress_count, trả về dòng sau khi cộng để Go kiểm tra
// đã đạt target_count hay chưa (chống race khi 2 request cùng lúc).
func (q *Queries) UpsertMissionProgress(ctx context.Context, arg UpsertMissionProgressParams) (UserMissionProgress, error) {
	row := q.db.QueryRow(ctx, upsertMissionProgress,
		arg.UserID,
		arg.MissionID,
		arg.PeriodKey,
		arg.ProgressCount,
	)
	var i UserMissionProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.MissionID,
		&i.PeriodKey,
		&i.ProgressCount,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
