// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type GrammarExercise struct {
	ID            pgtype.UUID `json:"id"`
	LessonID      pgtype.UUID `json:"lesson_id"`
	Type          string      `json:"type"`
	Question      string      `json:"question"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Explanation   pgtype.Text `json:"explanation"`
	OrderIndex    pgtype.Int4 `json:"order_index"`
}

type GrammarLesson struct {
	ID         pgtype.UUID        `json:"id"`
	TopicID    pgtype.UUID        `json:"topic_id"`
	Code       string             `json:"code"`
	Title      string             `json:"title"`
	Level      pgtype.Text        `json:"level"`
	OrderIndex pgtype.Int4        `json:"order_index"`
	Content    []byte             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type GrammarTopic struct {
	ID          pgtype.UUID        `json:"id"`
	LanguageID  string             `json:"language_id"`
	Code        string             `json:"code"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  pgtype.Int4        `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Language struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	StreakCount  pgtype.Int4        `json:"streak_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserVocabularyReview struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	VocabularyID   pgtype.UUID        `json:"vocabulary_id"`
	SrsStage       pgtype.Int4        `json:"srs_stage"`
	EaseFactor     pgtype.Float8      `json:"ease_factor"`
	IntervalDays   pgtype.Int4        `json:"interval_days"`
	NextReviewAt   pgtype.Timestamptz `json:"next_review_at"`
	LastReviewedAt pgtype.Timestamptz `json:"last_reviewed_at"`
}

type Vocabulary struct {
	ID         pgtype.UUID        `json:"id"`
	LanguageID string             `json:"language_id"`
	Term       string             `json:"term"`
	Phonetic   pgtype.Text        `json:"phonetic"`
	Meaning    string             `json:"meaning"`
	AudioUrl   pgtype.Text        `json:"audio_url"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}
