// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ChallengeQuestion struct {
	ID           pgtype.UUID        `json:"id"`
	LanguageID   pgtype.Text        `json:"language_id"`
	Question     string             `json:"question"`
	Options      []byte             `json:"options"`
	CorrectIndex int32              `json:"correct_index"`
	Explanation  pgtype.Text        `json:"explanation"`
	Difficulty   int32              `json:"difficulty"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type DeckVocabulary struct {
	DeckID       pgtype.UUID        `json:"deck_id"`
	VocabularyID pgtype.UUID        `json:"vocabulary_id"`
	AddedAt      pgtype.Timestamptz `json:"added_at"`
}

type Dialogue struct {
	ID          pgtype.UUID        `json:"id"`
	LessonID    pgtype.UUID        `json:"lesson_id"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	Difficulty  pgtype.Text        `json:"difficulty"`
	OrderIndex  pgtype.Int4        `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type DialogueLine struct {
	ID          pgtype.UUID        `json:"id"`
	DialogueID  pgtype.UUID        `json:"dialogue_id"`
	Speaker     string             `json:"speaker"`
	Text        string             `json:"text"`
	Translation pgtype.Text        `json:"translation"`
	AudioUrl    pgtype.Text        `json:"audio_url"`
	OrderIndex  pgtype.Int4        `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type ExerciseSession struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	DeckID          pgtype.UUID        `json:"deck_id"`
	ExerciseType    string             `json:"exercise_type"`
	TotalQuestions  pgtype.Int4        `json:"total_questions"`
	CorrectAnswers  pgtype.Int4        `json:"correct_answers"`
	XpEarned        pgtype.Int8        `json:"xp_earned"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Details         []byte             `json:"details"`
	StartedAt       pgtype.Timestamptz `json:"started_at"`
	CompletedAt     pgtype.Timestamptz `json:"completed_at"`
}

type ExerciseType struct {
	ID          string      `json:"id"`
	Name        string      `json:"name"`
	Description pgtype.Text `json:"description"`
	Icon        pgtype.Text `json:"icon"`
	Config      []byte      `json:"config"`
	IsActive    pgtype.Bool `json:"is_active"`
	OrderIndex  pgtype.Int4 `json:"order_index"`
}

type GameAnswer struct {
	ID            pgtype.UUID        `json:"id"`
	RoomID        pgtype.UUID        `json:"room_id"`
	ParticipantID pgtype.UUID        `json:"participant_id"`
	QuestionID    pgtype.UUID        `json:"question_id"`
	SelectedIndex pgtype.Int4        `json:"selected_index"`
	IsCorrect     bool               `json:"is_correct"`
	PointsEarned  int32              `json:"points_earned"`
	TimeTakenMs   int32              `json:"time_taken_ms"`
	AnsweredAt    pgtype.Timestamptz `json:"answered_at"`
}

type GameParticipant struct {
	ID       pgtype.UUID        `json:"id"`
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	Score    int32              `json:"score"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

type GameRoom struct {
	ID                     pgtype.UUID        `json:"id"`
	Code                   string             `json:"code"`
	HostUserID             pgtype.UUID        `json:"host_user_id"`
	Status                 string             `json:"status"`
	QuestionCount          int32              `json:"question_count"`
	TimePerQuestionSeconds int32              `json:"time_per_question_seconds"`
	MaxParticipants        int32              `json:"max_participants"`
	IsPractice             bool               `json:"is_practice"`
	Difficulty             pgtype.Int4        `json:"difficulty"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	StartedAt              pgtype.Timestamptz `json:"started_at"`
	FinishedAt             pgtype.Timestamptz `json:"finished_at"`
}

type GameRoomBan struct {
	RoomID   pgtype.UUID        `json:"room_id"`
	UserID   pgtype.UUID        `json:"user_id"`
	BannedAt pgtype.Timestamptz `json:"banned_at"`
}

type GameRoomQuestion struct {
	RoomID     pgtype.UUID `json:"room_id"`
	QuestionID pgtype.UUID `json:"question_id"`
	OrderIndex int32       `json:"order_index"`
}

type GrammarExercise struct {
	ID            pgtype.UUID `json:"id"`
	LessonID      pgtype.UUID `json:"lesson_id"`
	Type          string      `json:"type"`
	Question      string      `json:"question"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Explanation   pgtype.Text `json:"explanation"`
	OrderIndex    pgtype.Int4 `json:"order_index"`
	Level         pgtype.Int4 `json:"level"`
	Hint          pgtype.Text `json:"hint"`
	XpReward      pgtype.Int4 `json:"xp_reward"`
}

type GrammarLesson struct {
	ID         pgtype.UUID        `json:"id"`
	TopicID    pgtype.UUID        `json:"topic_id"`
	Code       string             `json:"code"`
	Title      string             `json:"title"`
	Level      pgtype.Text        `json:"level"`
	OrderIndex pgtype.Int4        `json:"order_index"`
	Content    []byte             `json:"content"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type GrammarTopic struct {
	ID          pgtype.UUID        `json:"id"`
	LanguageID  string             `json:"language_id"`
	Code        string             `json:"code"`
	Title       string             `json:"title"`
	Description pgtype.Text        `json:"description"`
	OrderIndex  pgtype.Int4        `json:"order_index"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Language struct {
	ID        string             `json:"id"`
	Name      string             `json:"name"`
	Code      string             `json:"code"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	StreakCount  pgtype.Int4        `json:"streak_count"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type UserDeck struct {
	ID          pgtype.UUID        `json:"id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Name        string             `json:"name"`
	Description pgtype.Text        `json:"description"`
	Color       pgtype.Text        `json:"color"`
	Icon        pgtype.Text        `json:"icon"`
	IsPublic    pgtype.Bool        `json:"is_public"`
	IsSystem    pgtype.Bool        `json:"is_system"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserExerciseProgress struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	VocabularyID    pgtype.UUID        `json:"vocabulary_id"`
	ExerciseType    string             `json:"exercise_type"`
	Status          pgtype.Text        `json:"status"`
	Attempts        pgtype.Int4        `json:"attempts"`
	CorrectCount    pgtype.Int4        `json:"correct_count"`
	SrsStage        pgtype.Int4        `json:"srs_stage"`
	EaseFactor      pgtype.Float8      `json:"ease_factor"`
	IntervalDays    pgtype.Int4        `json:"interval_days"`
	NextReviewAt    pgtype.Timestamptz `json:"next_review_at"`
	XpEarned        pgtype.Int8        `json:"xp_earned"`
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	MasteredAt      pgtype.Timestamptz `json:"mastered_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type UserGrammarProgress struct {
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	LessonID         pgtype.UUID        `json:"lesson_id"`
	Level            int32              `json:"level"`
	Attempts         pgtype.Int4        `json:"attempts"`
	CorrectCount     pgtype.Int4        `json:"correct_count"`
	XpEarned         pgtype.Int8        `json:"xp_earned"`
	Status           pgtype.Text        `json:"status"`
	ConsecutiveFails pgtype.Int4        `json:"consecutive_fails"`
	SrsStage         pgtype.Int4        `json:"srs_stage"`
	EaseFactor       pgtype.Float8      `json:"ease_factor"`
	IntervalDays     pgtype.Int4        `json:"interval_days"`
	NextReviewAt     pgtype.Timestamptz `json:"next_review_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserLevelProgress struct {
	ID                pgtype.UUID        `json:"id"`
	UserID            pgtype.UUID        `json:"user_id"`
	LanguageID        string             `json:"language_id"`
	TotalXp           pgtype.Int8        `json:"total_xp"`
	CurrentLevel      pgtype.Int4        `json:"current_level"`
	XpForCurrentLevel pgtype.Int8        `json:"xp_for_current_level"`
	XpForNextLevel    pgtype.Int8        `json:"xp_for_next_level"`
	RetentionScore    pgtype.Float8      `json:"retention_score"`
	AccuracyScore     pgtype.Float8      `json:"accuracy_score"`
	ProficiencyScore  pgtype.Float8      `json:"proficiency_score"`
	CurrentStreak     pgtype.Int4        `json:"current_streak"`
	LongestStreak     pgtype.Int4        `json:"longest_streak"`
	LastActivityAt    pgtype.Timestamptz `json:"last_activity_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type UserVocabularyReview struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	VocabularyID   pgtype.UUID        `json:"vocabulary_id"`
	SrsStage       pgtype.Int4        `json:"srs_stage"`
	EaseFactor     pgtype.Float8      `json:"ease_factor"`
	IntervalDays   pgtype.Int4        `json:"interval_days"`
	NextReviewAt   pgtype.Timestamptz `json:"next_review_at"`
	LastReviewedAt pgtype.Timestamptz `json:"last_reviewed_at"`
}

type Vocabulary struct {
	ID         pgtype.UUID        `json:"id"`
	LanguageID string             `json:"language_id"`
	Term       string             `json:"term"`
	Phonetic   pgtype.Text        `json:"phonetic"`
	Meaning    string             `json:"meaning"`
	Example    pgtype.Text        `json:"example"`
	Topic      pgtype.Text        `json:"topic"`
	Level      pgtype.Text        `json:"level"`
	AudioUrl   pgtype.Text        `json:"audio_url"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type VocabularyExercise struct {
	ID              pgtype.UUID        `json:"id"`
	VocabularyID    pgtype.UUID        `json:"vocabulary_id"`
	ExerciseType    string             `json:"exercise_type"`
	Question        string             `json:"question"`
	Options         []byte             `json:"options"`
	CorrectAnswer   string             `json:"correct_answer"`
	DistractorCount pgtype.Int4        `json:"distractor_count"`
	Difficulty      pgtype.Int4        `json:"difficulty"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}
