// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// level truyền từ Go (leveling.LevelForExp) sau khi đã cộng exp — tránh phải
	// tính lại công thức level trong SQL.
	AddUserRewards(ctx context.Context, arg AddUserRewardsParams) (User, error)
	AddVocabularyToDeck(ctx context.Context, arg AddVocabularyToDeckParams) (int64, error)
	BanGameParticipant(ctx context.Context, arg BanGameParticipantParams) error
	CompleteExerciseSession(ctx context.Context, arg CompleteExerciseSessionParams) (ExerciseSession, error)
	CreateDeck(ctx context.Context, arg CreateDeckParams) (UserDeck, error)
	CreateExerciseSession(ctx context.Context, arg CreateExerciseSessionParams) (ExerciseSession, error)
	CreateGameRoom(ctx context.Context, arg CreateGameRoomParams) (GameRoom, error)
	CreateMission(ctx context.Context, arg CreateMissionParams) (Mission, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateVocabularyExercise(ctx context.Context, arg CreateVocabularyExerciseParams) (VocabularyExercise, error)
	CreateVocabularyReviewIfAbsent(ctx context.Context, arg CreateVocabularyReviewIfAbsentParams) (int64, error)
	// Xoá mềm — giữ lại user_mission_progress đã có (không mất lịch sử/FK).
	DeactivateMission(ctx context.Context, id pgtype.UUID) error
	DeleteDeck(ctx context.Context, arg DeleteDeckParams) (int64, error)
	DeleteGameParticipant(ctx context.Context, arg DeleteGameParticipantParams) error
	FinishGameRoom(ctx context.Context, id pgtype.UUID) (GameRoom, error)
	GetActiveExerciseTypes(ctx context.Context) ([]ExerciseType, error)
	GetDeck(ctx context.Context, arg GetDeckParams) (UserDeck, error)
	GetDeckSessionStats(ctx context.Context, deckID pgtype.UUID) (GetDeckSessionStatsRow, error)
	GetDeckVocabularies(ctx context.Context, deckID pgtype.UUID) ([]Vocabulary, error)
	GetDialogueById(ctx context.Context, id pgtype.UUID) (GetDialogueByIdRow, error)
	GetDialoguesByLesson(ctx context.Context, lessonID pgtype.UUID) ([]GetDialoguesByLessonRow, error)
	// language_id để NULL thì lấy đến hạn ở MỌI ngôn ngữ user đang học (hành vi cũ) —
	// truyền vào khi muốn ôn tập đến hạn chỉ riêng 1 ngôn ngữ.
	GetDueVocabulariesForUser(ctx context.Context, arg GetDueVocabulariesForUserParams) ([]GetDueVocabulariesForUserRow, error)
	GetExerciseByTypeForVocabularies(ctx context.Context, arg GetExerciseByTypeForVocabulariesParams) ([]GetExerciseByTypeForVocabulariesRow, error)
	GetExerciseSession(ctx context.Context, id pgtype.UUID) (ExerciseSession, error)
	GetExerciseType(ctx context.Context, id string) (ExerciseType, error)
	GetGameParticipantByUser(ctx context.Context, arg GetGameParticipantByUserParams) (GameParticipant, error)
	GetGameRoomByCode(ctx context.Context, code string) (GameRoom, error)
	GetGameRoomByID(ctx context.Context, id pgtype.UUID) (GameRoom, error)
	GetGrammarExerciseByID(ctx context.Context, id pgtype.UUID) (GrammarExercise, error)
	GetGrammarLessonByCode(ctx context.Context, code string) (GrammarLesson, error)
	GetGrammarProgress(ctx context.Context, arg GetGrammarProgressParams) (UserGrammarProgress, error)
	GetLanguageByID(ctx context.Context, id string) (Language, error)
	GetLeaderboard(ctx context.Context, roomID pgtype.UUID) ([]GetLeaderboardRow, error)
	GetLessonProgressAllLevels(ctx context.Context, arg GetLessonProgressAllLevelsParams) ([]UserGrammarProgress, error)
	GetMissionByID(ctx context.Context, id pgtype.UUID) (Mission, error)
	GetNextAvailableLevel(ctx context.Context, arg GetNextAvailableLevelParams) (int32, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByIdentifier(ctx context.Context, email string) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserExerciseProgress(ctx context.Context, arg GetUserExerciseProgressParams) (UserExerciseProgress, error)
	GetUserExerciseProgressForDeck(ctx context.Context, arg GetUserExerciseProgressForDeckParams) ([]GetUserExerciseProgressForDeckRow, error)
	GetUserExerciseSessions(ctx context.Context, arg GetUserExerciseSessionsParams) ([]ExerciseSession, error)
	GetUserLevelProgress(ctx context.Context, arg GetUserLevelProgressParams) (UserLevelProgress, error)
	GetVocabularyExercise(ctx context.Context, arg GetVocabularyExerciseParams) (VocabularyExercise, error)
	GetVocabularyReview(ctx context.Context, arg GetVocabularyReviewParams) (UserVocabularyReview, error)
	InsertGameRoomQuestion(ctx context.Context, arg InsertGameRoomQuestionParams) error
	IsGameRoomBanned(ctx context.Context, arg IsGameRoomBannedParams) (bool, error)
	// Atomic: kiểm tra phòng còn "waiting" + chưa đủ người + chưa bị ban trong
	// CÙNG 1 statement với insert, để tránh race khi 2 người join đúng slot cuối
	// cùng lúc.
	JoinGameRoom(ctx context.Context, arg JoinGameRoomParams) (GameParticipant, error)
	// Nhiệm vụ event chỉ tính khi NOW() đang trong khoảng starts_at..ends_at.
	ListActiveMissionsByAction(ctx context.Context, actionType string) ([]Mission, error)
	// Dành cho admin — thấy cả nhiệm vụ đã tắt (is_active=false) để còn bật lại.
	ListAllMissions(ctx context.Context) ([]Mission, error)
	ListGameParticipants(ctx context.Context, roomID pgtype.UUID) ([]ListGameParticipantsRow, error)
	ListGameRoomQuestions(ctx context.Context, roomID pgtype.UUID) ([]ListGameRoomQuestionsRow, error)
	ListGrammarExercisesByLesson(ctx context.Context, lessonID pgtype.UUID) ([]GrammarExercise, error)
	ListGrammarLessonsByLanguage(ctx context.Context, languageID string) ([]ListGrammarLessonsByLanguageRow, error)
	ListGrammarTopicsByLanguage(ctx context.Context, languageID string) ([]GrammarTopic, error)
	ListLanguages(ctx context.Context) ([]Language, error)
	// period_key tính theo CÙNG quy tắc với Go (mission_service.periodKey) —
	// daily=YYYY-MM-DD, weekly=IYYY-"W"IW (ISO week), monthly=YYYY-MM, event=mission id.
	ListMissionsWithProgress(ctx context.Context, userID pgtype.UUID) ([]ListMissionsWithProgressRow, error)
	ListNewVocabulariesForUser(ctx context.Context, arg ListNewVocabulariesForUserParams) ([]Vocabulary, error)
	ListUserDecks(ctx context.Context, userID pgtype.UUID) ([]UserDeck, error)
	ListUsers(ctx context.Context) ([]User, error)
	ListUsersByLevel(ctx context.Context, limit int32) ([]User, error)
	ListUsersByPoints(ctx context.Context, limit int32) ([]User, error)
	ListUsersByStreak(ctx context.Context, limit int32) ([]User, error)
	MarkExerciseMastered(ctx context.Context, arg MarkExerciseMasteredParams) (UserExerciseProgress, error)
	// WHERE completed_at IS NULL đảm bảo chỉ 1 lần cộng thưởng dù gọi nhiều lần
	// (ví dụ race giữa 2 request) — gọi lần 2 trả 0 dòng (pgx.ErrNoRows).
	MarkMissionProgressCompleted(ctx context.Context, id pgtype.UUID) (UserMissionProgress, error)
	PickRandomQuestions(ctx context.Context, arg PickRandomQuestionsParams) ([]ChallengeQuestion, error)
	RemoveVocabularyFromDeck(ctx context.Context, arg RemoveVocabularyFromDeckParams) (int64, error)
	StartGameRoom(ctx context.Context, id pgtype.UUID) (GameRoom, error)
	// Atomic: insert câu trả lời + cộng điểm participant trong 1 statement (CTE),
	// tránh cần transaction Go riêng. Nếu đã trả lời câu này rồi (ON CONFLICT DO
	// NOTHING) thì không có row nào -> pgx.ErrNoRows ở phía Go.
	SubmitGameAnswer(ctx context.Context, arg SubmitGameAnswerParams) (SubmitGameAnswerRow, error)
	UnbanGameParticipant(ctx context.Context, arg UnbanGameParticipantParams) error
	UpdateDeck(ctx context.Context, arg UpdateDeckParams) (UserDeck, error)
	UpdateMission(ctx context.Context, arg UpdateMissionParams) (Mission, error)
	UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error)
	UpdateUserStreak(ctx context.Context, arg UpdateUserStreakParams) (UserLevelProgress, error)
	UpsertGrammarProgress(ctx context.Context, arg UpsertGrammarProgressParams) (UserGrammarProgress, error)
	// Atomic: cộng thêm progress_count, trả về dòng sau khi cộng để Go kiểm tra
	// đã đạt target_count hay chưa (chống race khi 2 request cùng lúc).
	UpsertMissionProgress(ctx context.Context, arg UpsertMissionProgressParams) (UserMissionProgress, error)
	UpsertUserExerciseProgress(ctx context.Context, arg UpsertUserExerciseProgressParams) (UserExerciseProgress, error)
	UpsertUserLevelProgress(ctx context.Context, arg UpsertUserLevelProgressParams) (UserLevelProgress, error)
	UpsertVocabularyReview(ctx context.Context, arg UpsertVocabularyReviewParams) (UserVocabularyReview, error)
}

var _ Querier = (*Queries)(nil)
