// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: srs_reviews.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVocabularyReviewIfAbsent = `-- name: CreateVocabularyReviewIfAbsent :execrows
INSERT INTO user_vocabulary_reviews (
    user_id, vocabulary_id, srs_stage, ease_factor, interval_days, next_review_at
) VALUES ($1, $2, 0, 2.5, 0, NOW())
ON CONFLICT (user_id, vocabulary_id) DO NOTHING
`

type CreateVocabularyReviewIfAbsentParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) CreateVocabularyReviewIfAbsent(ctx context.Context, arg CreateVocabularyReviewIfAbsentParams) (int64, error) {
	result, err := q.db.Exec(ctx, createVocabularyReviewIfAbsent, arg.UserID, arg.VocabularyID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getDueVocabulariesForUser = `-- name: GetDueVocabulariesForUser :many
SELECT 
    v.id AS vocabulary_id,
    v.term,
    v.phonetic,
    v.meaning,
    v.audio_url,
    r.id AS review_id,
    r.srs_stage,
    r.ease_factor,
    r.interval_days,
    r.next_review_at
FROM user_vocabulary_reviews r
JOIN vocabularies v ON r.vocabulary_id = v.id
WHERE r.user_id = $1 
  AND r.next_review_at <= NOW()
ORDER BY r.next_review_at ASC
LIMIT $2
`

type GetDueVocabulariesForUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
}

type GetDueVocabulariesForUserRow struct {
	VocabularyID pgtype.UUID        `json:"vocabulary_id"`
	Term         string             `json:"term"`
	Phonetic     pgtype.Text        `json:"phonetic"`
	Meaning      string             `json:"meaning"`
	AudioUrl     pgtype.Text        `json:"audio_url"`
	ReviewID     pgtype.UUID        `json:"review_id"`
	SrsStage     pgtype.Int4        `json:"srs_stage"`
	EaseFactor   pgtype.Float8      `json:"ease_factor"`
	IntervalDays pgtype.Int4        `json:"interval_days"`
	NextReviewAt pgtype.Timestamptz `json:"next_review_at"`
}

func (q *Queries) GetDueVocabulariesForUser(ctx context.Context, arg GetDueVocabulariesForUserParams) ([]GetDueVocabulariesForUserRow, error) {
	rows, err := q.db.Query(ctx, getDueVocabulariesForUser, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDueVocabulariesForUserRow
	for rows.Next() {
		var i GetDueVocabulariesForUserRow
		if err := rows.Scan(
			&i.VocabularyID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.AudioUrl,
			&i.ReviewID,
			&i.SrsStage,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.NextReviewAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVocabularyReview = `-- name: GetVocabularyReview :one
SELECT id, user_id, vocabulary_id, srs_stage, ease_factor, interval_days, next_review_at, last_reviewed_at FROM user_vocabulary_reviews
WHERE user_id = $1 AND vocabulary_id = $2
`

type GetVocabularyReviewParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) GetVocabularyReview(ctx context.Context, arg GetVocabularyReviewParams) (UserVocabularyReview, error) {
	row := q.db.QueryRow(ctx, getVocabularyReview, arg.UserID, arg.VocabularyID)
	var i UserVocabularyReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VocabularyID,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.LastReviewedAt,
	)
	return i, err
}

const listNewVocabulariesForUser = `-- name: ListNewVocabulariesForUser :many
SELECT v.id, v.language_id, v.term, v.phonetic, v.meaning, v.example, v.topic, v.level, v.audio_url, v.image_url, v.created_at
FROM vocabularies v
WHERE v.language_id = $1
  AND NOT EXISTS (
    SELECT 1 FROM user_vocabulary_reviews r
    WHERE r.user_id = $2 AND r.vocabulary_id = v.id
  )
ORDER BY v.topic, v.term
LIMIT $3
`

type ListNewVocabulariesForUserParams struct {
	LanguageID string      `json:"language_id"`
	UserID     pgtype.UUID `json:"user_id"`
	Limit      int32       `json:"limit"`
}

func (q *Queries) ListNewVocabulariesForUser(ctx context.Context, arg ListNewVocabulariesForUserParams) ([]Vocabulary, error) {
	rows, err := q.db.Query(ctx, listNewVocabulariesForUser, arg.LanguageID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Vocabulary
	for rows.Next() {
		var i Vocabulary
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVocabularyReview = `-- name: UpsertVocabularyReview :one
INSERT INTO user_vocabulary_reviews (
    user_id, vocabulary_id, srs_stage, ease_factor, interval_days, next_review_at, last_reviewed_at
) VALUES (
    $1, $2, $3, $4, $5, $6, NOW()
)
ON CONFLICT (user_id, vocabulary_id) 
DO UPDATE SET
    srs_stage = EXCLUDED.srs_stage,
    ease_factor = EXCLUDED.ease_factor,
    interval_days = EXCLUDED.interval_days,
    next_review_at = EXCLUDED.next_review_at,
    last_reviewed_at = NOW()
RETURNING id, user_id, vocabulary_id, srs_stage, ease_factor, interval_days, next_review_at, last_reviewed_at
`

type UpsertVocabularyReviewParams struct {
	UserID       pgtype.UUID        `json:"user_id"`
	VocabularyID pgtype.UUID        `json:"vocabulary_id"`
	SrsStage     pgtype.Int4        `json:"srs_stage"`
	EaseFactor   pgtype.Float8      `json:"ease_factor"`
	IntervalDays pgtype.Int4        `json:"interval_days"`
	NextReviewAt pgtype.Timestamptz `json:"next_review_at"`
}

func (q *Queries) UpsertVocabularyReview(ctx context.Context, arg UpsertVocabularyReviewParams) (UserVocabularyReview, error) {
	row := q.db.QueryRow(ctx, upsertVocabularyReview,
		arg.UserID,
		arg.VocabularyID,
		arg.SrsStage,
		arg.EaseFactor,
		arg.IntervalDays,
		arg.NextReviewAt,
	)
	var i UserVocabularyReview
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VocabularyID,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.LastReviewedAt,
	)
	return i, err
}
