// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_level_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserLevelProgress = `-- name: GetUserLevelProgress :one
SELECT id, user_id, language_id, total_xp, current_level, xp_for_current_level, xp_for_next_level, retention_score, accuracy_score, proficiency_score, current_streak, longest_streak, last_activity_at, created_at, updated_at FROM user_level_progress
WHERE user_id = $1 AND language_id = $2
`

type GetUserLevelProgressParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
}

func (q *Queries) GetUserLevelProgress(ctx context.Context, arg GetUserLevelProgressParams) (UserLevelProgress, error) {
	row := q.db.QueryRow(ctx, getUserLevelProgress, arg.UserID, arg.LanguageID)
	var i UserLevelProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LanguageID,
		&i.TotalXp,
		&i.CurrentLevel,
		&i.XpForCurrentLevel,
		&i.XpForNextLevel,
		&i.RetentionScore,
		&i.AccuracyScore,
		&i.ProficiencyScore,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStreak = `-- name: UpdateUserStreak :one
UPDATE user_level_progress
SET current_streak = $3,
    longest_streak = GREATEST(longest_streak, $3),
    last_activity_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1 AND language_id = $2
RETURNING id, user_id, language_id, total_xp, current_level, xp_for_current_level, xp_for_next_level, retention_score, accuracy_score, proficiency_score, current_streak, longest_streak, last_activity_at, created_at, updated_at
`

type UpdateUserStreakParams struct {
	UserID        pgtype.UUID `json:"user_id"`
	LanguageID    string      `json:"language_id"`
	CurrentStreak pgtype.Int4 `json:"current_streak"`
}

func (q *Queries) UpdateUserStreak(ctx context.Context, arg UpdateUserStreakParams) (UserLevelProgress, error) {
	row := q.db.QueryRow(ctx, updateUserStreak, arg.UserID, arg.LanguageID, arg.CurrentStreak)
	var i UserLevelProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LanguageID,
		&i.TotalXp,
		&i.CurrentLevel,
		&i.XpForCurrentLevel,
		&i.XpForNextLevel,
		&i.RetentionScore,
		&i.AccuracyScore,
		&i.ProficiencyScore,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserLevelProgress = `-- name: UpsertUserLevelProgress :one
INSERT INTO user_level_progress (user_id, language_id, total_xp, current_level, xp_for_current_level, xp_for_next_level, retention_score, accuracy_score, proficiency_score)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (user_id, language_id)
DO UPDATE SET
    total_xp = EXCLUDED.total_xp,
    current_level = EXCLUDED.current_level,
    xp_for_current_level = EXCLUDED.xp_for_current_level,
    xp_for_next_level = EXCLUDED.xp_for_next_level,
    retention_score = EXCLUDED.retention_score,
    accuracy_score = EXCLUDED.accuracy_score,
    proficiency_score = EXCLUDED.proficiency_score,
    last_activity_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, language_id, total_xp, current_level, xp_for_current_level, xp_for_next_level, retention_score, accuracy_score, proficiency_score, current_streak, longest_streak, last_activity_at, created_at, updated_at
`

type UpsertUserLevelProgressParams struct {
	UserID            pgtype.UUID   `json:"user_id"`
	LanguageID        string        `json:"language_id"`
	TotalXp           pgtype.Int8   `json:"total_xp"`
	CurrentLevel      pgtype.Int4   `json:"current_level"`
	XpForCurrentLevel pgtype.Int8   `json:"xp_for_current_level"`
	XpForNextLevel    pgtype.Int8   `json:"xp_for_next_level"`
	RetentionScore    pgtype.Float8 `json:"retention_score"`
	AccuracyScore     pgtype.Float8 `json:"accuracy_score"`
	ProficiencyScore  pgtype.Float8 `json:"proficiency_score"`
}

func (q *Queries) UpsertUserLevelProgress(ctx context.Context, arg UpsertUserLevelProgressParams) (UserLevelProgress, error) {
	row := q.db.QueryRow(ctx, upsertUserLevelProgress,
		arg.UserID,
		arg.LanguageID,
		arg.TotalXp,
		arg.CurrentLevel,
		arg.XpForCurrentLevel,
		arg.XpForNextLevel,
		arg.RetentionScore,
		arg.AccuracyScore,
		arg.ProficiencyScore,
	)
	var i UserLevelProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LanguageID,
		&i.TotalXp,
		&i.CurrentLevel,
		&i.XpForCurrentLevel,
		&i.XpForNextLevel,
		&i.RetentionScore,
		&i.AccuracyScore,
		&i.ProficiencyScore,
		&i.CurrentStreak,
		&i.LongestStreak,
		&i.LastActivityAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
