// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addUserRewards = `-- name: AddUserRewards :one
UPDATE users
SET exp = exp + $1,
    points = points + $2,
    level = $3,
    updated_at = NOW()
WHERE id = $4
RETURNING id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at
`

type AddUserRewardsParams struct {
	ExpDelta    int64       `json:"exp_delta"`
	PointsDelta int64       `json:"points_delta"`
	Level       int32       `json:"level"`
	ID          pgtype.UUID `json:"id"`
}

// level truyền từ Go (leveling.LevelForExp) sau khi đã cộng exp — tránh phải
// tính lại công thức level trong SQL.
func (q *Queries) AddUserRewards(ctx context.Context, arg AddUserRewardsParams) (User, error) {
	row := q.db.QueryRow(ctx, addUserRewards,
		arg.ExpDelta,
		arg.PointsDelta,
		arg.Level,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, username, password_hash, full_name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at
`

type CreateUserParams struct {
	Email        string      `json:"email"`
	Username     string      `json:"username"`
	PasswordHash string      `json:"password_hash"`
	FullName     pgtype.Text `json:"full_name"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.PasswordHash,
		arg.FullName,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByIdentifier = `-- name: GetUserByIdentifier :one
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at FROM users
WHERE email = $1 OR username = $1
`

func (q *Queries) GetUserByIdentifier(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByIdentifier, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at FROM users
WHERE username = $1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at FROM users
ORDER BY created_at DESC
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.StreakCount,
			&i.Role,
			&i.AdminModules,
			&i.IsActive,
			&i.Exp,
			&i.Level,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersAdminPaged = `-- name: ListUsersAdminPaged :many
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at, COUNT(*) OVER() AS total_count FROM users
WHERE ($1::text IS NULL
    OR username ILIKE '%' || $1::text || '%'
    OR email ILIKE '%' || $1::text || '%'
    OR full_name ILIKE '%' || $1::text || '%')
  AND ($2::text IS NULL OR role = $2::text)
  AND ($3::text IS NULL OR $3::text = ANY(admin_modules))
ORDER BY (role = 'owner') DESC, created_at DESC
LIMIT $5 OFFSET $4
`

type ListUsersAdminPagedParams struct {
	Search pgtype.Text `json:"search"`
	Role   pgtype.Text `json:"role"`
	Module pgtype.Text `json:"module"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

type ListUsersAdminPagedRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	StreakCount  pgtype.Int4        `json:"streak_count"`
	Role         string             `json:"role"`
	AdminModules []string           `json:"admin_modules"`
	IsActive     bool               `json:"is_active"`
	Exp          int64              `json:"exp"`
	Level        int32              `json:"level"`
	Points       int64              `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

// Quản lý học viên (admin) — search theo username/email/full_name, lọc theo
// role và/hoặc theo module đã được cấp quyền (admin_modules chứa module đó).
// Owner luôn nổi lên đầu (role='owner' DESC) — chỉ có 1-vài tài khoản owner
// nên không ảnh hưởng phân trang của phần còn lại.
func (q *Queries) ListUsersAdminPaged(ctx context.Context, arg ListUsersAdminPagedParams) ([]ListUsersAdminPagedRow, error) {
	rows, err := q.db.Query(ctx, listUsersAdminPaged,
		arg.Search,
		arg.Role,
		arg.Module,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersAdminPagedRow
	for rows.Next() {
		var i ListUsersAdminPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.StreakCount,
			&i.Role,
			&i.AdminModules,
			&i.IsActive,
			&i.Exp,
			&i.Level,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByLevel = `-- name: ListUsersByLevel :many
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at, COUNT(*) OVER() AS total_count FROM users
WHERE is_active
  AND ($1::text IS NULL
    OR username ILIKE '%' || $1::text || '%'
    OR full_name ILIKE '%' || $1::text || '%')
ORDER BY level DESC, exp DESC
LIMIT $3 OFFSET $2
`

type ListUsersByLevelParams struct {
	Search pgtype.Text `json:"search"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

type ListUsersByLevelRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	StreakCount  pgtype.Int4        `json:"streak_count"`
	Role         string             `json:"role"`
	AdminModules []string           `json:"admin_modules"`
	IsActive     bool               `json:"is_active"`
	Exp          int64              `json:"exp"`
	Level        int32              `json:"level"`
	Points       int64              `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) ListUsersByLevel(ctx context.Context, arg ListUsersByLevelParams) ([]ListUsersByLevelRow, error) {
	rows, err := q.db.Query(ctx, listUsersByLevel, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByLevelRow
	for rows.Next() {
		var i ListUsersByLevelRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.StreakCount,
			&i.Role,
			&i.AdminModules,
			&i.IsActive,
			&i.Exp,
			&i.Level,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByPoints = `-- name: ListUsersByPoints :many
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at, COUNT(*) OVER() AS total_count FROM users
WHERE is_active
  AND ($1::text IS NULL
    OR username ILIKE '%' || $1::text || '%'
    OR full_name ILIKE '%' || $1::text || '%')
ORDER BY points DESC
LIMIT $3 OFFSET $2
`

type ListUsersByPointsParams struct {
	Search pgtype.Text `json:"search"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

type ListUsersByPointsRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	StreakCount  pgtype.Int4        `json:"streak_count"`
	Role         string             `json:"role"`
	AdminModules []string           `json:"admin_modules"`
	IsActive     bool               `json:"is_active"`
	Exp          int64              `json:"exp"`
	Level        int32              `json:"level"`
	Points       int64              `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

func (q *Queries) ListUsersByPoints(ctx context.Context, arg ListUsersByPointsParams) ([]ListUsersByPointsRow, error) {
	rows, err := q.db.Query(ctx, listUsersByPoints, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByPointsRow
	for rows.Next() {
		var i ListUsersByPointsRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.StreakCount,
			&i.Role,
			&i.AdminModules,
			&i.IsActive,
			&i.Exp,
			&i.Level,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByStreak = `-- name: ListUsersByStreak :many
SELECT id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at, COUNT(*) OVER() AS total_count FROM users
WHERE is_active
  AND ($1::text IS NULL
    OR username ILIKE '%' || $1::text || '%'
    OR full_name ILIKE '%' || $1::text || '%')
ORDER BY streak_count DESC NULLS LAST, created_at
LIMIT $3 OFFSET $2
`

type ListUsersByStreakParams struct {
	Search pgtype.Text `json:"search"`
	Offset int32       `json:"offset"`
	Limit  int32       `json:"limit"`
}

type ListUsersByStreakRow struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	Username     string             `json:"username"`
	PasswordHash string             `json:"password_hash"`
	FullName     pgtype.Text        `json:"full_name"`
	AvatarUrl    pgtype.Text        `json:"avatar_url"`
	StreakCount  pgtype.Int4        `json:"streak_count"`
	Role         string             `json:"role"`
	AdminModules []string           `json:"admin_modules"`
	IsActive     bool               `json:"is_active"`
	Exp          int64              `json:"exp"`
	Level        int32              `json:"level"`
	Points       int64              `json:"points"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	TotalCount   int64              `json:"total_count"`
}

// Bảng xếp hạng (public) — ẩn tài khoản bị khoá (is_active=false), search
// theo username/full_name, phân trang qua COUNT(*) OVER() giống ListUsersAdminPaged.
func (q *Queries) ListUsersByStreak(ctx context.Context, arg ListUsersByStreakParams) ([]ListUsersByStreakRow, error) {
	rows, err := q.db.Query(ctx, listUsersByStreak, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersByStreakRow
	for rows.Next() {
		var i ListUsersByStreakRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Username,
			&i.PasswordHash,
			&i.FullName,
			&i.AvatarUrl,
			&i.StreakCount,
			&i.Role,
			&i.AdminModules,
			&i.IsActive,
			&i.Exp,
			&i.Level,
			&i.Points,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserActive = `-- name: UpdateUserActive :one
UPDATE users
SET is_active = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at
`

type UpdateUserActiveParams struct {
	IsActive bool        `json:"is_active"`
	ID       pgtype.UUID `json:"id"`
}

// Vô hiệu hoá/khôi phục tài khoản (owner-only, xem user_service.go) — không
// xoá cứng để giữ lại dữ liệu liên quan, có thể khôi phục bằng is_active=true.
func (q *Queries) UpdateUserActive(ctx context.Context, arg UpdateUserActiveParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserActive, arg.IsActive, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserModules = `-- name: UpdateUserModules :one
UPDATE users
SET admin_modules = $1, updated_at = NOW()
WHERE id = $2
RETURNING id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at
`

type UpdateUserModulesParams struct {
	AdminModules []string    `json:"admin_modules"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserModules(ctx context.Context, arg UpdateUserModulesParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserModules, arg.AdminModules, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET full_name  = COALESCE($1, full_name),
    avatar_url = COALESCE($2, avatar_url),
    updated_at = NOW()
WHERE id = $3
RETURNING id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at
`

type UpdateUserProfileParams struct {
	FullName  pgtype.Text `json:"full_name"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile, arg.FullName, arg.AvatarUrl, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserRole = `-- name: UpdateUserRole :one
UPDATE users
SET role = $1::varchar,
    admin_modules = CASE WHEN $1::varchar = 'user' THEN '{}'::text[] ELSE admin_modules END,
    updated_at = NOW()
WHERE id = $2
RETURNING id, email, username, password_hash, full_name, avatar_url, streak_count, role, admin_modules, is_active, exp, level, points, created_at, updated_at
`

type UpdateUserRoleParams struct {
	Role string      `json:"role"`
	ID   pgtype.UUID `json:"id"`
}

// Hạ role về 'user' thì xoá luôn admin_modules — role='user' không còn ý
// nghĩa giữ module cũ (RequireModule chặn từ role trước khi xét module).
// ::varchar ở cả 2 chỗ dùng $1 — Postgres cần suy ra CÙNG 1 kiểu cho 1 param
// qua extended query protocol, không cast sẽ lỗi 42P08 "inconsistent types".
func (q *Queries) UpdateUserRole(ctx context.Context, arg UpdateUserRoleParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserRole, arg.Role, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Username,
		&i.PasswordHash,
		&i.FullName,
		&i.AvatarUrl,
		&i.StreakCount,
		&i.Role,
		&i.AdminModules,
		&i.IsActive,
		&i.Exp,
		&i.Level,
		&i.Points,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
