// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_grammar_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getGrammarProgress = `-- name: GetGrammarProgress :one
SELECT id, user_id, lesson_id, level, attempts, correct_count, xp_earned, status, consecutive_fails, srs_stage, ease_factor, interval_days, next_review_at, created_at, updated_at FROM user_grammar_progress
WHERE user_id = $1 AND lesson_id = $2 AND level = $3
`

type GetGrammarProgressParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LessonID pgtype.UUID `json:"lesson_id"`
	Level    int32       `json:"level"`
}

func (q *Queries) GetGrammarProgress(ctx context.Context, arg GetGrammarProgressParams) (UserGrammarProgress, error) {
	row := q.db.QueryRow(ctx, getGrammarProgress, arg.UserID, arg.LessonID, arg.Level)
	var i UserGrammarProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonID,
		&i.Level,
		&i.Attempts,
		&i.CorrectCount,
		&i.XpEarned,
		&i.Status,
		&i.ConsecutiveFails,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getLessonProgressAllLevels = `-- name: GetLessonProgressAllLevels :many
SELECT id, user_id, lesson_id, level, attempts, correct_count, xp_earned, status, consecutive_fails, srs_stage, ease_factor, interval_days, next_review_at, created_at, updated_at FROM user_grammar_progress
WHERE user_id = $1 AND lesson_id = $2
ORDER BY level
`

type GetLessonProgressAllLevelsParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LessonID pgtype.UUID `json:"lesson_id"`
}

func (q *Queries) GetLessonProgressAllLevels(ctx context.Context, arg GetLessonProgressAllLevelsParams) ([]UserGrammarProgress, error) {
	rows, err := q.db.Query(ctx, getLessonProgressAllLevels, arg.UserID, arg.LessonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserGrammarProgress
	for rows.Next() {
		var i UserGrammarProgress
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.LessonID,
			&i.Level,
			&i.Attempts,
			&i.CorrectCount,
			&i.XpEarned,
			&i.Status,
			&i.ConsecutiveFails,
			&i.SrsStage,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.NextReviewAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextAvailableLevel = `-- name: GetNextAvailableLevel :one
SELECT COALESCE(MAX(level), 0) + 1 as next_level
FROM user_grammar_progress
WHERE user_id = $1 AND lesson_id = $2 AND status = 'passed'
`

type GetNextAvailableLevelParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	LessonID pgtype.UUID `json:"lesson_id"`
}

func (q *Queries) GetNextAvailableLevel(ctx context.Context, arg GetNextAvailableLevelParams) (int32, error) {
	row := q.db.QueryRow(ctx, getNextAvailableLevel, arg.UserID, arg.LessonID)
	var next_level int32
	err := row.Scan(&next_level)
	return next_level, err
}

const upsertGrammarProgress = `-- name: UpsertGrammarProgress :one
INSERT INTO user_grammar_progress (user_id, lesson_id, level, attempts, correct_count, xp_earned, status, consecutive_fails)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (user_id, lesson_id, level)
DO UPDATE SET
    attempts = EXCLUDED.attempts,
    correct_count = EXCLUDED.correct_count,
    xp_earned = EXCLUDED.xp_earned,
    status = EXCLUDED.status,
    consecutive_fails = EXCLUDED.consecutive_fails,
    updated_at = NOW()
RETURNING id, user_id, lesson_id, level, attempts, correct_count, xp_earned, status, consecutive_fails, srs_stage, ease_factor, interval_days, next_review_at, created_at, updated_at
`

type UpsertGrammarProgressParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	LessonID         pgtype.UUID `json:"lesson_id"`
	Level            int32       `json:"level"`
	Attempts         pgtype.Int4 `json:"attempts"`
	CorrectCount     pgtype.Int4 `json:"correct_count"`
	XpEarned         pgtype.Int8 `json:"xp_earned"`
	Status           pgtype.Text `json:"status"`
	ConsecutiveFails pgtype.Int4 `json:"consecutive_fails"`
}

func (q *Queries) UpsertGrammarProgress(ctx context.Context, arg UpsertGrammarProgressParams) (UserGrammarProgress, error) {
	row := q.db.QueryRow(ctx, upsertGrammarProgress,
		arg.UserID,
		arg.LessonID,
		arg.Level,
		arg.Attempts,
		arg.CorrectCount,
		arg.XpEarned,
		arg.Status,
		arg.ConsecutiveFails,
	)
	var i UserGrammarProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.LessonID,
		&i.Level,
		&i.Attempts,
		&i.CorrectCount,
		&i.XpEarned,
		&i.Status,
		&i.ConsecutiveFails,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
