// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: user_exercise_progress.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUserExerciseProgress = `-- name: GetUserExerciseProgress :one
SELECT id, user_id, vocabulary_id, exercise_type, status, attempts, correct_count, srs_stage, ease_factor, interval_days, next_review_at, xp_earned, last_attempted_at, mastered_at, created_at, updated_at FROM user_exercise_progress
WHERE user_id = $1 AND vocabulary_id = $2 AND exercise_type = $3
`

type GetUserExerciseProgressParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
	ExerciseType string      `json:"exercise_type"`
}

func (q *Queries) GetUserExerciseProgress(ctx context.Context, arg GetUserExerciseProgressParams) (UserExerciseProgress, error) {
	row := q.db.QueryRow(ctx, getUserExerciseProgress, arg.UserID, arg.VocabularyID, arg.ExerciseType)
	var i UserExerciseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VocabularyID,
		&i.ExerciseType,
		&i.Status,
		&i.Attempts,
		&i.CorrectCount,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.XpEarned,
		&i.LastAttemptedAt,
		&i.MasteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserExerciseProgressForDeck = `-- name: GetUserExerciseProgressForDeck :many
SELECT uep.id, uep.user_id, uep.vocabulary_id, uep.exercise_type, uep.status, uep.attempts, uep.correct_count, uep.srs_stage, uep.ease_factor, uep.interval_days, uep.next_review_at, uep.xp_earned, uep.last_attempted_at, uep.mastered_at, uep.created_at, uep.updated_at, v.term, v.meaning
FROM user_exercise_progress uep
JOIN vocabularies v ON uep.vocabulary_id = v.id
JOIN deck_vocabularies dv ON v.id = dv.vocabulary_id
WHERE uep.user_id = $1 AND dv.deck_id = $2 AND uep.exercise_type = $3
ORDER BY uep.status, uep.last_attempted_at
`

type GetUserExerciseProgressForDeckParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	DeckID       pgtype.UUID `json:"deck_id"`
	ExerciseType string      `json:"exercise_type"`
}

type GetUserExerciseProgressForDeckRow struct {
	ID              pgtype.UUID        `json:"id"`
	UserID          pgtype.UUID        `json:"user_id"`
	VocabularyID    pgtype.UUID        `json:"vocabulary_id"`
	ExerciseType    string             `json:"exercise_type"`
	Status          pgtype.Text        `json:"status"`
	Attempts        pgtype.Int4        `json:"attempts"`
	CorrectCount    pgtype.Int4        `json:"correct_count"`
	SrsStage        pgtype.Int4        `json:"srs_stage"`
	EaseFactor      pgtype.Float8      `json:"ease_factor"`
	IntervalDays    pgtype.Int4        `json:"interval_days"`
	NextReviewAt    pgtype.Timestamptz `json:"next_review_at"`
	XpEarned        pgtype.Int8        `json:"xp_earned"`
	LastAttemptedAt pgtype.Timestamptz `json:"last_attempted_at"`
	MasteredAt      pgtype.Timestamptz `json:"mastered_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	Term            string             `json:"term"`
	Meaning         string             `json:"meaning"`
}

func (q *Queries) GetUserExerciseProgressForDeck(ctx context.Context, arg GetUserExerciseProgressForDeckParams) ([]GetUserExerciseProgressForDeckRow, error) {
	rows, err := q.db.Query(ctx, getUserExerciseProgressForDeck, arg.UserID, arg.DeckID, arg.ExerciseType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserExerciseProgressForDeckRow
	for rows.Next() {
		var i GetUserExerciseProgressForDeckRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.VocabularyID,
			&i.ExerciseType,
			&i.Status,
			&i.Attempts,
			&i.CorrectCount,
			&i.SrsStage,
			&i.EaseFactor,
			&i.IntervalDays,
			&i.NextReviewAt,
			&i.XpEarned,
			&i.LastAttemptedAt,
			&i.MasteredAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Term,
			&i.Meaning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExerciseMastered = `-- name: MarkExerciseMastered :one
UPDATE user_exercise_progress
SET status = 'mastered',
    mastered_at = NOW(),
    updated_at = NOW()
WHERE user_id = $1 AND vocabulary_id = $2 AND exercise_type = $3
RETURNING id, user_id, vocabulary_id, exercise_type, status, attempts, correct_count, srs_stage, ease_factor, interval_days, next_review_at, xp_earned, last_attempted_at, mastered_at, created_at, updated_at
`

type MarkExerciseMasteredParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
	ExerciseType string      `json:"exercise_type"`
}

func (q *Queries) MarkExerciseMastered(ctx context.Context, arg MarkExerciseMasteredParams) (UserExerciseProgress, error) {
	row := q.db.QueryRow(ctx, markExerciseMastered, arg.UserID, arg.VocabularyID, arg.ExerciseType)
	var i UserExerciseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VocabularyID,
		&i.ExerciseType,
		&i.Status,
		&i.Attempts,
		&i.CorrectCount,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.XpEarned,
		&i.LastAttemptedAt,
		&i.MasteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUserExerciseProgress = `-- name: UpsertUserExerciseProgress :one
INSERT INTO user_exercise_progress (user_id, vocabulary_id, exercise_type, status, attempts, correct_count, xp_earned, last_attempted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NOW())
ON CONFLICT (user_id, vocabulary_id, exercise_type)
DO UPDATE SET
    status = EXCLUDED.status,
    attempts = EXCLUDED.attempts,
    correct_count = EXCLUDED.correct_count,
    xp_earned = EXCLUDED.xp_earned,
    last_attempted_at = NOW(),
    updated_at = NOW()
RETURNING id, user_id, vocabulary_id, exercise_type, status, attempts, correct_count, srs_stage, ease_factor, interval_days, next_review_at, xp_earned, last_attempted_at, mastered_at, created_at, updated_at
`

type UpsertUserExerciseProgressParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
	ExerciseType string      `json:"exercise_type"`
	Status       pgtype.Text `json:"status"`
	Attempts     pgtype.Int4 `json:"attempts"`
	CorrectCount pgtype.Int4 `json:"correct_count"`
	XpEarned     pgtype.Int8 `json:"xp_earned"`
}

func (q *Queries) UpsertUserExerciseProgress(ctx context.Context, arg UpsertUserExerciseProgressParams) (UserExerciseProgress, error) {
	row := q.db.QueryRow(ctx, upsertUserExerciseProgress,
		arg.UserID,
		arg.VocabularyID,
		arg.ExerciseType,
		arg.Status,
		arg.Attempts,
		arg.CorrectCount,
		arg.XpEarned,
	)
	var i UserExerciseProgress
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.VocabularyID,
		&i.ExerciseType,
		&i.Status,
		&i.Attempts,
		&i.CorrectCount,
		&i.SrsStage,
		&i.EaseFactor,
		&i.IntervalDays,
		&i.NextReviewAt,
		&i.XpEarned,
		&i.LastAttemptedAt,
		&i.MasteredAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
