// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVocabularyLikes = `-- name: CountVocabularyLikes :one
SELECT COUNT(*)::int FROM vocabulary_likes WHERE vocabulary_id = $1
`

func (q *Queries) CountVocabularyLikes(ctx context.Context, vocabularyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countVocabularyLikes, vocabularyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countVocabularyTopicChildren = `-- name: CountVocabularyTopicChildren :one
SELECT COUNT(*) FROM vocabulary_topics WHERE language_id = $1 AND parent_name = $2
`

type CountVocabularyTopicChildrenParams struct {
	LanguageID string      `json:"language_id"`
	ParentName pgtype.Text `json:"parent_name"`
}

func (q *Queries) CountVocabularyTopicChildren(ctx context.Context, arg CountVocabularyTopicChildrenParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVocabularyTopicChildren, arg.LanguageID, arg.ParentName)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createVocabulary = `-- name: CreateVocabulary :one

INSERT INTO vocabularies (language_id, term, phonetic, meaning, example, topic, level, audio_url, image_url, image_emoji)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, language_id, term, phonetic, meaning, example, topic, level, audio_url, image_url, image_emoji, created_at
`

type CreateVocabularyParams struct {
	LanguageID string      `json:"language_id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	ImageUrl   pgtype.Text `json:"image_url"`
	ImageEmoji pgtype.Text `json:"image_emoji"`
}

// ===== Admin CRUD (quản lý nội dung từ vựng) =====
func (q *Queries) CreateVocabulary(ctx context.Context, arg CreateVocabularyParams) (Vocabulary, error) {
	row := q.db.QueryRow(ctx, createVocabulary,
		arg.LanguageID,
		arg.Term,
		arg.Phonetic,
		arg.Meaning,
		arg.Example,
		arg.Topic,
		arg.Level,
		arg.AudioUrl,
		arg.ImageUrl,
		arg.ImageEmoji,
	)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.Term,
		&i.Phonetic,
		&i.Meaning,
		&i.Example,
		&i.Topic,
		&i.Level,
		&i.AudioUrl,
		&i.ImageUrl,
		&i.ImageEmoji,
		&i.CreatedAt,
	)
	return i, err
}

const createVocabularyTopic = `-- name: CreateVocabularyTopic :one
INSERT INTO vocabulary_topics (language_id, name, icon, order_index, parent_name)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (language_id, name) DO UPDATE SET icon = EXCLUDED.icon, order_index = EXCLUDED.order_index, parent_name = EXCLUDED.parent_name
RETURNING language_id, name, icon, order_index, parent_name
`

type CreateVocabularyTopicParams struct {
	LanguageID string      `json:"language_id"`
	Name       string      `json:"name"`
	Icon       string      `json:"icon"`
	OrderIndex int32       `json:"order_index"`
	ParentName pgtype.Text `json:"parent_name"`
}

func (q *Queries) CreateVocabularyTopic(ctx context.Context, arg CreateVocabularyTopicParams) (VocabularyTopic, error) {
	row := q.db.QueryRow(ctx, createVocabularyTopic,
		arg.LanguageID,
		arg.Name,
		arg.Icon,
		arg.OrderIndex,
		arg.ParentName,
	)
	var i VocabularyTopic
	err := row.Scan(
		&i.LanguageID,
		&i.Name,
		&i.Icon,
		&i.OrderIndex,
		&i.ParentName,
	)
	return i, err
}

const deleteVocabulary = `-- name: DeleteVocabulary :exec
DELETE FROM vocabularies WHERE id = $1
`

func (q *Queries) DeleteVocabulary(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVocabulary, id)
	return err
}

const deleteVocabularyTopic = `-- name: DeleteVocabularyTopic :exec
DELETE FROM vocabulary_topics WHERE language_id = $1 AND name = $2
`

type DeleteVocabularyTopicParams struct {
	LanguageID string `json:"language_id"`
	Name       string `json:"name"`
}

func (q *Queries) DeleteVocabularyTopic(ctx context.Context, arg DeleteVocabularyTopicParams) error {
	_, err := q.db.Exec(ctx, deleteVocabularyTopic, arg.LanguageID, arg.Name)
	return err
}

const favoriteVocabulary = `-- name: FavoriteVocabulary :exec
INSERT INTO vocabulary_favorites (user_id, vocabulary_id) VALUES ($1, $2)
ON CONFLICT (user_id, vocabulary_id) DO NOTHING
`

type FavoriteVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) FavoriteVocabulary(ctx context.Context, arg FavoriteVocabularyParams) error {
	_, err := q.db.Exec(ctx, favoriteVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const getVocabularyTopic = `-- name: GetVocabularyTopic :one
SELECT language_id, name, icon, order_index, parent_name FROM vocabulary_topics WHERE language_id = $1 AND name = $2
`

type GetVocabularyTopicParams struct {
	LanguageID string `json:"language_id"`
	Name       string `json:"name"`
}

func (q *Queries) GetVocabularyTopic(ctx context.Context, arg GetVocabularyTopicParams) (VocabularyTopic, error) {
	row := q.db.QueryRow(ctx, getVocabularyTopic, arg.LanguageID, arg.Name)
	var i VocabularyTopic
	err := row.Scan(
		&i.LanguageID,
		&i.Name,
		&i.Icon,
		&i.OrderIndex,
		&i.ParentName,
	)
	return i, err
}

const getVocabularyTopicOwnStats = `-- name: GetVocabularyTopicOwnStats :one
SELECT
    COUNT(v.id)::int AS total,
    COUNT(r.id)::int AS learned
FROM vocabularies v
LEFT JOIN user_vocabulary_reviews r ON r.vocabulary_id = v.id AND r.user_id = $1
WHERE v.language_id = $2 AND v.topic = $3
`

type GetVocabularyTopicOwnStatsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
	Topic      pgtype.Text `json:"topic"`
}

type GetVocabularyTopicOwnStatsRow struct {
	Total   int32 `json:"total"`
	Learned int32 `json:"learned"`
}

// Tổng số từ gắn TRỰC TIẾP vào 1 chủ đề (không gộp con) — dùng làm "card Từ
// chung" khi learner drill-down vào chủ đề cha, xem VocabularyService.ListChildTopics.
func (q *Queries) GetVocabularyTopicOwnStats(ctx context.Context, arg GetVocabularyTopicOwnStatsParams) (GetVocabularyTopicOwnStatsRow, error) {
	row := q.db.QueryRow(ctx, getVocabularyTopicOwnStats, arg.UserID, arg.LanguageID, arg.Topic)
	var i GetVocabularyTopicOwnStatsRow
	err := row.Scan(&i.Total, &i.Learned)
	return i, err
}

const likeVocabulary = `-- name: LikeVocabulary :exec
INSERT INTO vocabulary_likes (user_id, vocabulary_id) VALUES ($1, $2)
ON CONFLICT (user_id, vocabulary_id) DO NOTHING
`

type LikeVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) LikeVocabulary(ctx context.Context, arg LikeVocabularyParams) error {
	_, err := q.db.Exec(ctx, likeVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const listFavoriteVocabularies = `-- name: ListFavoriteVocabularies :many
SELECT
    v.id,
    v.language_id,
    v.term,
    v.phonetic,
    v.meaning,
    v.example,
    v.topic,
    v.level,
    v.audio_url,
    v.image_url,
    v.image_emoji,
    COALESCE(t.icon, '')::varchar AS topic_icon,
    (SELECT COUNT(*) FROM vocabulary_likes l WHERE l.vocabulary_id = v.id)::int AS like_count,
    EXISTS (SELECT 1 FROM vocabulary_likes l WHERE l.vocabulary_id = v.id AND l.user_id = $1) AS liked,
    TRUE AS favorited,
    EXISTS (SELECT 1 FROM user_vocabulary_reviews r WHERE r.vocabulary_id = v.id AND r.user_id = $1) AS in_review
FROM vocabulary_favorites fav
JOIN vocabularies v ON v.id = fav.vocabulary_id
LEFT JOIN vocabulary_topics t ON t.language_id = v.language_id AND t.name = v.topic
WHERE fav.user_id = $1
  AND ($2::varchar IS NULL OR v.language_id = $2)
ORDER BY fav.created_at DESC
`

type ListFavoriteVocabulariesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID pgtype.Text `json:"language_id"`
}

type ListFavoriteVocabulariesRow struct {
	ID         pgtype.UUID `json:"id"`
	LanguageID string      `json:"language_id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	ImageUrl   pgtype.Text `json:"image_url"`
	ImageEmoji pgtype.Text `json:"image_emoji"`
	TopicIcon  string      `json:"topic_icon"`
	LikeCount  int32       `json:"like_count"`
	Liked      bool        `json:"liked"`
	Favorited  bool        `json:"favorited"`
	InReview   bool        `json:"in_review"`
}

// language_id để NULL thì lấy yêu thích ở mọi ngôn ngữ.
func (q *Queries) ListFavoriteVocabularies(ctx context.Context, arg ListFavoriteVocabulariesParams) ([]ListFavoriteVocabulariesRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteVocabularies, arg.UserID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteVocabulariesRow
	for rows.Next() {
		var i ListFavoriteVocabulariesRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.ImageEmoji,
			&i.TopicIcon,
			&i.LikeCount,
			&i.Liked,
			&i.Favorited,
			&i.InReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabulariesByLanguageAdmin = `-- name: ListVocabulariesByLanguageAdmin :many
SELECT id, language_id, term, phonetic, meaning, example, topic, level, audio_url, image_url, image_emoji, created_at, COUNT(*) OVER() AS total_count FROM vocabularies
WHERE language_id = $1
  AND ($2::text IS NULL OR term ILIKE '%' || $2::text || '%' OR meaning ILIKE '%' || $2::text || '%')
  AND ($3::text IS NULL OR topic = $3::text)
  AND ($4::text IS NULL OR level = $4::text)
ORDER BY topic, term
LIMIT $6 OFFSET $5
`

type ListVocabulariesByLanguageAdminParams struct {
	LanguageID string      `json:"language_id"`
	Search     pgtype.Text `json:"search"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type ListVocabulariesByLanguageAdminRow struct {
	ID         pgtype.UUID        `json:"id"`
	LanguageID string             `json:"language_id"`
	Term       string             `json:"term"`
	Phonetic   pgtype.Text        `json:"phonetic"`
	Meaning    string             `json:"meaning"`
	Example    pgtype.Text        `json:"example"`
	Topic      pgtype.Text        `json:"topic"`
	Level      pgtype.Text        `json:"level"`
	AudioUrl   pgtype.Text        `json:"audio_url"`
	ImageUrl   pgtype.Text        `json:"image_url"`
	ImageEmoji pgtype.Text        `json:"image_emoji"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	TotalCount int64              `json:"total_count"`
}

// total_count (COUNT(*) OVER()) tính trên toàn bộ kết quả KHỚP filter, trước
// khi LIMIT/OFFSET — FE dùng để vẽ phân trang mà không cần query COUNT riêng.
func (q *Queries) ListVocabulariesByLanguageAdmin(ctx context.Context, arg ListVocabulariesByLanguageAdminParams) ([]ListVocabulariesByLanguageAdminRow, error) {
	rows, err := q.db.Query(ctx, listVocabulariesByLanguageAdmin,
		arg.LanguageID,
		arg.Search,
		arg.Topic,
		arg.Level,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabulariesByLanguageAdminRow
	for rows.Next() {
		var i ListVocabulariesByLanguageAdminRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.ImageEmoji,
			&i.CreatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabulariesByTopic = `-- name: ListVocabulariesByTopic :many
SELECT
    v.id,
    v.language_id,
    v.term,
    v.phonetic,
    v.meaning,
    v.example,
    v.topic,
    v.level,
    v.audio_url,
    v.image_url,
    v.image_emoji,
    COALESCE(t.icon, '')::varchar AS topic_icon,
    (SELECT COUNT(*) FROM vocabulary_likes l WHERE l.vocabulary_id = v.id)::int AS like_count,
    EXISTS (SELECT 1 FROM vocabulary_likes l WHERE l.vocabulary_id = v.id AND l.user_id = $1) AS liked,
    EXISTS (SELECT 1 FROM vocabulary_favorites f WHERE f.vocabulary_id = v.id AND f.user_id = $1) AS favorited,
    EXISTS (SELECT 1 FROM user_vocabulary_reviews r WHERE r.vocabulary_id = v.id AND r.user_id = $1) AS in_review
FROM vocabularies v
LEFT JOIN vocabulary_topics t ON t.language_id = v.language_id AND t.name = v.topic
WHERE v.language_id = $2
  AND v.topic = $3
ORDER BY v.level, v.term
`

type ListVocabulariesByTopicParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
	Topic      pgtype.Text `json:"topic"`
}

type ListVocabulariesByTopicRow struct {
	ID         pgtype.UUID `json:"id"`
	LanguageID string      `json:"language_id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	ImageUrl   pgtype.Text `json:"image_url"`
	ImageEmoji pgtype.Text `json:"image_emoji"`
	TopicIcon  string      `json:"topic_icon"`
	LikeCount  int32       `json:"like_count"`
	Liked      bool        `json:"liked"`
	Favorited  bool        `json:"favorited"`
	InReview   bool        `json:"in_review"`
}

// Cột phải giữ y hệt ListFavoriteVocabularies — service convert qua lại 2 kiểu Row.
func (q *Queries) ListVocabulariesByTopic(ctx context.Context, arg ListVocabulariesByTopicParams) ([]ListVocabulariesByTopicRow, error) {
	rows, err := q.db.Query(ctx, listVocabulariesByTopic, arg.UserID, arg.LanguageID, arg.Topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabulariesByTopicRow
	for rows.Next() {
		var i ListVocabulariesByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.ImageEmoji,
			&i.TopicIcon,
			&i.LikeCount,
			&i.Liked,
			&i.Favorited,
			&i.InReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyChildTopics = `-- name: ListVocabularyChildTopics :many
SELECT
    t.name::varchar AS name,
    COALESCE(t.icon, '📘')::varchar AS icon,
    COUNT(v.id)::int AS total,
    COUNT(r.id)::int AS learned
FROM vocabulary_topics t
LEFT JOIN vocabularies v ON v.language_id = t.language_id AND v.topic = t.name
LEFT JOIN user_vocabulary_reviews r ON r.vocabulary_id = v.id AND r.user_id = $1
WHERE t.language_id = $2 AND t.parent_name = $3
GROUP BY t.name, t.icon, t.order_index
ORDER BY t.order_index, t.name
`

type ListVocabularyChildTopicsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
	ParentName pgtype.Text `json:"parent_name"`
}

type ListVocabularyChildTopicsRow struct {
	Name    string `json:"name"`
	Icon    string `json:"icon"`
	Total   int32  `json:"total"`
	Learned int32  `json:"learned"`
}

// Chủ đề con của 1 chủ đề cha (learner drill-down, GET /vocab/topics/children)
// — total/learned chỉ tính từ gắn trực tiếp vào từng chủ đề con.
func (q *Queries) ListVocabularyChildTopics(ctx context.Context, arg ListVocabularyChildTopicsParams) ([]ListVocabularyChildTopicsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyChildTopics, arg.UserID, arg.LanguageID, arg.ParentName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyChildTopicsRow
	for rows.Next() {
		var i ListVocabularyChildTopicsRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Learned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyTopicRelations = `-- name: ListVocabularyTopicRelations :many
SELECT name, parent_name, icon FROM vocabulary_topics WHERE language_id = $1
`

type ListVocabularyTopicRelationsRow struct {
	Name       string      `json:"name"`
	ParentName pgtype.Text `json:"parent_name"`
	Icon       string      `json:"icon"`
}

// Toàn bộ quan hệ cha/con của 1 ngôn ngữ (không phân trang — chỉ vài chục
// dòng) — dùng để dựng cây 2 cấp cho learner, xem VocabularyService.ListTopics.
func (q *Queries) ListVocabularyTopicRelations(ctx context.Context, languageID string) ([]ListVocabularyTopicRelationsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyTopicRelations, languageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyTopicRelationsRow
	for rows.Next() {
		var i ListVocabularyTopicRelationsRow
		if err := rows.Scan(&i.Name, &i.ParentName, &i.Icon); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyTopics = `-- name: ListVocabularyTopics :many
SELECT
    v.topic::varchar AS name,
    COALESCE(t.icon, '📘')::varchar AS icon,
    COUNT(*)::int AS total,
    COUNT(r.id)::int AS learned
FROM vocabularies v
LEFT JOIN vocabulary_topics t ON t.language_id = v.language_id AND t.name = v.topic
LEFT JOIN user_vocabulary_reviews r ON r.vocabulary_id = v.id AND r.user_id = $1
WHERE v.language_id = $2
  AND v.topic IS NOT NULL
GROUP BY v.topic, t.icon, t.order_index
ORDER BY COALESCE(t.order_index, 2147483647), v.topic
`

type ListVocabularyTopicsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
}

type ListVocabularyTopicsRow struct {
	Name    string `json:"name"`
	Icon    string `json:"icon"`
	Total   int32  `json:"total"`
	Learned int32  `json:"learned"`
}

// Chủ đề lấy từ vocabularies.topic; icon/thứ tự từ vocabulary_topics nếu có.
// learned = số từ trong chủ đề user đã đưa vào hàng đợi SRS.
func (q *Queries) ListVocabularyTopics(ctx context.Context, arg ListVocabularyTopicsParams) ([]ListVocabularyTopicsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyTopics, arg.UserID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyTopicsRow
	for rows.Next() {
		var i ListVocabularyTopicsRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Learned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyTopicsByLanguageAdmin = `-- name: ListVocabularyTopicsByLanguageAdmin :many
SELECT language_id, name, icon, order_index, parent_name, COUNT(*) OVER() AS total_count FROM vocabulary_topics
WHERE language_id = $1
  AND ($2::text IS NULL OR name ILIKE '%' || $2::text || '%')
ORDER BY order_index, name
LIMIT $4 OFFSET $3
`

type ListVocabularyTopicsByLanguageAdminParams struct {
	LanguageID string      `json:"language_id"`
	Search     pgtype.Text `json:"search"`
	Offset     int32       `json:"offset"`
	Limit      int32       `json:"limit"`
}

type ListVocabularyTopicsByLanguageAdminRow struct {
	LanguageID string      `json:"language_id"`
	Name       string      `json:"name"`
	Icon       string      `json:"icon"`
	OrderIndex int32       `json:"order_index"`
	ParentName pgtype.Text `json:"parent_name"`
	TotalCount int64       `json:"total_count"`
}

func (q *Queries) ListVocabularyTopicsByLanguageAdmin(ctx context.Context, arg ListVocabularyTopicsByLanguageAdminParams) ([]ListVocabularyTopicsByLanguageAdminRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyTopicsByLanguageAdmin,
		arg.LanguageID,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyTopicsByLanguageAdminRow
	for rows.Next() {
		var i ListVocabularyTopicsByLanguageAdminRow
		if err := rows.Scan(
			&i.LanguageID,
			&i.Name,
			&i.Icon,
			&i.OrderIndex,
			&i.ParentName,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfavoriteVocabulary = `-- name: UnfavoriteVocabulary :exec
DELETE FROM vocabulary_favorites WHERE user_id = $1 AND vocabulary_id = $2
`

type UnfavoriteVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) UnfavoriteVocabulary(ctx context.Context, arg UnfavoriteVocabularyParams) error {
	_, err := q.db.Exec(ctx, unfavoriteVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const unlikeVocabulary = `-- name: UnlikeVocabulary :exec
DELETE FROM vocabulary_likes WHERE user_id = $1 AND vocabulary_id = $2
`

type UnlikeVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) UnlikeVocabulary(ctx context.Context, arg UnlikeVocabularyParams) error {
	_, err := q.db.Exec(ctx, unlikeVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const updateVocabulary = `-- name: UpdateVocabulary :one
UPDATE vocabularies
SET term = $2, phonetic = $3, meaning = $4, example = $5, topic = $6, level = $7,
    audio_url = $8, image_url = $9, image_emoji = $10
WHERE id = $1
RETURNING id, language_id, term, phonetic, meaning, example, topic, level, audio_url, image_url, image_emoji, created_at
`

type UpdateVocabularyParams struct {
	ID         pgtype.UUID `json:"id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	ImageUrl   pgtype.Text `json:"image_url"`
	ImageEmoji pgtype.Text `json:"image_emoji"`
}

func (q *Queries) UpdateVocabulary(ctx context.Context, arg UpdateVocabularyParams) (Vocabulary, error) {
	row := q.db.QueryRow(ctx, updateVocabulary,
		arg.ID,
		arg.Term,
		arg.Phonetic,
		arg.Meaning,
		arg.Example,
		arg.Topic,
		arg.Level,
		arg.AudioUrl,
		arg.ImageUrl,
		arg.ImageEmoji,
	)
	var i Vocabulary
	err := row.Scan(
		&i.ID,
		&i.LanguageID,
		&i.Term,
		&i.Phonetic,
		&i.Meaning,
		&i.Example,
		&i.Topic,
		&i.Level,
		&i.AudioUrl,
		&i.ImageUrl,
		&i.ImageEmoji,
		&i.CreatedAt,
	)
	return i, err
}
