// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVocabularyLikes = `-- name: CountVocabularyLikes :one
SELECT COUNT(*)::int FROM vocabulary_likes WHERE vocabulary_id = $1
`

func (q *Queries) CountVocabularyLikes(ctx context.Context, vocabularyID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, countVocabularyLikes, vocabularyID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const favoriteVocabulary = `-- name: FavoriteVocabulary :exec
INSERT INTO vocabulary_favorites (user_id, vocabulary_id) VALUES ($1, $2)
ON CONFLICT (user_id, vocabulary_id) DO NOTHING
`

type FavoriteVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) FavoriteVocabulary(ctx context.Context, arg FavoriteVocabularyParams) error {
	_, err := q.db.Exec(ctx, favoriteVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const likeVocabulary = `-- name: LikeVocabulary :exec
INSERT INTO vocabulary_likes (user_id, vocabulary_id) VALUES ($1, $2)
ON CONFLICT (user_id, vocabulary_id) DO NOTHING
`

type LikeVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) LikeVocabulary(ctx context.Context, arg LikeVocabularyParams) error {
	_, err := q.db.Exec(ctx, likeVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const listFavoriteVocabularies = `-- name: ListFavoriteVocabularies :many
SELECT
    v.id,
    v.language_id,
    v.term,
    v.phonetic,
    v.meaning,
    v.example,
    v.topic,
    v.level,
    v.audio_url,
    v.image_url,
    v.image_emoji,
    COALESCE(t.icon, '')::varchar AS topic_icon,
    (SELECT COUNT(*) FROM vocabulary_likes l WHERE l.vocabulary_id = v.id)::int AS like_count,
    EXISTS (SELECT 1 FROM vocabulary_likes l WHERE l.vocabulary_id = v.id AND l.user_id = $1) AS liked,
    TRUE AS favorited,
    EXISTS (SELECT 1 FROM user_vocabulary_reviews r WHERE r.vocabulary_id = v.id AND r.user_id = $1) AS in_review
FROM vocabulary_favorites fav
JOIN vocabularies v ON v.id = fav.vocabulary_id
LEFT JOIN vocabulary_topics t ON t.language_id = v.language_id AND t.name = v.topic
WHERE fav.user_id = $1
  AND ($2::varchar IS NULL OR v.language_id = $2)
ORDER BY fav.created_at DESC
`

type ListFavoriteVocabulariesParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID pgtype.Text `json:"language_id"`
}

type ListFavoriteVocabulariesRow struct {
	ID         pgtype.UUID `json:"id"`
	LanguageID string      `json:"language_id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	ImageUrl   pgtype.Text `json:"image_url"`
	ImageEmoji pgtype.Text `json:"image_emoji"`
	TopicIcon  string      `json:"topic_icon"`
	LikeCount  int32       `json:"like_count"`
	Liked      bool        `json:"liked"`
	Favorited  bool        `json:"favorited"`
	InReview   bool        `json:"in_review"`
}

// language_id để NULL thì lấy yêu thích ở mọi ngôn ngữ.
func (q *Queries) ListFavoriteVocabularies(ctx context.Context, arg ListFavoriteVocabulariesParams) ([]ListFavoriteVocabulariesRow, error) {
	rows, err := q.db.Query(ctx, listFavoriteVocabularies, arg.UserID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFavoriteVocabulariesRow
	for rows.Next() {
		var i ListFavoriteVocabulariesRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.ImageEmoji,
			&i.TopicIcon,
			&i.LikeCount,
			&i.Liked,
			&i.Favorited,
			&i.InReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabulariesByTopic = `-- name: ListVocabulariesByTopic :many
SELECT
    v.id,
    v.language_id,
    v.term,
    v.phonetic,
    v.meaning,
    v.example,
    v.topic,
    v.level,
    v.audio_url,
    v.image_url,
    v.image_emoji,
    COALESCE(t.icon, '')::varchar AS topic_icon,
    (SELECT COUNT(*) FROM vocabulary_likes l WHERE l.vocabulary_id = v.id)::int AS like_count,
    EXISTS (SELECT 1 FROM vocabulary_likes l WHERE l.vocabulary_id = v.id AND l.user_id = $1) AS liked,
    EXISTS (SELECT 1 FROM vocabulary_favorites f WHERE f.vocabulary_id = v.id AND f.user_id = $1) AS favorited,
    EXISTS (SELECT 1 FROM user_vocabulary_reviews r WHERE r.vocabulary_id = v.id AND r.user_id = $1) AS in_review
FROM vocabularies v
LEFT JOIN vocabulary_topics t ON t.language_id = v.language_id AND t.name = v.topic
WHERE v.language_id = $2
  AND v.topic = $3
ORDER BY v.level, v.term
`

type ListVocabulariesByTopicParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
	Topic      pgtype.Text `json:"topic"`
}

type ListVocabulariesByTopicRow struct {
	ID         pgtype.UUID `json:"id"`
	LanguageID string      `json:"language_id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      pgtype.Text `json:"topic"`
	Level      pgtype.Text `json:"level"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	ImageUrl   pgtype.Text `json:"image_url"`
	ImageEmoji pgtype.Text `json:"image_emoji"`
	TopicIcon  string      `json:"topic_icon"`
	LikeCount  int32       `json:"like_count"`
	Liked      bool        `json:"liked"`
	Favorited  bool        `json:"favorited"`
	InReview   bool        `json:"in_review"`
}

// Cột phải giữ y hệt ListFavoriteVocabularies — service convert qua lại 2 kiểu Row.
func (q *Queries) ListVocabulariesByTopic(ctx context.Context, arg ListVocabulariesByTopicParams) ([]ListVocabulariesByTopicRow, error) {
	rows, err := q.db.Query(ctx, listVocabulariesByTopic, arg.UserID, arg.LanguageID, arg.Topic)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabulariesByTopicRow
	for rows.Next() {
		var i ListVocabulariesByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.AudioUrl,
			&i.ImageUrl,
			&i.ImageEmoji,
			&i.TopicIcon,
			&i.LikeCount,
			&i.Liked,
			&i.Favorited,
			&i.InReview,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVocabularyTopics = `-- name: ListVocabularyTopics :many
SELECT
    v.topic::varchar AS name,
    COALESCE(t.icon, '📘')::varchar AS icon,
    COUNT(*)::int AS total,
    COUNT(r.id)::int AS learned
FROM vocabularies v
LEFT JOIN vocabulary_topics t ON t.language_id = v.language_id AND t.name = v.topic
LEFT JOIN user_vocabulary_reviews r ON r.vocabulary_id = v.id AND r.user_id = $1
WHERE v.language_id = $2
  AND v.topic IS NOT NULL
GROUP BY v.topic, t.icon, t.order_index
ORDER BY COALESCE(t.order_index, 2147483647), v.topic
`

type ListVocabularyTopicsParams struct {
	UserID     pgtype.UUID `json:"user_id"`
	LanguageID string      `json:"language_id"`
}

type ListVocabularyTopicsRow struct {
	Name    string `json:"name"`
	Icon    string `json:"icon"`
	Total   int32  `json:"total"`
	Learned int32  `json:"learned"`
}

// Chủ đề lấy từ vocabularies.topic; icon/thứ tự từ vocabulary_topics nếu có.
// learned = số từ trong chủ đề user đã đưa vào hàng đợi SRS.
func (q *Queries) ListVocabularyTopics(ctx context.Context, arg ListVocabularyTopicsParams) ([]ListVocabularyTopicsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyTopics, arg.UserID, arg.LanguageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyTopicsRow
	for rows.Next() {
		var i ListVocabularyTopicsRow
		if err := rows.Scan(
			&i.Name,
			&i.Icon,
			&i.Total,
			&i.Learned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unfavoriteVocabulary = `-- name: UnfavoriteVocabulary :exec
DELETE FROM vocabulary_favorites WHERE user_id = $1 AND vocabulary_id = $2
`

type UnfavoriteVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) UnfavoriteVocabulary(ctx context.Context, arg UnfavoriteVocabularyParams) error {
	_, err := q.db.Exec(ctx, unfavoriteVocabulary, arg.UserID, arg.VocabularyID)
	return err
}

const unlikeVocabulary = `-- name: UnlikeVocabulary :exec
DELETE FROM vocabulary_likes WHERE user_id = $1 AND vocabulary_id = $2
`

type UnlikeVocabularyParams struct {
	UserID       pgtype.UUID `json:"user_id"`
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
}

func (q *Queries) UnlikeVocabulary(ctx context.Context, arg UnlikeVocabularyParams) error {
	_, err := q.db.Exec(ctx, unlikeVocabulary, arg.UserID, arg.VocabularyID)
	return err
}
