// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary_exercises.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createVocabularyExercise = `-- name: CreateVocabularyExercise :one
INSERT INTO vocabulary_exercises (vocabulary_id, exercise_type, question, options, correct_answer, difficulty, metadata)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, vocabulary_id, exercise_type, question, options, correct_answer, distractor_count, difficulty, metadata, created_at
`

type CreateVocabularyExerciseParams struct {
	VocabularyID  pgtype.UUID `json:"vocabulary_id"`
	ExerciseType  string      `json:"exercise_type"`
	Question      string      `json:"question"`
	Options       []byte      `json:"options"`
	CorrectAnswer string      `json:"correct_answer"`
	Difficulty    pgtype.Int4 `json:"difficulty"`
	Metadata      []byte      `json:"metadata"`
}

func (q *Queries) CreateVocabularyExercise(ctx context.Context, arg CreateVocabularyExerciseParams) (VocabularyExercise, error) {
	row := q.db.QueryRow(ctx, createVocabularyExercise,
		arg.VocabularyID,
		arg.ExerciseType,
		arg.Question,
		arg.Options,
		arg.CorrectAnswer,
		arg.Difficulty,
		arg.Metadata,
	)
	var i VocabularyExercise
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.ExerciseType,
		&i.Question,
		&i.Options,
		&i.CorrectAnswer,
		&i.DistractorCount,
		&i.Difficulty,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getExerciseByTypeForVocabularies = `-- name: GetExerciseByTypeForVocabularies :many
SELECT ve.id, ve.vocabulary_id, ve.exercise_type, ve.question, ve.options, ve.correct_answer, ve.distractor_count, ve.difficulty, ve.metadata, ve.created_at, v.term, v.meaning
FROM vocabulary_exercises ve
JOIN vocabularies v ON ve.vocabulary_id = v.id
WHERE ve.vocabulary_id = ANY($1::uuid[])
  AND ve.exercise_type = $2
`

type GetExerciseByTypeForVocabulariesParams struct {
	Column1      []pgtype.UUID `json:"column_1"`
	ExerciseType string        `json:"exercise_type"`
}

type GetExerciseByTypeForVocabulariesRow struct {
	ID              pgtype.UUID        `json:"id"`
	VocabularyID    pgtype.UUID        `json:"vocabulary_id"`
	ExerciseType    string             `json:"exercise_type"`
	Question        string             `json:"question"`
	Options         []byte             `json:"options"`
	CorrectAnswer   string             `json:"correct_answer"`
	DistractorCount pgtype.Int4        `json:"distractor_count"`
	Difficulty      pgtype.Int4        `json:"difficulty"`
	Metadata        []byte             `json:"metadata"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Term            string             `json:"term"`
	Meaning         string             `json:"meaning"`
}

func (q *Queries) GetExerciseByTypeForVocabularies(ctx context.Context, arg GetExerciseByTypeForVocabulariesParams) ([]GetExerciseByTypeForVocabulariesRow, error) {
	rows, err := q.db.Query(ctx, getExerciseByTypeForVocabularies, arg.Column1, arg.ExerciseType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExerciseByTypeForVocabulariesRow
	for rows.Next() {
		var i GetExerciseByTypeForVocabulariesRow
		if err := rows.Scan(
			&i.ID,
			&i.VocabularyID,
			&i.ExerciseType,
			&i.Question,
			&i.Options,
			&i.CorrectAnswer,
			&i.DistractorCount,
			&i.Difficulty,
			&i.Metadata,
			&i.CreatedAt,
			&i.Term,
			&i.Meaning,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVocabularyExercise = `-- name: GetVocabularyExercise :one
SELECT id, vocabulary_id, exercise_type, question, options, correct_answer, distractor_count, difficulty, metadata, created_at FROM vocabulary_exercises
WHERE vocabulary_id = $1 AND exercise_type = $2
`

type GetVocabularyExerciseParams struct {
	VocabularyID pgtype.UUID `json:"vocabulary_id"`
	ExerciseType string      `json:"exercise_type"`
}

func (q *Queries) GetVocabularyExercise(ctx context.Context, arg GetVocabularyExerciseParams) (VocabularyExercise, error) {
	row := q.db.QueryRow(ctx, getVocabularyExercise, arg.VocabularyID, arg.ExerciseType)
	var i VocabularyExercise
	err := row.Scan(
		&i.ID,
		&i.VocabularyID,
		&i.ExerciseType,
		&i.Question,
		&i.Options,
		&i.CorrectAnswer,
		&i.DistractorCount,
		&i.Difficulty,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}
