// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vocabulary_topics.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listVocabularyTopics = `-- name: ListVocabularyTopics :many
SELECT
    v.topic,
    COUNT(*) as vocabulary_count
FROM vocabularies v
WHERE v.language_id = $1
  AND v.topic IS NOT NULL
  AND v.topic != ''
  AND NOT EXISTS (
    SELECT 1 FROM user_vocabulary_reviews r
    WHERE r.user_id = $2 AND r.vocabulary_id = v.id
  )
GROUP BY v.topic
ORDER BY v.topic
`

type ListVocabularyTopicsRow struct {
	Topic             string `json:"topic"`
	VocabularyCount   int64  `json:"vocabulary_count"`
}

func (q *Queries) ListVocabularyTopics(ctx context.Context, arg ListVocabularyTopicsParams) ([]ListVocabularyTopicsRow, error) {
	rows, err := q.db.Query(ctx, listVocabularyTopics, arg.LanguageID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabularyTopicsRow
	for rows.Next() {
		var i ListVocabularyTopicsRow
		if err := rows.Scan(&i.Topic, &i.VocabularyCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type ListVocabularyTopicsParams struct {
	LanguageID string      `json:"language_id"`
	UserID     pgtype.UUID `json:"user_id"`
}

const listVocabulariesByTopic = `-- name: ListVocabulariesByTopic :many
SELECT
    v.id,
    v.language_id,
    v.term,
    v.phonetic,
    v.meaning,
    v.example,
    v.topic,
    v.level,
    v.image_url,
    v.audio_url,
    v.created_at
FROM vocabularies v
WHERE v.language_id = $1
  AND v.topic = $2
  AND NOT EXISTS (
    SELECT 1 FROM user_vocabulary_reviews r
    WHERE r.user_id = $3 AND r.vocabulary_id = v.id
  )
ORDER BY v.term
`

type ListVocabulariesByTopicRow struct {
	ID         pgtype.UUID `json:"id"`
	LanguageID string      `json:"language_id"`
	Term       string      `json:"term"`
	Phonetic   pgtype.Text `json:"phonetic"`
	Meaning    string      `json:"meaning"`
	Example    pgtype.Text `json:"example"`
	Topic      string      `json:"topic"`
	Level      string      `json:"level"`
	ImageUrl   pgtype.Text `json:"image_url"`
	AudioUrl   pgtype.Text `json:"audio_url"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListVocabulariesByTopic(ctx context.Context, arg ListVocabulariesByTopicParams) ([]ListVocabulariesByTopicRow, error) {
	rows, err := q.db.Query(ctx, listVocabulariesByTopic, arg.LanguageID, arg.Topic, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVocabulariesByTopicRow
	for rows.Next() {
		var i ListVocabulariesByTopicRow
		if err := rows.Scan(
			&i.ID,
			&i.LanguageID,
			&i.Term,
			&i.Phonetic,
			&i.Meaning,
			&i.Example,
			&i.Topic,
			&i.Level,
			&i.ImageUrl,
			&i.AudioUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type ListVocabulariesByTopicParams struct {
	LanguageID string      `json:"language_id"`
	Topic     string      `json:"topic"`
	UserID    pgtype.UUID `json:"user_id"`
}
